### ISSUE TITLE
The Legend of Zelda Spirit Tracks (Release Build) (Still slow down)

### ISSUE THREAD

**Issue by tabnk** [TASVideos/desmume#10]
Complied with VS 2015 and already change to release build (DeSmuME-VS2015-x64-Release)

Setting: Both OpenGL and Software mode (Native resolution). 
It's still slow down as before. 

Any other debug option I need to disable ?

![image](https://cloud.githubusercontent.com/assets/10874582/21124811/171b43c4-c11c-11e6-997a-62fa3174b60f.png)

![image](https://cloud.githubusercontent.com/assets/10874582/21124825/2e03deca-c11c-11e6-9c8a-853903920852.png)

Source code:
https://github.com/TASVideos/desmume

**Comment by zeromus** [comment]
what CPU are you running? try changing desmume's config > display method options (systems with faulty GPUs can run slow until they're adjusted)

**Comment by tabnk** [comment]
I'm was using DirectDraw HW.

I'm changed display method to DirectDraw SW and OpenGL but still same slow down.

CPU: Intel 3770. 
GPU: AMD R290 and Nvidia GTX 960 (Tested Both)

![image](https://cloud.githubusercontent.com/assets/10874582/21125843/6999844c-c123-11e6-9b44-bb4daaf1e768.png)

**Comment by rogerman** [comment]
This is a very difficult scene for DeSmuME to render. It uses dual-screen 3D, lots of polygons and special effects, and the biggest slow down of all -- the texture thrashing. The slow down that you're noticing is when the texture thrashing is at its worst.

I can guarantee you that all past versions of DeSmuME have exhibited this behavior. However, recent improvements in both the 2D and 3D code have yielded performance improvements. In my experience with this scene, I'm observing better FPS in the latest code compared to v0.9.11 with all the hardware I've tested with.

If your complaint is that the earlier part of the scene (when the train is shown and Zelda is flying around) is slower than the later part of the scene (when the train is no longer shown and the birds fly away), then there really is no issue here -- it is simply a difference of rendering complexity in this particular scene of this game, and your hardware is simply not able keep up.

Your Intel i7-3770 should easily run through this scene without any issues, as I've run this scene without slow down on much lesser hardware. Something must be wrong with your computer.

**Comment by tabnk** [comment]
Unlikely to be hardware issues. I'm got two set of systems (Intel 3770 and 4590). Both systems experiences slow down. 

If isn't a bug than it could be Windows 10 causing it.  However it is working fine, if I use latest Stable Release: v0.9.11.

**Comment by zeromus** [comment]
you have "tex deposterize" and "tex smoothing" enabled. That hurts when the texture is thrashing.
Woops, I accidentally made those the defaults on commit e0f8e5a.

**Comment by tabnk** [comment]
Thank. Problem solved.
