### ISSUE TITLE
DeSmuME is being flagged as generic malware now..

### ISSUE THREAD

**Issue by hamsterben5** [TASVideos/desmume#101]
Hey, probably not a big deal but just wanted to let you know that with a ton of AVGs I've been using, someone flagged DeSmuME so many times the builds are being pointed out as "Bad reputation, potentially malware". You could clear this up with Avast! or whoever else is flagging it. 
![screenshot_30](https://user-images.githubusercontent.com/6598846/31103611-db10b794-a7a5-11e7-89aa-47887bc2130a.png)
![screenshot_31](https://user-images.githubusercontent.com/6598846/31103636-fab6bd00-a7a5-11e7-89ba-8c4ad84836d1.png)
![screenshot_32](https://user-images.githubusercontent.com/6598846/31103693-557b5994-a7a6-11e7-8427-6f64cf5b7b77.png)

**Comment by zeromus** [comment]
Please check files on virustotal before paying any attention to what one particular AV software says. Their heuristics are triggering false positives with regularity.
