### ISSUE TITLE
Magnification Filter is not working with increased Resolution

### ISSUE THREAD

**Issue by Papermanzero** [TASVideos/desmume#106]
Version: windows latest commit.
If the user enables highet resolution rendering (e.g 2x 3x etc) magnification filters like bilinear, xbrz are disabled although they are selected (activated).
Solution could be either to apply the fullscreen filter on top of the higher resolution rendering or to grey out the magnification filter if higher resolution is enabled.

**Comment by zeromus** [comment]
no they aren't. assume they arent (because they arent) and attempt to describe your problem from that point.

**Comment by Papermanzero** [comment]
It's just a usability problem.
From a user point of view I was expecting the magnification filter will be applied on top of the high resolution rendering. If this is not possible, the magnification filter should be grey (user cannot choose a filter).

My attention was to filter the sprites. but this is a different issue, which (I guess) roger explained in the forum (rewrite of graphic handling with a lot of effort)

**Comment by zeromus** [comment]
The magnification is applied on top of the high resolution rendering.

**Comment by Papermanzero** [comment]
Had the time to reproduce the issue with the latest commit.
First screeshot shows the default settings with OpenGL
<img width="641" alt="1" src="https://user-images.githubusercontent.com/10263536/31791362-a04c5516-b518-11e7-8a26-eafc6c20590d.PNG">
These are the settings
<img width="356" alt="2" src="https://user-images.githubusercontent.com/10263536/31791395-b8948076-b518-11e7-9590-e72beed5c195.PNG">
Then I activate the magnification filter
<img width="356" alt="2" src="https://user-images.githubusercontent.com/10263536/31791425-c757999a-b518-11e7-8b54-bbe88d3f6b19.PNG">
This is the following result
<img width="769" alt="4" src="https://user-images.githubusercontent.com/10263536/31791464-dc2c2ab6-b518-11e7-8a7f-2cfaef8f1070.PNG">
Everything is fine so far. However If I increase now the resolution in the 3D settings...
<img width="356" alt="5" src="https://user-images.githubusercontent.com/10263536/31791475-e953ccda-b518-11e7-8306-8e127ac704de.PNG">
The magnification filter is deactivated, however the higher resolution is applied.
<img width="769" alt="6" src="https://user-images.githubusercontent.com/10263536/31791492-00950224-b519-11e7-983a-947e48ac0f10.PNG">
If I check the settings for the magnifiaction filter. It is still the same as in screenshot 2.

**Comment by zeromus** [comment]
You have doubled the resolution, then doubled it again. That should yield a 1024x768 screen. Yet your screens are 640x480, about half of what it should be. How do you expect to see the results of doubling twice when your window is only doubled once?

Here's how. Look more closely. Zoom in on the 'S' in Select the game in screenshot 4 and compare to screenshot 1.

**Comment by Papermanzero** [comment]
Now I got you, thanks. 

Just my experience from a user point of view, the dependencies between window size, magnification filter and GPU scaling are not obvious. The behaviours of the features are not aligned.
Means, if I activated the 2xBRZ, the windows size will be doubled automatically.
If I would activate the GPU scaling the same behaviour should occur. Means another doubling of the windiws size. But this does not happen.
But in any case I am still able to adjust the window size independet of the set magnification filter or GPU scaling. This is a little bit confusing.

Maybe there are better ways to embed the features in the UI.
I know, it is easy to say "maybe you could bla bla bla".
I don't want to say you have to change it. 
I know, changing something could lead in major redesigns of code or architecture.  
It is just my experience from an end user point of view, and maybe it could be helpful for future changes.

**Comment by zeromus** [comment]
I like to see the effects of changing the GPU scaling without having the window go nuts. That makes considerably less sense for the magnification filters. The purpose if magnification filters is to stretch the window and manufacture details. So you'd want to see those details, or there's no point. The purpose of GPU scaling is to keep from losing details which existed in the first place. To me that's opposite enough to warrant the separate treatment, although I admit the combination of them isn't entirely obvious. Still, I thought anyone who changed the GPU scale and then thought "I saw no effect" would immediately think "guess I have to change the window size". I also thought anyone who changed the GPU scale would do that BEFORE setting a magnification filter, because otherwise the results of whatever beenfit the GPU scaling gets you is munged beyond recognition.
