### ISSUE TITLE
Feature Request: Fullscreen Exclusive Display Mode

### ISSUE THREAD

**Issue by Nicholas-Steel** [TASVideos/desmume#108]
It would be fantastic if such a display mode could be implemented for the emulator because it would allow me (& others) a means of using the emulator without the DWM messing with VSYNC.

The DWM causes frequent periodic "bursts" of anomalous stuttering in most programs on my PC and has done so since Windows Vista was new (I worked around this by switching games to Fullscreen Exclusive Display Modes). There are a few programs out there that work fine in windowed and borderless fullscreen on my PC but there really aren't many.

The only hardware components I haven't replaced over the years was the Monitor, Motherboard and CPU. I assume one of these 3 components hates the DWM (likely the monitor I guess).

Windows 10 x64 (latest updates, including the recent FCU)
Intel i7 920 @ 3.6Ghz
Geforce 760 4GB
24GB DDR3 1500~MHZ RAM
ASUS P6T Motherboard
Samsung P2350 monitor

**Comment by zeromus** [comment]
we don't need a bug report to track this obvious suggestion
