### ISSUE TITLE
GPU.cpp and texcache.cpp still hardcode to bind SSE2 colorspace covert functions even enable AVX2 extension.

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#11]
void GPUEngineBase::_RenderPixelsCustomVRAM(GPUEngineCompositorInfo &compInfo)
{
.........
			if (OUTPUTFORMAT == NDSColorFormat_BGR666_Rev)
			{
				ColorspaceConvert555To6665Opaque_SSE2<false>(src16[0], src[0], src[1]);
				ColorspaceConvert555To6665Opaque_SSE2<false>(src16[1], src[2], src[3]);
			}
			else
			{
				ColorspaceConvert555To8888Opaque_SSE2<false>(src16[0], src[0], src[1]);
				ColorspaceConvert555To8888Opaque_SSE2<false>(src16[1], src[2], src[3]);
			}
..............
}

**Comment by zeromus** [comment]
because that code only supports SSE2 for other reasons. read up 11 lines.
