### ISSUE TITLE
Touch screen input no longer works after git#1742114 in macOS

### ISSUE THREAD

**Issue by microbug** [TASVideos/desmume#110]
Tested with Pokémon Platinum. Git#1742114 works as expected; in the opening scene when you have to touch the pokeball, I can click on the centre (with a touchpad or mouse) and the game registers the click. In git#059ea51 and later this is not the case: the status bar at the bottom shows that a click is registered by DeSmuME but the game does not register it. (For some reason the macOS link to git#70c69a4 actually goes to git#64d58b9 so I can't test that version).

I'm on macOS 10.13 build 17A405, happy to provide any further information requested.

**Comment by rogerman** [comment]
I'm almost sure that it's a bug that's affecting Macs with Retina Displays. I'm looking into it.

But help me confirm my hunch first. Can you report to me your Mac's Model Identifier? You can find this information by going to DeSmuME > About DeSmuME. Just copy-paste the Model Identifier here.

**Comment by microbug** [comment]
My model identifier is MacBookPro13,3 (MacBook Pro 2016) — a Retina display model.

**Comment by rogerman** [comment]
Thanks for the info, I should have this resolved shortly.

**Comment by microbug** [comment]
Thanks, the new version works as expected :D
