### ISSUE TITLE
Can't import save file from no$gba

### ISSUE THREAD

**Issue by avipup** [TASVideos/desmume#113]
I can't import the attached savegame file (for Final Fantasy Tactics Advance 2).
I tried with 0.9.11 and the latest 2017-10-20 build.
Windows version, x64.
The save file comes from no$gba 2.8c.

When importing I chose the first AUTO option and then tried a couple of items in the manual dropdown.
Nothing seems to work.

[ffta2u.zip](https://github.com/TASVideos/desmume/files/1418449/ffta2u.zip)

**Comment by zeromus** [comment]
desmume doesnt support this, use "google" to find a converter
