### ISSUE TITLE
Cant delete the file

### ISSUE THREAD

**Issue by TomoeXDAZ** [TASVideos/desmume#114]
![asd](https://user-images.githubusercontent.com/33341769/32362969-e2603f1c-c03a-11e7-86a9-ae568c1862d4.PNG)
im the administrator to my PC... 
and i cant even shred the dang file.
whats going on?

**Comment by zeromus** [comment]
not our problem. find a windows sysadmin to help you, or ask your brother who downloaded it on a different user account.

**Comment by TomoeXDAZ** [comment]
this PC only has one user account. 
sysadmin..

**Comment by zeromus** [comment]
ask the internet for windows support, this has nothing to do with desmume
