### ISSUE TITLE
Mario and sonic at the olympic wintergames Bug. 

### ISSUE THREAD

**Issue by DaBreezee** [TASVideos/desmume#117]
so uh, when go in the cannon to icepeak, (a part where you have to go through in the story) i see a glimpse of icepeak and then it freezes i really want to continue so ill hope you fix it! (also, please dont humiliate me just because i like these sort of games.)

**Comment by zeromus** [comment]
https://sourceforge.net/p/desmume/bugs/1455/
find a patched rom
the game freezes due to marginal timing problems.
it freezes on flash carts as well.
