### ISSUE TITLE
[feature request] add AVX2 version texture unpack functions for texcache.cpp

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#12]
Texture unpack functions are called frequently and current Desmume only has SSE2 version of texture unpack functions for texcache.cpp. If it won't cost too many efforts to implement AVX2 version of these functions, it should improve Desmume perfomance a lot.

**Comment by zeromus** [comment]
We don't need suggestions from gamers on what code to speed up
