### ISSUE TITLE
[Linux] Crash on Graphics OpenGL Selection

### ISSUE THREAD

**Issue by Enverex** [TASVideos/desmume#126]
Opening the GUI, selecting OpenGL in Graphics Settings and then hitting OK results in the interface crashing. Here's the console output from when it happens. It then seems to crash immediately on the next startup too, but then works the next time - that appears to be because it's defaulted back to Software at this point.

```
CPU mode: Interpreter
Microphone successfully inited.
DeSmuME 0.9.12 git#0 x64-JIT SSE4.2+AVX2

Using 8 threads for video filter.
SoftRast Initialized with cores=8
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

This is built from GIT as of about 20 minutes ago. This is on a machine using the official Nvidia drivers with a GTX1060.

**Comment by davg-qqq** [comment]
Crash happens at https://github.com/TASVideos/desmume/blob/d556c99771d8d303226e16caf43399c6b5390624/desmume/src/OGLRender_3_2.cpp#L2036
The results of a gl api call are being used to create a std::string, but in the configuration described above (desmume built with --enable-osmesa and proprietary nvidia drivers) the api is returning null causing a crash.
Adding a null check fixes the crash. The renderer will still fail to initialize and desmume will switch back to software rasterizer.
