### ISSUE TITLE
colorspacehandler_AVX2 breaks Chrono Trigger video with 32-bit color

### ISSUE THREAD

**Issue by bearoso** [TASVideos/desmume#131]
Enabling AVX2 support causes the Chrono Trigger opening video to have the blue channel in the wrong place. Patch attached.
[colorspace_AVX2.patch.txt](https://github.com/TASVideos/desmume/files/1800555/colorspace_AVX2.patch.txt)

**Comment by bearoso** [comment]
Might want to check the ColorspaceConvert555To6665_AVX2 function, too. Looks like the same problem, but I have no test case.

**Comment by rogerman** [comment]
Fixed this particular issue in commit 249d41d, along with some other similar bugs. Thanks for the report!
