### ISSUE TITLE
Slot1 "Retail DEBUG" mode is inaccurate

### ISSUE THREAD

**Issue by mariomadproductions** [TASVideos/desmume#133]
For example, in New Super Mario Bros. (USA), on boot, the command windows says that the file `\data\polygon_unit\wire_netting8.nsbtx` is loaded, but there is no reason why this file would be loaded on the boot, and corrupting the file doesn't change the functionality of the game on boot.

**Comment by zeromus** [comment]
We're going to need more data than that to call this a bug. Games may load any weird files by accident and do nothing with them. Need multiple games, multiple files, and false negatives besides false positives.

**Comment by mariomadproductions** [comment]
- I've indented all/most of the incorrect files in New Super Mario Bros. (USA) - I stopped after entering World 1-1: https://pastebin.com/h1PWTUfR It seems to be listing nearby files...
- Kirby Mass Attack (USA) loads `\data\data\zombippon\zombippon.dat `, but if you corrupt the file it doesn't load it for some reason.

**Comment by zeromus** [comment]
The game may load 512 bytes at a time, regardless of where the files are located in the rom. For instance, sound_data.sdat begins in the 512 byte sector whose beginning is contained within wire_settings8.nsbtx. There's almost certainly no bug here, and if you think otherwise it will take deeper analysis.

**Comment by mariomadproductions** [comment]
That would make sense for NSMB, thanks for the explanation. But I wonder what the situation with Kirby Mass Attack is. It doesn't seem to load any other weird files.

**Comment by zeromus** [comment]
same song, different verse, I'm sure.
