### ISSUE TITLE
[Feature request] Record WAV with separate channels OR consistent channel mixing

### ISSUE THREAD

**Issue by YobaHere** [TASVideos/desmume#134]
That way output will be written in WAV from each channel into 16 separate WAV files, since audio is so inconsistent in terms of mixing.
OR
Maybe make consistent channel mixing. I'm sure this will be harder, but will make it a lot easier to analyze music and sound. If a sample was played on one channel and same sample will be played it should play at this same channel.

**Comment by zeromus** [comment]
You should be using a 2sf player for this. there are rudimentary capabilities along these lines in vio2sf. Your 2nd paragraph is not likely ever to happen though. it would require a high level replayer. which some people probably know how to do, but it's not at all appropriate for desmume.
