### ISSUE TITLE
Rune Factory 1 and 2 - Audio issues

### ISSUE THREAD

**Issue by CynthiaQuinn** [TASVideos/desmume#137]
the audio issues are the same in both games, so i shall detail them using RF1 as an example.

Opening song before start screen: infrequent but noticeable repeating or as i call it "the broken record player effect"

During in-game conversation whenever a character uses voice it is really choppy and slow for example they say "hi there" but it comes out as "h-h-hi t-t-t-th-th-er-e-e-e-e" 

if you need anymore info let me know.

**Comment by zeromus** [comment]
Having trouble with sound? Try literally the 1st sound setting "Synchronization Mode"

**Comment by CynthiaQuinn** [comment]
I've went through all the sound settings already. Nothing fixes it

**Comment by zeromus** [comment]
Then improve your system performance or see the speedup tips at http://wiki.desmume.org/index.php?title=Faq#DeSmuME_runs_too_slow.21
