### ISSUE TITLE
SMLAL(B|T)(B|T) instructions not handled properly

### ISSUE THREAD

**Issue by josh65536** [TASVideos/desmume#139]
There's a glitch with signed multiple and accumulate long halfword instructions.
To reproduce, set
```
r0 = 0x00000800
r1 = 0x00000000
r2 = 0x00001000
r3 = 0x00000000
```
and execute the instruction:
`smlalbb r0, r1, r2, r3`
The resulting 64-bit integer in `r0:r1` is `0x0000080000000800` instead of `0x0000000000000800`.
The relevant line, which sets the high 32 bits of this 64-bit integer is:
`cpu->R[REG_POS(i,16)] += (res + ((tmp<0)*0xFFFFFFFF));`
but `res` is already set to the sum of the _low_ bits. Instead, the line should be:
`cpu->R[REG_POS(i,16)] += ((tmp<0)*0xFFFFFFFF) + (res < (u64)tmp);`
As a necessary bonus, this also takes care of the carry bit.

**Comment by zeromus** [comment]
Can we rewrite this to be less obtuse? Something like:
```
//untested
s32 a = LWORD(cpu->R[REG_POS(i,0));
s32 b = LWORD(cpu->R[REG_POS(i,8));
s64 product = (s64)(a*b);
s64 dst64 = (s64)(cpu->R[REG_POS(i,12)] + (cpu->R[REG_POS(i,16)]<<32));
s64 sum = dst64 + product;
cpu->R[REG_POS(i,12)] = (u32)(sum & 0xFFFFFFFF);
cpu->R[REG_POS(i,16)] = (u32)((sum>>32) & 0xFFFFFFFF);
```

I dont want to risk another bug being here for another 10 years because of such cryptic logic. And after looking at it for a few minutes, I think the performance will be similar.

**Comment by josh65536** [comment]
Don't forget to convert the high bits to a 64-bit integer before left shifting it 32 bits.

**Comment by zeromus** [comment]
ok.. edited... i guess... I'll try it soon.. if nobody else does.
I assume you found this in your own romhack and not in a real game? I like to know if it's fixed a real game.

**Comment by josh65536** [comment]
Yeah, I found it in my game.

**Comment by zeromus** [comment]
@josh65536 , please check it
