### ISSUE TITLE
Can desmume recognize when a video is playing on a screen?

### ISSUE THREAD

**Issue by i30817** [TASVideos/desmume#143]
And if so, can there be a option to temporarily force a screen configuration? For example, if two videos on the two screens are playing, force the '2 screens vertical' configuration and restore the previous on end of videos playing. If one video is playing, show that screen until the end of the video (or a second video starts).

I understand that this isn't likely to be possible because the emulation might not have the HLE hooks to recognize games using video, much less the screen it ends up on, but i thought it worth asking as a usability feature since emulators like ppsspp hook various functions in dlls of individual games (often memsets) and the same technique could work for this.

Personally, i think it would make the 1 screen with toggle feature much better, but it would be good for all modes if it worked well.

**Comment by zeromus** [comment]
nope, sorry. The only way this will ever be pleasant for you is if theres hotkeys to quickly change layouts between a couple appropriate to the game.
