### ISSUE TITLE
32bit builds are giving ~30% less performance in Software Rasterizer with Dynamic Recompiler(12)

### ISSUE THREAD

**Issue by Jules-A** [TASVideos/desmume#149]
I first noticed this when testing the latest autobuild (SuuperW's changes looked interesting) but it's exactly the same with the 32bit Nightly. Honestly I don't care for 32bit builds but it's currently the only way to test the latest changes without having to set everything up and do it myself (which I'm sure many people including myself don't want to do). 

If you're wondering why I'm using Software rasterizer it's' because I'm currently using a HD5750 with my FX8320 so it gives similar FPS with OGL but with added input lagg. Testing was done in Pokemon Heart Gold.
[desmume.ini.txt](https://github.com/TASVideos/desmume/files/2146906/desmume.ini.txt)
32bit
![32bit](https://user-images.githubusercontent.com/1760158/42059738-025df0de-7b57-11e8-8eed-25a917f9ab3b.JPG)
64bit
![64bit](https://user-images.githubusercontent.com/1760158/42059739-029f354e-7b57-11e8-8fd1-c20c4479fe8f.JPG)

**Comment by zeromus** [comment]
and? it would be rather unlikely if different compilers/target ISA yielded the same performance. 

feel free to continue posting to this bug if there's a specific revision which dropped the x86 performance

**Comment by Jules-A** [comment]
I've tested early 2017 builds and the same issue happens, I could test on different machines and try locate a specific revision it doesn't seem like you'd fix it anyways. Honestly I was just hoping for an update of Nightly 64bit build.

**Comment by zeromus** [comment]
don't bother, I'm sure it's always been this way. There's probably not anything to "fix".

The buildbot now has x64 builds

**Comment by Jules-A** [comment]
Well 30% seemed like a pretty big disparity, even for an FX8320 which for some reason gains from 64bit builds in quite a few programs that aren't limited by memory. But I agree it's not worth the time to fix for an outdated processor on 32bit which is being phased out. Thanks for the build.

**Comment by zeromus** [comment]
30% is a big disparity entirely attributable to the idiosyncrasies of the algorithms, compilers, and ISAs involved--not a bug.
