### ISSUE TITLE
Replace DirectInput with XInput

### ISSUE THREAD

**Issue by wildgoosespeeder** [TASVideos/desmume#15]
Something I noticed with using an Xbox 360 controller and that is both the LT and RT can cancel each other out. This makes mapping those triggers to the L and R buttons on a DS a pain during game play. This is a symptom of using the DirectInput API for Xbox 360 controllers. XInput API doesn't have this issue. I was wondering if this was being considered at all during development of DeSmuME?

**Comment by zeromus** [comment]
Nobody was ever interested in doing that work. A patch which replaces directinput with xinput won't be accepted. A patch which adds support for xinput might.

**Comment by wildgoosespeeder** [comment]
OK then, consider adding support in the future.
