### ISSUE TITLE
Screen size ratio continually increases window size on every start-up

### ISSUE THREAD

**Issue by cascardian** [TASVideos/desmume#160]
The increase seems to correspond to the ratio chosen. Locking the size by making the .ini read-only doesn't really work, as it only sets the window size values as the permanent base for the multiplier.

Windows 10 RS4.

**Comment by retr0s4ge** [comment]
@cascardian Thanks for pointing this out.

The exact bug is that the startup window size doesn't match that from the ini file if the following conditions are met:
1- The window was resized by border dragging
2- Aspect ratio is set to be maintained
3- Screen size ratio is > 1

I will fix that promptly.

**Comment by retr0s4ge** [comment]
@cascardian Please recheck and confirm that this issue is resolved.

**Comment by zeromus** [comment]
(supposedly fixed in d869e6cb10b28d89a8ec5a7e8a08d9d559559dbc)

**Comment by cascardian** [comment]
I can confirm that this issue is fixed. Thank you!
