### ISSUE TITLE
Waiting for the display thread to draw each frame while vsync is ON slows emulation down if monitor refresh rate is lower than 60

### ISSUE THREAD

**Issue by retr0s4ge** [TASVideos/desmume#164]
Waiting for the display thread to draw every frame (currently activated only if frameskip is 0) while vsync is ON slows the emulation down if the monitor's refresh rate is lower than 60.
ex. Internal fps is capped at 48 if the monitor has 48Hz refresh rate

Each of these options work correctly if the other is not activated.

vsync option alone allows internal fps to change freely depending on emulation and 3D settings (not capped at monitor refresh rate), yet the final display rate is synchronized with the monitor and no screen tearing is visible.

Setting frame skip to zero alone activates the wait for display thread to draw each frame, which works as intended, and the fps is not capped at monitor refresh rate.

@SuuperW

**Comment by SuuperW** [comment]
It sounds like it is working as intended.
If the user requests both vsync and zero frame skipping, he will expect the output video to be synchronized with the monitor and every video frame to be visible. This is what happens, according to your description.

You cannot logically run at a higher fps than your display's fps with zero frame skipping on that display.

**Comment by zeromus** [comment]
It's logical. you could argue that frameskipping is designed to help reach target speed (60fps) NOT reach the vsync'd rate. In that case it should have no effect when the monitor is running at 48hz. I'm sympathetic to a user who wants to get what amounts to a good triple buffered solution for 60fps game running without tearing at 48hz. That said, I think you're all nuts for spending any time on this junky old frontend and every time you do change one thing it will become increasingly implausible that youve done it without breaking something else or ever fix anything else again.

**Comment by Jules-A** [comment]
While this may be working as intended, turbo while under 60 is severely affected. Turbo at 40 fps makes fps go to around 50 but looks like it's skipping most frames. Before the initial changes by SuuperW, turbo at 45fps (even with newer builds being 64bit, they are 15% slower than the old Nighly's but better than 30% diff between 32bit builds) would bring fps to 105. Basically with the changes, turbo is unusable if your FPS is just above 60fps or lower. If I lower the GPU factor to 3 (what I normally play at) which gets me to 66fps (uncapped) on the old Nightly turbos to 125fps while the newer builds are normal 61fps and turbos to 83 fps but again looks like it's skipping too many frames.

I know this is really a separate issue, I was planning to write a detailed issue but haven't had the time. I thought this might be helpful as it's still related.

**Comment by zeromus** [comment]
If old nightly got to 66fps and new nightly gets to 61fps, then you need to bisect to find the offending commit

**Comment by zeromus** [comment]
my nightly builds are using vc2015, that is, version 1900. I dont know what 1910 builds youre using, or anything about them.

**Comment by Jules-A** [comment]
I'm using the Nightly x64 builds from https://desmume.org/download/ 
[Screenshot](https://user-images.githubusercontent.com/1760158/43277111-968066aa-9139-11e8-9868-e5d8d19ed817.JPG)
Appveyor x86 build (x64 wasn't available then) [318](https://ci.appveyor.com/project/zeromus/desmume/build/0.0.0.318) dropped fps from 57 to 56 and [321](https://ci.appveyor.com/project/zeromus/desmume/build/0.0.0.321) from 56 to 52. 
These changes look like a drop in fps is to be expected but 321 causes a rather large drop despite never using any magnification filters.

**Comment by Jules-A** [comment]
Oh wow, I didn't expect that testing [313](https://ci.appveyor.com/project/zeromus/desmume/build/0.0.0.313) it indeed drops fps by 2.5fps. That means "Forcibly wait for the display thread to draw each frame" from 321 didn't really drop fps much at all, at least not enough to worry about.

**Comment by retr0s4ge** [comment]
Sorry, I was very busy for the past 2 days.

@zeromus @SuuperW Triple buffering solves this open issue, as evident in windowed mode working at 60fps with no tearing at all on windows 10 regardless of monitor refresh rate (Desmume vsync option has to be off).
This happens thanks to windows 10 DWM's forced triple buffering and forced vsync (they began forcing triple buffering starting from windows 8.1?). It is not applied in full screen though (once WS_CAPTION style is no longer set) and tearing is very visible then.
If I manage to solve this neatly, I will submit a pull request for your review.

Regarding WiFi emulation, I can make it so WiFi is disabled by default and add a check box in the WiFi settings to enable it. I will submit a pull request for that.

@Jules-A Thanks for thoroughly testing each and every build and pinpointing the issue.
