### ISSUE TITLE
Turbo is broken below 70fps with Display Method=DirectDraw (HW&SW)

### ISSUE THREAD

**Issue by Jules-A** [TASVideos/desmume#165]
Currently using DirectDraw HW at 40fps and activating turbo increases fps to 50 but makes things extremely choppy and unplayable. This continues up until around 70fps where things will start to turbo fine. Setting the Display Method to OGL however at 40fps increases fps to 80 (base 62 goes to 105) and doesn't appear to be dropping many frames.
Nightly build 2018/04/18 – git#9c12846 goes from 48fps to 110 when using turbo on DirectDraw HW.
Regressed by https://github.com/TASVideos/desmume/pull/148 .
I originally posted in https://github.com/TASVideos/desmume/issues/164 but I think it's best I create a separate issue to avoid unrelated comments in that issue.

Using FX8320, HD5750
[desmume.ini.txt](https://github.com/TASVideos/desmume/files/2233095/desmume.ini.txt)

**Comment by LogPod** [comment]
Turning vsync on and off somewhat fixes this issue

**Comment by Jules-A** [comment]
@LogPod It seems to make it less choppy but only slightly and FPS is still the same.

**Comment by Jules-A** [comment]
Fixed by  #176
