### ISSUE TITLE
Wi-Fi Emulation

### ISSUE THREAD

**Issue by fancymelonub** [TASVideos/desmume#170]
Are you guys bringing back the Wi-Fi stuff? And if you are, then what improvements have the Wi-Fi emulation thing got since the Desmume Wi-Fi builds.

**Comment by fancymelonub** [comment]
This wasn't purpose to be a real issue anyways so closing it is fine, wish was there a Discord server for DeSmuME.
But seriously, did the Wi-Fi emulation improve in any way?

**Comment by zeromus** [comment]
I'm glad my action meets with your approval.
You wouldnt be asking this if we hadn't already brought back wi-fi stuff. 
All the discussion is here or linked to from here: http://forums.desmume.org/viewtopic.php?pid=27161
We use IRC, not discord: http://wiki.desmume.org/index.php?title=Faq#Where.2Fwhat_is_IRC.3F

**Comment by fancymelonub** [comment]
Thanks!

**Comment by fancymelonub** [comment]
Hey, I have a weird problem. The validation and password reset emails didn't get sent to me. Did I make a typo in the email boxes? If you wanna know what username I registered with in the fourms, it's Wiferni.

**Comment by zeromus** [comment]
I see your email address doesn't look like a typo, but it does look like an email address you might enter because you don't want to give your real email address.

**Comment by fancymelonub** [comment]
That's my actual main email, I know right.
I'm not sure if I should put it here or in some kind of DMs, though. Just to make sure there's no typos.

**Comment by zeromus** [comment]
Wait 24 hours and check your spam.

**Comment by fancymelonub** [comment]
Ok, I got the password reset email but not the validation one.

**Comment by fancymelonub** [comment]
Oh yea, also. On the latest build. what does "Compatibility mode" do?

**Comment by zeromus** [comment]
https://github.com/TASVideos/desmume/pull/166
