### ISSUE TITLE
Request: Cheat List window improvements.

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/desmume#178]
Hey guys.

Would it be possible to modify the cheat list window a bit with the following improvements?

**PENDING:**

-Ability to highlight multiple cheats to delete them, instead of deleting them one by one. 
When creating my own cheats, I usually have to add 10 or 20 addresses for testing, but deleting the bad ones afterwards is tedious since I can only delete one by one, and can't even use the keyboard for it.

-Ability to move cheats to the top or bottom. 
When a cheat list is too big, and you add a new cheat or if I'm making my own cheats, the new codes will always appear in the bottom. Which means that if I'm constantly modifying the value, or enabling/disabling the cheat, I have to scroll all the way to the bottom. It would be nice if I could just move those cheats to the top to avoid scrolling every time.

**ALREADY IMPLEMENTED:**

-Ability to enable / disable all available cheats.
A welcomed feature would be the option of clicking on a box or something to check-mark all available cheats (and uncheck them too). This is specially needed when opening the Cheats Database, since you have to click each cheat one by one to add it to the emulator.

**Comment by ReyVGM** [comment]
Also, the cheat descriptions get cut off by the useless thing:

![new bitmap image](https://user-images.githubusercontent.com/7338867/44323576-86aa0c00-a420-11e8-9231-ee1c91907f87.PNG)

**Comment by zeromus** [comment]
So is this fixed or what

**Comment by zeromus** [comment]
let's say its fixed unless someone tells me otherwise
