### ISSUE TITLE
Viewtiful Joe Double Trouble - Black textures during cutscenes.

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/desmume#179]
With DeSmuME_0.9.11_x64, the cutscenes in the game play fine, with some minor texture glitches on the characters.
But with the latest interim builds (DeSmuME_git#6fa6467c_x64 so far), all the character textures are black during cutscenes. Happens with softraster and opengl.

**Comment by rogerman** [comment]
I can confirm the bug.

It appears as if changes to power register handling has caused a regression in commit 759a039.
