### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by zminhquanz** [TASVideos/desmume#18]
Please make an android port official , on Android have Drastic but you have to paid , and the other it's port unofficial from Desmume and it's have a poor perfomance

**Comment by zeromus** [comment]
We dont need a bug for this. It's an obvious choice for anyone who wants to tackle it.

**Comment by trymeouteh** [comment]
I would love to see a stable and supported Android port of DeSmuME. As long it is stable, available on F-Droid and will be updated now and then to ensure it will work on newer versions of Android I would be happy.

There is no good DS emulator out there that is outside of the Google Play Store. Drastic is a great DS Emulator but it can only be obtained in the Goolag Play Store.
