### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by spyro888** [TASVideos/desmume#182]
For nds emulator on retrix I cant find firmware.bin need it to run emulator ... Can you help me please

**Comment by zeromus** [comment]
you don't need firmware.bin to run emulator. moreover, if we could have provided that file, we would have, and you would already have it.

**Comment by spyro888** [comment]
So how I can run nds emu ?
I put bios arm9 and bios arm7 but only firmware.bin I couldnt find it and emu cant run every trying !!!
How run it if I dont need firmware ?
