### ISSUE TITLE
Suggestion: Forcibly trigger anti-piracy

### ISSUE THREAD

**Issue by mariomadproductions** [TASVideos/desmume#183]
I'd like to document some game anti-piracy features for [The Cutting Room Floor](https://tcrf.net/The_Cutting_Room_Floor), so it would be useful if there was a feature that causes the sort of things that DS anti-piracy code looks out for to be badly emulated on purpose.

**Comment by zeromus** [comment]
try removing line 66-67 of slot1comp_rom.cpp and see if you can get them to trigger

**Comment by mariomadproductions** [comment]
Thanks, I'll try that.

**Comment by zeromus** [comment]
install tortoisegit

**Comment by zeromus** [comment]
(FYI, git no longer needs to be installed to build desmume)

**Comment by zeromus** [comment]
waiting for @mariomadproductions to confirm whether this hack triggers the AP

**Comment by zeromus** [comment]
I don't think I want to add an option for this.. I glanced around and can't see a place I'm happy adding it. Since the code is easy to hack, maybe we can leave it that way. If you insist, I can add a command line parameter, since there isn't any need to change it at run-time.

**Comment by mariomadproductions** [comment]
I would appreciate it if you could add a command line parameter for this.
