### ISSUE TITLE
Pokemon Ranger - Shadows of Almia Graphic Glitches

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/desmume#189]
I'm using the latest build, and also 0.9.11. I've used both renderers, turned on/off bios, bus level timing, dynamic recompiler, and the sort.

Issue is that the game is sprinkled with these glitchy lines all over the place:

![pokemon ranger - shadows of almia u venom _23_05_25_28856](https://user-images.githubusercontent.com/7338867/45196435-37d6e180-b22a-11e8-9971-1fa1a624ee77.png)

When you walk up or down, some disappear, and others appear. When moving from left to right, they do not change.

**Comment by zeromus** [comment]
numerical precision issues. will get magically fixed one day. try using TXT hack

**Comment by linklight2** [comment]
Txt hack does not fix
