### ISSUE TITLE
Linux (Ubuntu 18.04) wifi.h:2268:14: error: two or more data types in declaration 

### ISSUE THREAD

**Issue by noabody** [TASVideos/desmume#191]
You folks must be sick to death of "can't build on *this or that Linux variant*" issues and I apologize for that.  Your project has always had a focus on Windows users.  That said:
```shell
In file included from ../../commandline.cpp:24:
../../movie.h:31:10: fatal error: replay.h: No such file or directory
 #include "replay.h"
          ^~~~~~~~~~
```
I guess this file isn't in ```desmume/src/frontend/posix``` so I sym-linked the Windows one:
```shell
(cd desmume/src && ln -sf frontend/windows/replay.* .)
```
I'm at a complete loss on this one:
```shell
In file included from ../../NDSSystem.h:27,
                 from ../../OGLRender.cpp:29:
../../wifi.h:2268:14: error: two or more data types in declaration of ‘type name’
   u16 Status:4;
              ^
Makefile:1648: recipe for target '../../OGLRender.o' failed
```
Line 2268 in ```desmume/src/wifi.h``` is a typedef union struct for value "Status" (google says its for handling lots of slightly different data types).

Not sure why doing:
```shell
(cd desmume/src/frontend/posix && ./autogen.sh)
(cd desmume/src/frontend/posix && ./configure)
make -C desmume/src/frontend/posix -j4
```
Is even trying to build the wifi module as I don't believe it's default.  Maybe we need a call for help to have a Linux and OSX savvy tech keep track of their stand-alone gui versions.   Seems like libretro and android have someone.

**Comment by zeromus** [comment]
including wifi.h does not mean the wifi module is getting built.
nobody will answer your call.
