### ISSUE TITLE
If you have a specific character, you can not open the file. (bug)

### ISSUE THREAD

**Issue by schbella** [TASVideos/desmume#192]
If ポ is (One of Japanese Katakana) in the file name
I can not open the file. It has no response.

Example
(1)
File name: ポケットモンスター パール.nds
In this case, I can not open the file.

(2)
Except for ポ
File name: ケットモンスター パール.nds
In this case, I can open the file successfully.
And other Japanese characters except ポ were not problematic.

I use DeSmuME 0.9.11
This is a bug.
Please fix it.

**Comment by zeromus** [comment]
desmume 0.9.11 is not supported
