### ISSUE TITLE
Desmume version 9.11 and 9.10 crashing entire computer.

### ISSUE THREAD

**Issue by cosmoandwinnie** [TASVideos/desmume#195]
What it says on the tin. Within five minutes of using Desmume, my computer screen will go black with no warning, and I'll need to turn the entire system back on as if I had shut it off completely. 
Is anyone else experiencing this issue?
I could find no recent topics on this issue, and I'll try using older versions of Desmume until Desmume gets a new update or a fix to this.

**Comment by johnny-mac** [comment]
Have you tried desmume-reloaded? It may have to be compiled from source-code, not really sure but maybe you'll get different results.

**Comment by rogerman** [comment]
@cosmoandwinnie, if your computer is suddenly shutting down under any circumstances, then this is certainly a deeper issue with your computer's OS, firmware, or hardware -- most likely hardware. Maybe your computer is overheating? In any case, this is definitely not a problem with DeSmuME. However, you can also try one of our nightly builds on our official Downloads page at desmume.org/download/.

@johnny-mac: desmume-reloaded will not provide any different results. All it does is kinda-sorta restore WiFi functionality from the v0.9.7 code base and also does some very minor changes to other random stuff -- nothing related to the user's issue at hand.

**Comment by cosmoandwinnie** [comment]
@rogerman I was hoping that wasn’t the case. I’ve been on the phone with support two days in a row now, soon to be three, and we’re just not finding anything, and desmume was the only thing that made it crash. The computer is less than a year old.

**Comment by zeromus** [comment]
run memtest86 or prime95 on it to try proving another program does it so you can get your money back. also try not using desmume's opengl renderer, and try upgrading/downgrading your gpu drivers.

**Comment by rogerman** [comment]
No response from the OP for over a month, and it seems like this issue is a problem on the user's end rather than with DeSmuME, so I'm closing out this one.
