### ISSUE TITLE
Add Lua function to read all controller buttons

### ISSUE THREAD

**Issue by QueeferSutherland** [TASVideos/desmume#198]
I would like a Lua function (controller.get) that gets the state of all controller buttons similar to how input.get() gets the state of all keyboard keys.

I use a DualShock 2 for controlling games in Desmume and half of the controller buttons are unused. I'd like to use a Lua script to detect input from an unused button (ex. L3) and perform an action, like click a specific spot on the touch screen.

joypad.get() only detects controls bound in Control Config.
input.get() detects all keyboard and mouse input.

There is no function I can find to read controller input. My current workaround is to use input.get() to detect a specific keyboard key and use antimicro to bind that key to a specific controller button.

Implementing this request will require the use of the joyGetPosEx() function found in winmm.dll.

**Comment by QueeferSutherland** [comment]
I have just finished implementing this myself, so I guess the request can be withdrawn.

![showInput](https://i.postimg.cc/x1gnd27g/show_Input.png)

**Comment by zeromus** [comment]
finished implementing yourself solely through lua, or by modifying lua-engine.cpp?

**Comment by QueeferSutherland** [comment]
I modified lua-engine.cpp in the desmume-release_0_9_11 branch and recompiled with no warning/errors.

**Comment by zeromus** [comment]
can you share it by pasting the file or making a PR vs that branch? I don't see why it couldn't be merged into master

**Comment by QueeferSutherland** [comment]
Here is my lua-engine.cpp.

https://pastebin.com/jAqgHQ8y

**Comment by windwakr** [comment]
Support for the joystick axes would be great. I've implemented it myself, but it's not pretty.
https://github.com/windwakr/desmume/commit/d9c5536e2b821c45e452ab6e02ac8ed272ca7236

**Comment by QueeferSutherland** [comment]
I left out the axes because I couldn't think of any way they would be useful. Today I found a way to use them and realized axes support would be amazing.

The problem with your scaling is that it returns *-1.5* when my analog stick is centered. The simplest solution I can come up with is to subtract 1 from the axis' maximum position.

For example, this is the code for the X axis. It will return 0 at center, -1 at full left tilt, and 1.00003 at full right tilt.
    double scaledxpos = (joyinfoex.dwXpos - joycaps.wXmin) * 2.0 / (joycaps.wXmax - joycaps.wXmin - 1) - 1.0;

Also, testing for the axes' existence isn't really necessary because an axis that doesn't exist will always return a position of 0 (-1 when scaled). If you are going to test for axes then you should also test for the X & Y axes too (by using joycaps.wNumAxes) because someone using a USB SNES Controller won't have any axes at all. Personally, I'd return all the axes' values and let the user decide which ones to use.

Here is my new lua-engine.cpp for the desmume-release_0_9_11 branch that adds support for joystick axes.
https://pastebin.com/M2sjEB8D

**Comment by QueeferSutherland** [comment]
I left out the axes because I couldn't think of any way they would be useful. Today I found a way to use them and realized axes support would be amazing.

The problem with your scaling is that it returns *-1.5* when my analog stick is centered. The simplest solution I can come up with is to subtract 1 from the axis' maximum position.

For example, this is the code for the X axis. It will return 0 at center, -1 at full left tilt, and 1.00003 at full right tilt.
`double scaledxpos = (joyinfoex.dwXpos - joycaps.wXmin) * 2.0 / (joycaps.wXmax - joycaps.wXmin - 1) - 1.0;`

Also, testing for the axes' existence isn't really necessary because an axis that doesn't exist will always return a position of 0 (-1 when scaled). If you are going to test for axes then you should also test for the X & Y axes too (by using joycaps.wNumAxes) because someone using a USB SNES Controller won't have any axes at all. Personally, I'd return all the axes' values and let the user decide which ones to use.

Here is my new lua-engine.cpp for the desmume-release_0_9_11 branch that adds support for joystick axes.
https://pastebin.com/M2sjEB8D

**Comment by zeromus** [comment]
you need to clamp it to [-1,1]

**Comment by windwakr** [comment]
@QueeferSutherland, are you sure it wasn't something like -1.5e-05? That means 0.000015, which is effectively zero. Also, I did update the code to check for the X and Y axes. I forced it over that old commit so I don't know why the link still works.

https://github.com/windwakr/desmume/commit/4fa314da2329a2fe1060519ad147ad5d1c206d18

**Comment by QueeferSutherland** [comment]
@windwakr You are correct, the code is fine. My display method was truncating the value to -1.525 when it was returning -1.5e-05.

My controller has no U/V axes, but they both return a min/max of 0/65535. I agree that they should be checked anyway as it's best to err on the side of caution and make no assumptions.

I've compiled this and it's working great.
https://pastebin.com/wMwHV42i

![axes](https://i.postimg.cc/qMtgcMsw/axes.png)
Note: The +/-0 is an intentional result of the string.format used in my lua script to align the values for display. The non-formatted return values have 15 decimal places.

**Comment by zeromus** [comment]
let me know when you guys are done by putting it in a PR vs master

**Comment by windwakr** [comment]
>Personally, I'd return all the axes' values

Yeah, that's a good idea. That way scripts won't just error out if they try to access an axis that doesn't exist. Just have it return 0.0 for ones that don't exist. Something like
```C++
scaledpos = 0.0;
if (joycaps.wNumAxes > 0)
        scaledpos = SCALEAXIS(joyinfoex.dwXpos, joycaps.wXmin, joycaps.wXmax, -1.0, 1.0);
lua_pushnumber(L, scaledpos);
lua_setfield(L, -2, "x");
scaledpos = 0.0;
if (joycaps.wNumAxes > 1) 
    scaledpos = SCALEAXIS(joyinfoex.dwYpos, joycaps.wYmin, joycaps.wYmax, -1.0, 1.0);
lua_pushnumber(L, scaledpos);
lua_setfield(L, -2, "y");
```
Or something like that, idk.
