### ISSUE TITLE
Soul Silver crashes Desmume when loading state 

### ISSUE THREAD

**Issue by Moltresrider** [TASVideos/desmume#199]
If I load a state for Pokémon Soul Silver that is more than a day old, Desmume always crashes with "_Desmume git#e6b3dfd has stopped working_" It will crash every time I try to load this state. The in game save works, but sometimes while it said it saved, when I load my game, it loads a few saves ago and not the most recent.

Savestates less than 24 hours old are unaffected by this problem

Edit: I just had a crash from a 20 minute old savestate so apparently it is not with older than 24 hours savestates.

I am not sure what is causing this because I test the savestate right after I create it, but it will always crash Desmume later

**Comment by zeromus** [comment]
Your hard disk is going bad or your security software is run amuck. Backup all your files now while you still can.

**Comment by zeromus** [comment]
i would believe you if you hadnt also said your in-game saves are teleporting through time also. desmume can't do that. maybe your little brother is playing a trick on you. but its more likely your backup software. or youre running it out of dropbox on two computers with two versions of desmume and theyre getting mixed up or not messing up during synchronizing

**Comment by Jules-A** [comment]
Are you sure ingame saving is not working properly that sounds like it could be an Antivirus keeping Desmume from writing to the file. If you were mistaken about the ingame saves, there has been quite a few changes to save states that might be causing the issue. If you don't mind trying a highly experimental build could you see if [this build](https://ci.appveyor.com/project/zeromus/desmume/build/0.0.0.399/job/uquyr5va848ovk0i/artifacts) fixes it?

**Comment by zeromus** [comment]
tired of seeing this
