### ISSUE TITLE
OpenGL renderer crashes when using single core and 3x internal resolution.

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#20]
OpenGL render is broken when using single core and internal resolution higher than 1x, tested with latest test x64 build on windows 8.1. 

my settings:
![2x-settings](https://cloud.githubusercontent.com/assets/8726272/21429424/a0229490-c899-11e6-8d87-365084adff1d.jpg)

2x internal resolution:
![2x](https://cloud.githubusercontent.com/assets/8726272/21429435/aa938e0c-c899-11e6-82f9-f435073a601c.jpg)
 
3x internal resolution:
**emulator will crash immediately**

Step to reproduce:
(1) download test build git#7b13501 from official web site.
(2) run emulator and change render to opengl 3.2, HD prescale to 2 or 3
(3) close emulator
(4) run emulator with command line parameter "--num-cores 1" to force using single core.
(5) 2x internal resolution will cause graphic glitch as picture above.
(6) 3x internal resolution will crash immediately.

**Comment by zeromus** [comment]
FYI for some time I've felt there is some tiny corruption in the high resolution rendering (maybe/likely only on windows) and so this may just be smoking it out more easily.

**Comment by zeromus** [comment]
unfortunately not related to my intermittent corruption
