### ISSUE TITLE
LINUX - Segfault when trying to switch to OpenGL

### ISSUE THREAD

**Issue by blacksparrow123** [TASVideos/desmume#202]
I'm on manjaro.
Desmume installed via AUR.

**Comment by zeromus** [comment]
let's play a guessing game. I'm thinking of the thing everyone asks for when all you say is "I got a segfault". Can you guess what I'm thinking?
otherwise--sounds like a question for the maintainer of the desmume package, which isn't us.

**Comment by blacksparrow123** [comment]
Yeah. Not very informative.
Does desmume have some sort of logs or something?

I'll try to contact them if they are still around.

**Comment by zeromus** [comment]
oh, supposedly this was fixed in may. good enough for me
