### ISSUE TITLE
Allow communication between emulator on Wii and real DS

### ISSUE THREAD

**Issue by friedkeenan** [TASVideos/desmume#204]
The Wii was/is able to do DS Download Play stuff with DS'es, and when I was scrounging around I found [this](https://wiibrew.org/wiki//dev/net/wd/command). I know the protocol that the DS uses is colloguially called Nifi (Nintendo wifi) and that it's a slightly modded protocol from what's standard, but I can find little to no information about it, besides a bunch of people saying no one really understands/has used it in any way.

It's probably not super useful, but I can think of one use: Unlocking the DLC in Dragon Quest IX. In Dragon Quest IX, you were supposed to go online to unlock all the post-game quests, or you could connect to a DS that had the DLC unlocked. It's fairly simple to unlock the DLC if you have access to the save file, so you could theoretically edit the save file for the emulator to unlock the DLC, and then use the Wii's Nifi functionality to connect to a real DS who doesn't have the DLC unlocked, which will then cause the DS to edit the save file and unlock the DLC.

I *might* try working on this if I can figure out more about Nifi, and if I can become more experienced with how emulators work, but I'm also not super experienced with C, so I'm probably not the best person for the job.

**Comment by zeromus** [comment]
in other words, improve the wifi emulation. got it.

**Comment by HatsuneMiku001-vocaloid** [comment]
I just saw this post because I am trying to find a way to connect my New 2DS XL into a Wii emulator so I can play Pokémon: Battle Revolution but I have had no luck, just people saying "you need DeSmuME to play Battle Revolution" which I don't feel like doing, have you had any process with it @friedkeenan?
