### ISSUE TITLE
Daigassou! Band-Brothers DX (Japan) fails to load error

### ISSUE THREAD

**Issue by benderscruffy** [TASVideos/desmume#213]
fails to load 
![band](https://user-images.githubusercontent.com/2696404/47613013-7322bd80-dac1-11e8-918b-0551930f814a.PNG)

**Comment by rogerman** [comment]
This one works for me.
![bandbros_also_works](https://user-images.githubusercontent.com/6055122/47613168-e0453d00-da46-11e8-8236-aec09747636d.png)

It is possible that you may have a corrupt .dsv file. Try removing the .dsv file from the Battery folder and see if the game starts.

**Comment by zeromus** [comment]
Use google, find solution on desmume's own bug tracker
https://sourceforge.net/p/desmume/bugs/1325/
use slot-1 nand
