### ISSUE TITLE
Path Settings for "States" Doesn't seem to work properly for Windows

### ISSUE THREAD

**Issue by ImSpecial** [TASVideos/desmume#214]
https://i.imgur.com/2srGRhk.png

Issue is that no matter the custom directory set, output directory is always "StateSlots".

Other path settings seems to adjust properly ie. changing Battery to Saves, Screenshots to Screenshots123, etc.

Guessing this has to do with it. https://github.com/TASVideos/desmume/pull/188/commits/aaad5e63c5ee9917863398c19d3cf6fd7f9dba78

**Comment by zeromus** [comment]
@SuuperW dont we need a new entry in pathconfig if theres a new path to be configured?
