### ISSUE TITLE
arm_jit.cpp: OP_LDRD_REG() and OP_STRD_REG() out-of-bounds array access for cpu->R[]

### ISSUE THREAD

**Issue by rogerman** [TASVideos/desmume#215]
See the macro for #define T(op, proc) at arm_jit.cpp:1924.

One part of this macro is "op<proc,15>", which calls OP_LDRD_REG<PROCNUM, 15>() and OP_STRD_REG<PROCNUM, 15>().

Both of these functions access cpu->R[Rnum+1], where Rnum is 15 in the macro. This causes an out-of-bounds access at cpu->R[16], in which the armcpu_t.R array should only have 16 elements (array range should only be from [0...15]).

**Comment by rogerman** [comment]
Additional notes about what's going on:

The OP_LDRD_REG() and OP_STRD_REG() are functions that are called via function pointer tables op_ldrd_tab and op_strd_tab. These function pointer tables are only accessed via functions OP_LDRD_STRD_POST_INDEX() and OP_LDRD_STRD_OFFSET_PRE_INDEX().

In both functions OP_LDRD_STRD_POST_INDEX() and OP_LDRD_STRD_OFFSET_PRE_INDEX(), there are existing checks to ensure that the register number must be even-numbered before op_ldrd_tab or op_strd_tab are ever accessed.

Therefore, OP_LDRD_REG<PROCNUM, 15>() and OP_STRD_REG<PROCNUM, 15>() will never be called in practice due to 15 being an odd-numbered register. So in reality, all commit c8306de does is silence a compiler warning when attempting to do a double-word load/store on register 15.

But it's fine. This commit helps clarify within the OP_LDRD_REG() and OP_STRD_REG() functions themselves that double-word load/stores should only be performed on even-numbered registers, which is an ARM9 requirement.

**Comment by StapleButter** [comment]
afaik Puppy Palace is working on melonDS, and it doesn't care about LDRD/STRD alignment (something I'd have to fix btw), so I doubt it has to do with this

'd need to test it on hardware first tho. I suspect it just ignores bit0 of the destination register ID, but has to be confirmed.
