### ISSUE TITLE
Nintendo WFC

### ISSUE THREAD

**Issue by Heoz** [TASVideos/desmume#218]
When i make connection on NINTENDO WFC SETTINGS and i reset emulator even if i saved connection it deletes and i tried hamachi but WIFI didnt show it as available can it be fixed and how does adhoc working since it didnt work before

**Comment by Jules-A** [comment]
I have no idea what you are saying... You also didn't mention what OS or build you are using... If English isn't your native language can you try Google Translate?

**Comment by zeromus** [comment]
his firmware settings arent being saved. he is expecting the wifi search in the firmware to find his local networks. In general he's wanting help using wifi in desmume, which he's not going to get.
