### ISSUE TITLE
QT Frontend

### ISSUE THREAD

**Issue by sudopluto** [TASVideos/desmume#22]
I was browsing the wiki and noticed that there was work being done on a cross platform QT GUI. Is that still a thing? Also, if it isn't a thing, could you give me some pointers of where i could start to learn how to do it?

**Comment by zeromus** [comment]
There's no work being done on a cross platform QT gui.  Google knows more about QT than we do. If you come back knowing something about QT, then we can talk about what it would take to make it a desmume frontend. Just make a pretend frontend first with whitenoise video that changes color when you press keys or gamepad buttons and outputs static noise. If you can do that, then you can make a desmume frontend.
