### ISSUE TITLE
Puzzler World 2 (USA) black screens

### ISSUE THREAD

**Issue by benderscruffy** [TASVideos/desmume#221]
after the loading screen nothing but black screens and music playing in the background
happens in both softrasterizer and opengl 3.2

**Comment by zeromus** [comment]
ill assume this guy is committed to being a power tester. he can obviously boot desmume without all black screens judging from prior issues.  but your guidance on how to make useful issues is appreciated.

**Comment by benderscruffy** [comment]
so im not smart as u guys
