### ISSUE TITLE
WinFrontend's "Display Method" remains as DDHW when OGL renderer is used (45% less FPS)

### ISSUE THREAD

**Issue by Jules-A** [TASVideos/desmume#225]
Currently when you change to OpenGL renderer, Direct Draw Hardware "Display method" is still used. On my system in Pokemon HG, there is a 45% performance increase when also switching this setting to OGL. I believe many users are enabling OGL renderer but not changing the display method resulting in them seeing no increase from using OGL. 
It seems like these settings should be moved to the 3D Settings interface and maybe even set to respective setting when renderer is changed but I was wondering if there was a reason why this isn't already the case?

**Comment by Jules-A** [comment]
>  The options shall remain where they are, and remain separate. 

> Put an action button in the 3d settings to set the display method to ogl if you wish.
So you mean double up on settings?

> it has nothing to do with the chosen 3d renderer
Maybe not but the people that are going to be switching to OGL renderer are very likely the same people willing to accept the chance of glitches for the increase in speed but I guess switching automatically is a bad idea.

**Comment by zeromus** [comment]
No, I mean add another way to alter the same setting.

The glitches arent rendering glitches, the glitches are total system malfunctions

**Comment by rogerman** [comment]
The 3D Rendering Settings affect the actual emulated 3D graphics layer of the NDS. When you modify these settings, you are directly affecting what the emulated NDS hardware sees when it tries to render the final video output.

The final video output could really be used for anything by the client -- it could source a screenshot, an AVI-captured video frame, or a displayed video frame in a window. It is up to the client to use the final video output however it wants.

In the Windows port, the Display Method settings control how Windows uses the final video output from the emulator for displaying the video frame in a normal window. But really, there could be all sorts of display methods that can process the final video output and blit it to a normal window based on GDI, SDL, DirectDraw, Direct3D, OpenGL, Vulkan, etc. -- no one cares how the client uses the data. All of this business is purely end-user facing stuff that has nothing to do with the emulation.

Closing, based on the user's misunderstanding that the Display Method settings are completely different and completely unrelated to the 3D Rendering settings.

**Comment by zeromus** [comment]
Well, I think the user understood the difference, just not the significance, basically thinking it was so insignificant that it was baffling there was a user-facing option for it at all when there were such grave performance impliactions

**Comment by Jules-A** [comment]
zeromus is correct but I still feel these settings should be in the graphics setting window once and ONLY once I implement a description box in the graphics window. 
The reasoning is 1.) Currently the program gives no indication of what the setting does, how it's different to changing the 3d renderer and what the consequences are leading to accidental changing. 2.) People that want to change the setting for speed aren't able to easily locate it (generally such a setting would be in graphics settings (along with Vsync). 

Now you could say I could just implement tooltips but implementing tooltips would mean 1.) You are unable to go in detail about a setting 2.) It blocks the viewport 3.) If I implement it in just a few places people might expect it to work in others, with a description window people can guess that the other windows don't have it. 4.) People would expect it on every object (something I don't have time to do).

I did a quick 2min mockup of what it might look like. If you want to see how it would work, check Dolphin. 
![graphics settings mockup](https://user-images.githubusercontent.com/1760158/48976438-b2452e00-f0c2-11e8-864c-c909022013fb.JPG)

I can't really work on it yet though but I was wondering where I should put the strings.

**Comment by zeromus** [comment]
Your single-minded devotion to making sure morons get maximum performance is fascinating. I object to putting chaos workarounds (display methods) in this screen full of deterministic rendering options. I object to even trying to describe what the display methods do. Chaos workarounds can't be described in any way that will make sense to the morons you're advocating for. That they're totally independent of the rendering options is the only true thing you can say about them. About the only thing I can think of that makes sense is the command button called "Use OpenGL Display Method" which is enabled when an opengl renderer is chosen and dispmethod isn't opengl, with a label beneath it saying "It probably makes sense to click this, but zeromus won't let me make it automatic"

Good work on organizing the options dialog though, I just checked it out. It's pretty. I don't mind either hover tips style, but I don't care enough to get involved.

**Comment by Jules-A** [comment]
> Your single-minded devotion to making sure morons get maximum performance is fascinating.

I'm not sure it's really fair to call them morons, considering the current placement of the settings without anything describing what they actually do. Afaik they only get told to enable it under the "Desmume runs too slow" FAQ answer.

> Chaos workarounds can't be described in any way that will make sense to the morons you're advocating for.

But you guys already gave enough information for people to understand. Surely this would be enough for them to understand?:
"Directly affects what the emulated NDS hardware sees when it tries to render the final video output.
Setting the display method to OpenGL greatly improves FPS when also using OpenGL 3D Renderer but can cause issues such as blinking screens, malfunctioning vsync, malfunctioning fans, entirely broken/black/corrupted screens, blurred minimizing/maximizing. Default: DirectDraw HW"

> About the only thing I can think of that makes sense is the command button called "Use OpenGL Display Method"

Actually that sounds like a much better solution, while using OpenGL display method with SoftRast actually increases FPS from 44 to 51, I just can't see many use cases for it.

**Comment by zeromus** [comment]
This depends on your system, man. Sorry, I forgot to list "inexplicable performance surprises" in the list of chaos bugs that the display methods affect. You're overconfident in your testing methodologies. They don't apply to every system. Also, I don't understand the "Directly affects what the emulated NDS hardware sees when it tries to render the final video output" language. That sounds wrong. It's more like "what the emulator uses to present the final video output" and has nothing to do with the emulated NDS hardware. Really this belongs in a frontend features panel which would include things like screen splits and multiple windows and crap like that if it was ever too complex for a menu.

I'm done discussing this.
