### ISSUE TITLE
0.9.12

### ISSUE THREAD

**Issue by ShalokShalom** [TASVideos/desmume#226]
Hi there :)

I just released there is still development going on, while the current release is soon 4 years old. 
Any ideas?

**Comment by zeromus** [comment]
If you want to chat, go to the chat room.
None of the developers care how old the current release is.

**Comment by Jules-A** [comment]
Well, it would be nice if there was another release before Visual Studio 2019 releases because it drops support for XP and it would be nice to be able to use the new features.

**Comment by zeromus** [comment]
And you can't use vs2017 to compile it for XP for the next 15 years, because......?

**Comment by ShalokShalom** [comment]
@zeromus o.o

People look at the current release, often at somewhere different places as Github. 
Some people dont want to compile for them self. 
This is why 99% of all projects do releases. 

Why you not?

**Comment by zeromus** [comment]
Because making releases takes that could be spent improving the code instead

**Comment by ShalokShalom** [comment]
Creating a release costs literally seconds.

**Comment by Jules-A** [comment]
> Creating a release costs literally seconds.

Even if we ignore all the new code that hasn't had time to stabilize, there's 1238 commits since 9.11 release, do you want to volunteer to write the changelog?

**Comment by ShalokShalom** [comment]
I dont need a changelog. Its just for packagers and so on. Just follow the standards.
