### ISSUE TITLE
Slight Sprite Stretching Glitch in Dragon Quest VI

### ISSUE THREAD

**Issue by mike20599** [TASVideos/desmume#227]
I tried v0.9.11 and git#1f9b9e0 but both versions have this minor graphical glitch in Dragon Quest VI. The main character's sprite alternates between looking normal and getting partially stretched. Not sure if this occurs with other sprites, but it's most noticeable on the main character.
![dragon quest vi - realms of revelation usa en fr es __17505](https://user-images.githubusercontent.com/45381878/49062966-acd30b00-f1ca-11e8-8e1e-40cc3b281c22.png)![dragon quest vi - realms of revelation usa en fr es __17501](https://user-images.githubusercontent.com/45381878/49062967-ad6ba180-f1ca-11e8-9ec8-2cb7aa9ba4df.png)

In the left screenshot, the blue haired guy looks normal. In the right screenshot you can see he has been stretched slightly in a vertical slice to the left of his right eye. This alternating occurs every half second or so. Here are some more shots where it's clearer.

![dragon quest vi - realms of revelation usa en fr es __16456](https://user-images.githubusercontent.com/45381878/49063264-ac873f80-f1cb-11e8-91f6-efe7dd8bd547.png)![dragon quest vi - realms of revelation usa en fr es __16463](https://user-images.githubusercontent.com/45381878/49063265-ad1fd600-f1cb-11e8-9909-d9213fb12acf.png)

**Comment by rogerman** [comment]
This is an issue with SoftRasterizer's texture sampling precision. You have 1 of 2 options as a workaround:
1. If you want to continue to use SoftRasterizer as the 3D Rendering Engine, then enable TXT Hack (or Fragment Sampling Hack if you're running DeSmuME on a Mac).
2. Switch the 3D Rendering Engine to OpenGL, which does not have this issue.

**Comment by mike20599** [comment]
Thanks, that fixed the issue!
