### ISSUE TITLE
[Question/Feature Request] hide console?

### ISSUE THREAD

**Issue by Ninjistix** [TASVideos/desmume#230]
is it possible to have a option to hide the console?

![image](https://user-images.githubusercontent.com/12572974/49251532-9ce84080-f3ef-11e8-8a0c-387a8f548cc0.png)

![image](https://user-images.githubusercontent.com/12572974/49251442-5f83b300-f3ef-11e8-8320-e985e676637f.png)

**Comment by zeromus** [comment]
add to desmume.ini
```
[Console]
Show=0
```

**Comment by Ninjistix** [comment]
would it still be possible to add that option, without modifying the .ini ?  and thanks for the quick reply, I had asked about it on Reddit also, came here for faster response 👍

**Comment by zeromus** [comment]
You could have edited the ini 1000 times in the time it's taken you to ask twice. 1000 people could edit the ini 1000 times in the time it would take to add a menu item. 

I guess I could have added the option in the time it me took to write this....
