### ISSUE TITLE
About Crash in DeSmume, please help me!

### ISSUE THREAD

**Issue by lnn2204** [TASVideos/desmume#242]
![untitled](https://user-images.githubusercontent.com/46069059/50374681-ad718c80-0624-11e9-9a41-c9c8e19b87d5.png)
Like this image :D Tks

**Comment by zeromus** [comment]
looks like youre trying to load an old savestate in a new emulator version. not supported.

**Comment by zeromus** [comment]
yes there is, and it's not worth the trouble.
