### ISSUE TITLE
AVX vector store to incorrectly-aligned buffer causing segfault

### ISSUE THREAD

**Issue by filialpails** [TASVideos/desmume#245]
I get an immediate segfault in [`ColorspaceConvertBuffer555To8888Opaque_AVX2`](https://github.com/TASVideos/desmume/blob/f5d90a77c1dfa1aca3e0a546aa93105f28de5cbc/desmume/src/utils/colorspacehandler/colorspacehandler_AVX2.cpp#L323) when running the GTK frontend on Linux. The crash doesn't occur in the CLI or Glade frontends. It also doesn't occur when compiled with `-mno-avx2`.

Here's a backtrace from GDB:

```
#0  ColorspaceConvertBuffer555To8888Opaque_AVX2<true, false> (src=src@entry=0x7ffff2886000, dst=dst@entry=0x7fffec01e010, pixCountVec256=pixCountVec256@entry=98304) at ../../utils/colorspacehandler/colorspacehandler_AVX2.cpp:323
#1  0x0000555555809d6c in ColorspaceHandler_AVX2::ConvertBuffer555To8888Opaque_SwapRB (this=this@entry=0x555558911f00 <csh>, src=src@entry=0x7ffff2886000, dst=dst@entry=0x7fffec01e010, pixCount=pixCount@entry=98304) at ../../utils/colorspacehandler/colorspacehandler_AVX2.cpp:812
#2  0x000055555580c52a in ColorspaceConvertBuffer555To8888Opaque<true, false> (src=0x7ffff2886000, dst=0x7fffec01e010, pixCount=98304) at ../../utils/colorspacehandler/colorspacehandler.cpp:151
#3  0x00005555555f88a4 in RedrawScreen () at main.cpp:1659
#4  0x00005555555fdb99 in common_gtk_main (my_config=0x7fffffffcff0) at main.cpp:3472
#5  0x00005555555fe017 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:3544
```

Compiled with only the flags `-march=native -Og -ggdb3` on GCC 8.2.0.

It appears to be caused by `_mm256_store_si256`'s first argument, `*dst`, being only 16-byte aligned instead of the required 32. The following patch causes the crash to no longer occur.

```patch
--- a/desmume/src/filter/videofilter.cpp
+++ b/desmume/src/filter/videofilter.cpp
@@ -290,7 +290,7 @@

     // Overallocate the source buffer by 8 rows of pixels to account for out-of-bounds
     // memory reads done by some filters.
-    uint32_t *newPixBuffer = (uint32_t *)calloc(width * (height + 8), sizeof(uint32_t));
+    uint32_t *newPixBuffer = (uint32_t *)aligned_alloc(32, width * (height + 8) * sizeof(uint32_t));
     if (newPixBuffer == NULL)
     {
         return result;
```

**Comment by rogerman** [comment]
Thanks for the heads up -- yeah, this is some pretty old code that I wrote way back then. It could certainly use a refactor using the newest internal API that we have nowadays, which would make the code a lot cleaner and nicer. Maybe one day...
