### ISSUE TITLE
Store audio sample into movie

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/desmume#252]
21 Aug 2009 nitsuja "fixed potential microphone desyncs (savestated, and silenced non-mic-button during movie)" and added this note https://github.com/TASVideos/desmume/commit/c20c88bdbc98d448f4e441d2e0fbd4ca36e0008b#diff-531a52533dbbce84f5f5a54b23ee8b93R187

This wasn't a big heal for almost 10 years, but recently a movie was submitted to TASVideos that uses an audio sample, and the game can't be completed without it. But it isn't stored in the movie, even though it is a part of the game input. The administration didn't agree to accept movies without audio samples embedded, so I have to request embedding them.

However, there's no trivial way to do it:
- Since movies are text based, not archive based, you can't just add the files. Samples have to be injected (as they are, or with something like base64) right in the movie "text".
- Then there's a problem with using different samples in one movie. The UI allows to pick another file at any moment, and UI makes it actually load, to be then used whenever the microphone key is pressed.

To resolve all this I propose:
- When starting a movie recording, suggest to load the sample that's currently selected in the mic settings. That allows to store it in the movie header, so when the movie is replayed, it can be fetched just like an external file is fetched.
- If the user changes the sample while the movie is being recorder, the new sample should be written to the movie at the frame it was loaded. This allows to fetch it in time in its entirety, so it could then be used with the microphone hotkey.

**Comment by zeromus** [comment]
I dont like your proposal. Here's what would be better
1. mic sample system is changed to use a filename-based system, maybe like 0.wav, 1.wav, 2.wav etc.
2. add hotkey to rotate between those
3. add current sample choice to each frame's input in the movie, somehow
4. store samples in header and load those instead of what's on disk when loading a movie

**Comment by vadosnaprimer** [comment]
Yeah it's nicer. Requires planning ahead the usage of samples in the movie, but allows to store them all in the header.

What do you think of using base64? It would be very helpful if the sample could be verified against some initial file. Using your variant, I would pick all the WAV files the author claims they have used, start movie recording on my own, and in the movie I get the same sample data recorded. Much like we do with SRAM that's stored in movies in binary form.

**Comment by zeromus** [comment]
i dont understand what base64 has to do with verifying the initial file. your movie header (using the samples provided by the movie author) should match the submitted movie, regardless of the format the samples are stored in. 

the only reason I suggested to put them in the header is because you seemed to want that. It would be even easier if they were NOT stored in the header but rather distributed with the movie, and you can "verify" the samples by seeing if the movie syncs. I can appreciate that it's nice having sram and savestates in the header because that's so common but mic samples are NOT common

**Comment by vadosnaprimer** [comment]
If base64 (or any other encoding) is not used, samples could also be verified just by comparing them with the files directly in a hex editor, But if they are all pre-written right at the top, importing them all at once just to verify is trivial, even if they are encoded.

If they are written in the middle of the movie whenever one loads them, they can still be verified by importing them right at the start instead. So this easier method can be used just as well.

Verifying them separately from movie sync is needed to avoid using copyrighted stuff, we don't want to embed that into published movies (or submissions). So we'd require that the author posts the sample file that was used in the movie, and we would make sure it's what is in the movie indeed.

**Comment by zeromus** [comment]
then we shouldn't put the sample in the header at all (but why would they be using copyrighted mic samples?). if you wish I can just put the hash of the mic samples in the header. or better yet a single hash of the binary concatenated sample files.

**Comment by vadosnaprimer** [comment]
They might not know it's bad and record, say, Rick Astley via microphone and use that in the movie. All sorts of stupid stuff that we want to guarantee doesn't happen.

Since it's a text format, hashes can either be edited or clash, only direct comparison provides the needed level of safety.

**Comment by zeromus** [comment]
1. reject the movie
2. think this scenario through more. someone uses different samples whose hashes match. result: the movie doesn't sync. so what?

**Comment by zeromus** [comment]
the movie would use the wav file. you decide if the wav is OK. if it is, you accept the movie. the movie cant use anything but that wav file. i dont think youve understood my proposal. lets do this again
1. the submission includes 0.wav and 1.wav
2. the movie includes NOTHING new in the header
2b. the movie includes a new entry on each input frame indicating which mic sample is selected (like an analog input)
3. the person replaying the movie places 0.wav and 1.wav from the submission in the special place
3b. if those samples are correct, the movie will sync

**Comment by vadosnaprimer** [comment]
The thing is, admins demanded that the sample is embedded right into the movie file. Otherwise this request wouldn't be needed.

**Comment by zeromus** [comment]
ok then we don't have a choice and why are we discussing it?

**Comment by vadosnaprimer** [comment]
Um, it's a request that the emulator embeds those samples into movies. There are options how to do it.

**Comment by zeromus** [comment]
it will be treated exactly like the RTC, where it's read from the system (or disk) ordinarily, and the chosen value (the samples) are put into the header.

**Comment by zeromus** [comment]
done at 175a471e5e5aeb4578ac3fc25863f573850e27ed

testing is up to you, but let me know if you have problems

**Comment by vadosnaprimer** [comment]
Thank you!
