### ISSUE TITLE
The new OGLRender.cpp is incorrect.

### ISSUE THREAD

**Issue by Csokis** [TASVideos/desmume#254]
Compiling under linux (Ubuntu 18.04.1 LTS) already shows an error. :(

> In file included from ../../OGLRender.cpp:20:0:
../../OGLRender.h:108:38: error: ‘void (* glBlendEquation)(GLenum)’ redeclared as different kind of symbol
 EXTERNOGLEXT(PFNGLBLENDEQUATIONPROC, glBlendEquation) // Core in v1.2
                                      ^
../../OGLRender.h:69:53: note: in definition of macro ‘EXTERNOGLEXT’
  #define EXTERNOGLEXT(procPtr, func) extern procPtr func;
                                                     ^~~~
In file included from ../../OGLRender.h:58:0,
                 from ../../OGLRender.cpp:20:
/usr/include/GL/gl.h:1633:23: note: previous declaration ‘void glBlendEquation(GLenum)’
 GLAPI void GLAPIENTRY glBlendEquation( GLenum mode );
                       ^~~~~~~~~~~~~~~
In file included from ../../OGLRender.cpp:20:0:
../../OGLRender.cpp:161:32: error: ‘void (* glBlendEquation)(GLenum)’ redeclared as different kind of symbol
 OGLEXT(PFNGLBLENDEQUATIONPROC, glBlendEquation) // Core in v1.2
                                ^
../../OGLRender.h:67:41: note: in definition of macro ‘OGLEXT’
  #define OGLEXT(procPtr, func)  procPtr func = NULL;
                                         ^~~~
In file included from ../../OGLRender.h:58:0,
                 from ../../OGLRender.cpp:20:
/usr/include/GL/gl.h:1633:23: note: previous declaration ‘void glBlendEquation(GLenum)’
 GLAPI void GLAPIENTRY glBlendEquation( GLenum mode );
                       ^~~~~~~~~~~~~~~
In file included from ../../OGLRender.cpp:20:0:
../../OGLRender.cpp: In function ‘void OGLLoadEntryPoints_Legacy()’:
../../OGLRender.h:68:93: error: assignment of function ‘void glBlendEquation(GLenum)’
  #define INITOGLEXT(procPtr, func) func = (procPtr)glXGetProcAddress((const GLubyte *) #func);
                                                                                             ^
../../OGLRender.cpp:243:2: note: in expansion of macro ‘INITOGLEXT’
  INITOGLEXT(PFNGLBLENDEQUATIONPROC, glBlendEquation) // Core in v1.2
  ^~~~~~~~~~
../../OGLRender.h:68:93: error: cannot convert ‘PFNGLBLENDEQUATIONPROC {aka void (*)(unsigned int)}’ to ‘void(GLenum) {aka void(unsigned int)}’ in assignment
  #define INITOGLEXT(procPtr, func) func = (procPtr)glXGetProcAddress((const GLubyte *) #func);
                                                                                             ^
../../OGLRender.cpp:243:2: note: in expansion of macro ‘INITOGLEXT’
  INITOGLEXT(PFNGLBLENDEQUATIONPROC, glBlendEquation) // Core in v1.2
  ^~~~~~~~~~
Makefile:1648: recipe for target '../../OGLRender.o' failed
make[1]: *** [../../OGLRender.o] Error 1
make[1]: Leaving directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix'
Makefile:1670: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

The compilation was good yesterday, but no longer after today's "git pull".

**Comment by Jules-A** [comment]
I don't think it will fix it but since glBlendEquation is only being used in 3.2 it probably shouldn't be declared and init in OGLRender.cpp.

**Comment by Csokis** [comment]
I tried, but the same error.

> In file included from ../../OGLRender_3_2.cpp:20:0:
../../OGLRender.h:197:38: error: ‘void (* glBlendEquation)(GLenum)’ redeclared as different kind of symbol
 EXTERNOGLEXT(PFNGLBLENDEQUATIONPROC, glBlendEquation) // Core in v1.2
                                      ^
../../OGLRender_3_2.h:49:53: note: in definition of macro ‘EXTERNOGLEXT’
  #define EXTERNOGLEXT(procPtr, func) extern procPtr func;
                                                     ^~~~
In file included from ../../OGLRender_3_2.h:42:0,
                 from ../../OGLRender_3_2.cpp:20:
/usr/include/GL/gl.h:1633:23: note: previous declaration ‘void glBlendEquation(GLenum)’
 GLAPI void GLAPIENTRY glBlendEquation( GLenum mode );
                       ^~~~~~~~~~~~~~~
In file included from ../../OGLRender_3_2.cpp:20:0:
../../OGLRender_3_2.cpp:41:32: error: ‘void (* glBlendEquation)(GLenum)’ redeclared as different kind of symbol
 OGLEXT(PFNGLBLENDEQUATIONPROC, glBlendEquation) // Core in v1.2
                                ^
../../OGLRender_3_2.h:47:41: note: in definition of macro ‘OGLEXT’
  #define OGLEXT(procPtr, func)  procPtr func = NULL;
                                         ^~~~
In file included from ../../OGLRender_3_2.h:42:0,
                 from ../../OGLRender_3_2.cpp:20:
/usr/include/GL/gl.h:1633:23: note: previous declaration ‘void glBlendEquation(GLenum)’
 GLAPI void GLAPIENTRY glBlendEquation( GLenum mode );
                       ^~~~~~~~~~~~~~~
In file included from ../../OGLRender_3_2.cpp:20:0:
../../OGLRender_3_2.cpp: In function ‘void OGLLoadEntryPoints_3_2()’:
../../OGLRender_3_2.h:48:93: error: assignment of function ‘void glBlendEquation(GLenum)’
  #define INITOGLEXT(procPtr, func) func = (procPtr)glXGetProcAddress((const GLubyte *) #func);
                                                                                             ^
../../OGLRender_3_2.cpp:87:2: note: in expansion of macro ‘INITOGLEXT’
  INITOGLEXT(PFNGLBLENDEQUATIONPROC, glBlendEquation)
  ^~~~~~~~~~
../../OGLRender_3_2.h:48:93: error: cannot convert ‘PFNGLBLENDEQUATIONPROC {aka void (*)(unsigned int)}’ to ‘void(GLenum) {aka void(unsigned int)}’ in assignment
  #define INITOGLEXT(procPtr, func) func = (procPtr)glXGetProcAddress((const GLubyte *) #func);
                                                                                             ^
../../OGLRender_3_2.cpp:87:2: note: in expansion of macro ‘INITOGLEXT’
  INITOGLEXT(PFNGLBLENDEQUATIONPROC, glBlendEquation)
  ^~~~~~~~~~
Makefile:1648: recipe for target '../../OGLRender_3_2.o' failed
make[1]: *** [../../OGLRender_3_2.o] Error 1
make[1]: Leaving directory '/mnt/minden/Letöltések/desmume-testFix/desmume/src/frontend/posix'
Makefile:1670: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Jules-A** [comment]
Ugh... Okay lol I guess it's some kind of registry issue, I guess you can try my other test branch if you got spare time which is using OGL3.3 and updated registry: https://github.com/Jules-A/desmume/tree/testOgl . Rogerman might be on soon if you just want to wait. I must admit I am rather curious as to why exactly this is occurring.

**Comment by Csokis** [comment]
New Error! :)

> depbase=`echo ../../OGLRender.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"desmume\" -DPACKAGE_TARNAME=\"desmume\" -DPACKAGE_VERSION=\"svn\" -DPACKAGE_STRING=\"desmume\ svn\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"desmume\" -DVERSION=\"svn\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSVN_REV=0 -DSVN_REV_STR=\"0\" -DHAVE_LIBZ=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_LIBDL=1 -DHAVE_LIBGL=1 -DHAVE_GL_GLX_H=1 -DHAVE_GL_GLX=1 -DHAVE_LIBSOUNDTOUCH=1 -DHAVE_JIT=1 -DHOST_LINUX=1 -DHOST_64=1 -I.  -I./../../../src/ -I./../../../src/libretro-common/include -I./../../../src/frontend -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -I/usr/include/alsa -I/usr/include/agg2 -I/usr/include/soundtouch    -g -O2 -MT ../../OGLRender.o -MD -MP -MF $depbase.Tpo -c -o ../../OGLRender.o ../../OGLRender.cpp &&\
mv -f $depbase.Tpo $depbase.Po
make[1]: *** No rule to make target '../../OGLRender_3_2.cpp', needed by '../../OGLRender_3_2.o'.  Stop.
make[1]: Leaving directory '/mnt/minden/Letöltések/desmume-testOgl/desmume/src/frontend/posix'
Makefile:1672: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Jules-A** [comment]
Yeah silly me, forgot all the makefiles etc. need name changing :/
