### ISSUE TITLE
Bugs with Anguna

### ISSUE THREAD

**Issue by Felipefpl** [TASVideos/desmume#255]
Hi, i have win7 x64 and desmume 0.9.11 x64 and these problems happen with this free game: 

http://www.tolberts.net/anguna/

DS version of anguna - i cant save using the game saving function, save states work fine, i cant save neither in no$gba so idk if this is a problem of both emus or from the game itself.

GBA version of anguna - it shows the error msg below when i try to load the game, after that it says it failed to load the game, idk why since the emu shows supports for .gba

![anguna](https://user-images.githubusercontent.com/5569804/52527249-ac67ed80-2cac-11e9-9168-beb701b08f77.gif)

**Comment by zeromus** [comment]
Homebrew games are usually not programmed to save correctly. They depend on the existence of a flash card. Ask the web for advice on how to make ANY homebrew save on desmume; this one in particular is no different. In short, use config > slot > 2 GBA cartridge and mount the same rom in the GBA slot, or use config > slot 2 > MPCF flash card device

**Comment by Felipefpl** [comment]
zeromus - hi, thank you for the explanation. :)
