### ISSUE TITLE
freezed game, clueless on how to advance

### ISSUE THREAD

**Issue by sykdan2188** [TASVideos/desmume#256]
First of all, I'm sorry if someone had complained about this in the past, I just ran into this and I'm clueless on how to fix it. I have tried to Google a solution but wasn't successful. 

Basically, I'm playing this game, Mario and Sonic at the Olympic winter games Vancouver 2010. There's an adventure mode with 6 islands, and when I unlocked the 5th and tried traveling to it, the game froze. I restarted my machine, saved and loaded, nothing.

If anyone smart on this place can help me, I'll be pleased. 

If I need to provide some files, you can ask me.

**Comment by zeromus** [comment]
http://www.lmgtfy.com/?q=mario+and+sonic+olympic+desmume+freeze

**Comment by sykdan2188** [comment]
This is what I did, and I didn't find any fix. Thanks for being a dick to me.

**Comment by zeromus** [comment]
You didn't say that's what you did; you said you did other things. You said you werent successful googling solutions, not that you succeeded googling suggestions but that the suggestions didn't resolve your problem. I don't have any confidence that you've googled correctly, OR read correctly, OR tried any of the provided fixes correctly

**Comment by sykdan2188** [comment]
I did find a lot of download links to patches and fixes, but they were obsolete. This is why I asked here in the first place, honestly...

**Comment by zeromus** [comment]
No, they weren't. Go back and read them again.

Game patches don't get obsolete, unless the problem is fixed in other ways. If the problem isn't fixed in other ways, the patch isn't obsolete.

**Comment by sykdan2188** [comment]
The links (downloads) were obsolete. Not the patches themselves.

**Comment by zeromus** [comment]
https://sourceforge.net/p/desmume/bugs/1455/?page=1

**Comment by sykdan2188** [comment]
I'm sorry if I sound dumb or something, but,

"Disable EVERY checkbox in emulation settings." 

Is that the workaround?

I can't test it right now, because I'm not at my computer.

**Comment by sykdan2188** [comment]
Nope, that didn't work for me.

**Comment by zeromus** [comment]
then use the exact version I said I tested it on
