### ISSUE TITLE
Crash for wrong location

### ISSUE THREAD

**Issue by Elystaer** [TASVideos/desmume#257]
The emulator crashed again and again before i found what was wrong: it was trying to load a game in GBA slot which was actually missing. As I said, my problem is solved, but i'm here to signal the crash without information about it.

There might be either a toolbox telling the problem, or a "ignore GBA slot if file is invalid" function.

**Comment by zeromus** [comment]
works for me in windows 7. Failure to load gba file is safely handled benign condition
