### ISSUE TITLE
Star Wars The Clone Wars (E) - Black screen after starting a game

### ISSUE THREAD

**Issue by DarkSwan86** [TASVideos/desmume#26]
After the main title screen, when you start a game, it simply shows a black screen but DesMuMe isn't hanged (infinite loop)?

More info from SourceForge bugtracker: 

The regression on the intro was introduced on 3396, as mtabachenko commented:

"core:- fix timings in THUMB CPU mode (fix bug #2879374 and break SW: CW JA intro :(, maybe mistake in WiFi emulation);"

--- ROM INFO ---
ROM game code: CLWP
ROM serial: NTR-CLWP-EUR
ROM chipID: 0000FFC2
ROM internal name: SW:CW JA
ROM developer: LucasArts Entertainment

--- PC INFO ---
CPU: Intel i5-4670K
GPU: AMD Radeon 7950
Driver version: Crimson ReLive Edition 16.12.2 (December 2016)
OS: Windows 7 x64

**Comment by zeromus** [comment]
Seems to be fixed by 
https://github.com/TASVideos/desmume/commit/281268e05fc7b334cdd51b8f892b99d651cac795
