### ISSUE TITLE
Local multiplayer

### ISSUE THREAD

**Issue by dgrisham** [TASVideos/desmume#260]
Hi -- I looked on the FAQ and the existing (open/closed) issues, but haven't seen anything about this. Is there any way of supporting (or intention to implement) local multiplayer in DeSmuME? I'm specifically asking about the feature that, on the DS, uses infrared to connect to local DS's. In DeSmuME, I'm guessing that it'd look more like mapping some local port to DeSmuME that other computers on the network can connect to. To me, this could alleviate a lot of the desire for WiFi support -- e.g. for Pokemon you could battle/trade with anyone if you could figure out how to connect to their IP (with port forwarding/etc.). But if it's overly complicated, it may not be worth it -- just curious about the possibility.

**Comment by zeromus** [comment]
It's possible. There are no intentions. It may never work over the internet though, as internet latency is considerably higher than infrared latency. And so it may never even be attempted over the internet (it would be two instances on the same PC). Feel free to go investigate which other emulators have implemented infrared over the internet and write about it here for future reference
