### ISSUE TITLE
Permanent fullscreen mode or fullscreen CLI parameter.

### ISSUE THREAD

**Issue by bandithedoge** [TASVideos/desmume#262]
My controller-only frontend setup relies on the command line for launching games. I know you can press Alt+Enter but it goes back to windowed after relaunching the emulator. Can I do something about it?

**Comment by zeromus** [comment]
can't your controller-only frontend synthesize alt+enter keystrokes?

**Comment by bandithedoge** [comment]
It can, but it's not the most elegant solution since I want it to be as clean as possible.

**Comment by zeromus** [comment]
nah
