### ISSUE TITLE
Magical Starsign Not working?

### ISSUE THREAD

**Issue by awfulArtist** [TASVideos/desmume#265]
Trying to play Magical Starsign, and I can get past all opening cutscenes and save the game right before the battle tutorial. But when it tries to open the battle tutorial, it immediately either freezes and won't continue no matter how long I wait, or it just outright crashes.

**Comment by zeromus** [comment]
using which version of desmume, using all default configurations?

**Comment by awfulArtist** [comment]
0.9.11, the x64 windows ver. Its all default, I deleted all cheats, I've tried shifting a few things around but have put everything back to default now.

**Comment by zeromus** [comment]
0.9.11 is old. use latest buildbot version

**Comment by awfulArtist** [comment]
I can't find the latest build then, Every website I can find has that one as the latest one

**Comment by zeromus** [comment]
show me which web sites you looked at, each of which have that one as the latest one

**Comment by awfulArtist** [comment]
https://desmume.org/category/releases/
http://desmume.org/download/
https://www.filehorse.com/download-desmume-64/
https://www.emuparadise.me/Nintendo_DS_Emulators/Windows/DeSmuME/41
https://desmume.en.uptodown.com/windows/download/147767

**Comment by zeromus** [comment]
on the 1st URL, I see no files, but only a link to the 2nd URL
on the 2nd URL I see files from 2019.

**Comment by awfulArtist** [comment]
I tried the one from the 2019 march post and the first time I ran through the opening it froze again, but quickly resumed. Thanks a ton, sorry I'm new to this still and kinda stupid with it lmao

**Comment by zeromus** [comment]
I just got battle tutorials without any hanging. I dunno what you did, some mysterious hacking or cheating or config-changing.
