### ISSUE TITLE
Speed Up Emulation on latest version

### ISSUE THREAD

**Issue by Aurorans** [TASVideos/desmume#267]
Hello. I'm trying everything to get the emulator to go past 10 FPS.

I have an intel i7700K performance edition, with 32 GB of ram, and a Nvidia Geforce 1060 Ti Graphics card.

I'm using the latest master of 9.12

I have tried using 12% - 100% dynamic recompiler, adding Speed Hacks, and setting the following:

All Combined and individually

Emulation Settings:
Uncheck Enable Advanced Bus-Level Timing
Uncheck Enable Game HAcks
Check Use Dynamicv Recompiler
Block Size: 100%

Sound Settings:
Dual SPU Synch/Asynch
Sound Core - None
Buffer Size - 0
Interpolation - None
Volume - 0
Uncheck Advanced SPU Logic

3D Settings
SoftRasterizer/OpenGL OLD/OpenGL 3.2
GPU Scaling Factor: 1
GPU color Depth: 15bit
Texture Scaling: x1
Multisample Antialiasing: Disabled
Uncheck High Precision Color Interpolation
Uncheck TXT hack
Uncheck Line Hack
Uncheck Deposterize Textures
Uncheck Smooth Textures
Uncheck Enable Edge Marking
Uncheck Enable Fog
Uncheck Enable Textures
Uncheck Enable Shadow Polygons
Uncheck Enable NDS Style Depth Calculation
Uncheck Enable Special Zero Alpha Blending
Uncheck Enable Depth L-Equal Polygon Facing

Other: 
Frame skip - 9

Even with all these settings combined, I'm still only getting 10 FPS on this particular build of the emulator. On the latest emulator from the Desmume Nightly Builds downloads, it runs past 60FPS. However, the Nightly Builds currently don't support lua scripting.

I would use 9.11, but the graphics there are limited.

**Comment by zeromus** [comment]
leave ALL settings on default, then change options in config > display method. Your system, has buggy GPU drivers or "desktop enhancements" installed which are breaking options affected by those choices

**Comment by zeromus** [comment]
wait, are you trying to build desmume? If so, learn how to use visual studio: don't make a debug build

**Comment by zeromus** [comment]
Yes, I see now that I have apprehended your thought process perfectly. Lua DOES fail in a nightly build but works in the (slow) debug build you make (but not as of 55c158d305166128a3c2bad4419033c974fdc14a)
Next time you have a problem, the fastest way to fix the problem is to post a bug about the problem, not post an issue about a problem you ran into while trying to work around the bug you never told us about

**Comment by Aurorans** [comment]
Hey zeromus, I did post that part of the issue.

"Even with all these settings combined, I'm still only getting 10 FPS on this particular build of the emulator. On the latest emulator from the Desmume Nightly Builds downloads, it runs past 60FPS. However, the Nightly Builds currently don't support lua scripting.

I would use 9.11, but the graphics there are limited."

I didn't think it was all that prevalent, but thanks for telling me that the debug build is slow. I'll test out the release build and get back to you.

In any case, do you happen to know why Lua fails in the nightly build?

**Comment by zeromus** [comment]
Doesn't matter. I fixed it.
