### ISSUE TITLE
Homie Rollerz (U) - No character on top selection screen on both render

### ISSUE THREAD

**Issue by DarkSwan86** [TASVideos/desmume#27]
On the racer selection screen, the top screen should show the selected racer (3d model).

![2202 - homie rollerz u __21917](https://cloud.githubusercontent.com/assets/24975273/21742232/a676bce2-d4ea-11e6-8f31-b6ce4aa2cf8d.png)

--- ROM INFO ---
ROM game code: YHRE
ROM serial: NTR-YHRE-USA
ROM chipID: 00000FC2
ROM internal name: HOMIEROLLERZ
ROM developer: Unknown

--- PC INFO ---
CPU: Intel i5-4670K
GPU: AMD Radeon 7950
Driver version: Crimson ReLive Edition 16.12.2 (December 2016)
OS: Windows 7 x64

**Comment by zeromus** [comment]
This problem is basically solved. I fixed it for softrasterizer. The fix belongs in code shared between the engines, but that's not happening soon, so it needs porting to opengl for now.

**Comment by rogerman** [comment]
Fixed in commit c71da85.
