### ISSUE TITLE
[Cheats] Checksum not matching

### ISSUE THREAD

**Issue by Ninjistix** [TASVideos/desmume#271]
![image](https://user-images.githubusercontent.com/12572974/56814290-dbeab880-680c-11e9-914c-5de7f8958e61.png)

Happens on the official 9.11 release also, using cheat file from 
DeadSkullzJr's Cheat Databases (v2.1.0) - October 28, 2018
GBAtemp:
https://gbatemp.net/threads/deadskullzjrs-flashcart-cheat-databases.488711/

the cheats still work but the popup happens every time you try to load the cheatdb

**Comment by zeromus** [comment]
http://forums.desmume.org/viewtopic.php?id=11156
