### ISSUE TITLE
[Feature Request] Multi-language user interface

### ISSUE THREAD

**Issue by ZSkycat** [TASVideos/desmume#272]
Allow users to use language configuration file.

**Comment by zeromus** [comment]
nah. it'll just get broken and out of date.

**Comment by ZSkycat** [comment]
@zeromus 
Just provide feature. Translation can be done by fans. Like [KeePass](https://keepass.info/translations.html).

There are actually examples of language localization.
It is very inconvenient to modify each version currently updated.

![image](https://user-images.githubusercontent.com/20368649/57172820-e550d200-6e57-11e9-990c-2bc3573cc721.png)
