### ISSUE TITLE
Pokemon Heart Gold save loading error

### ISSUE THREAD

**Issue by crimsonicchaos** [TASVideos/desmume#283]
the game loads up fine but when I press on my save file the screen goes black and freezes, can someone help me?

**Comment by zeromus** [comment]
Did you ever hack or cheat? Are you sure it's frozen, or could it just be black? Do you hear music?

**Comment by crimsonicchaos** [comment]
I don't hear anything I even put it on a AP patcher to see if something was wrong but it showed that the file was okay

**Comment by crimsonicchaos** [comment]
![image](https://user-images.githubusercontent.com/27197442/60656843-0f336e80-9e72-11e9-87e8-72a77ea3207e.png)
screenshot

**Comment by crimsonicchaos** [comment]
but I used a cheat that said it would fix it should I try deleting that?

**Comment by crimsonicchaos** [comment]
and another thing I was playing on fast mode the whole time

**Comment by zeromus** [comment]
I dont know what "fast" mode is, but if you cheated before it broke, then that's what broke it. I've never had any proof that anyone is having this problem unless they've cheated. Take a screenshot of what it looks like before you "press on your save file screen". Do you hear music at that point?

**Comment by crimsonicchaos** [comment]
yes I do but after the black screen appears I hear nothing

**Comment by zeromus** [comment]
waiting for a screen shot. Did you close desmume quickly after saving last time? Are you storing your files on a USB drive or on your hard disk?

**Comment by crimsonicchaos** [comment]
hard disk
