### ISSUE TITLE
Feature request: independent windows for the two screens

### ISSUE THREAD

**Issue by amomchilov** [TASVideos/desmume#285]
There are lots of use cases for Nintendo DS screens that can be placed in ways besides the usual vertical stack. It would be nice to support them

There seems to be a lot of community interest in this:
1) https://github.com/OpenEmu/OpenEmu/issues/597
2) https://sourceforge.net/p/desmume/feature-requests/185/
3) https://sourceforge.net/p/desmume/feature-requests/158/

Ideally, I think the two screens could be made into two separate, individually scalable, positionable and rotatable windows. This affords users the flexibility to juxtapose them as they wish. There are a bunch of configurations that would be nice to support, and they could all be satisfied by this approach.

1) Vertically stacked with a gap (for games that depend on a certain distance between the screens)
2) Vertically stacked without a gap, perhaps even with different screen sizes (e.g. for a game where the bottom screen is only a dashboard or map, that isn't as important as the upper screen)
3) Horizontally stacked and rotated, "like a book" (for games that require it)
4) Horizontally stacked to better make use of mac screen space
5) Split across separate screens (e.g. use a TV for the upper screen, and a coffee-table MacBook screen for the lower screen)

I saw this related ticket [#172 Wishlist for windows port obvious features incl. window and screen layout options](https://github.com/TASVideos/desmume/issues/172), but it seems orthogonal to this feature. My interest in this comes from wanting to run dual windows in OpenEMU on a Mac, not on Windows.

What do you guys think?

**Comment by zeromus** [comment]
this is openemu's job.

**Comment by rogerman** [comment]
@amomchilov, you do realize that the standalone DeSmuME Mac port has already had every single one of these features you mentioned since v0.9.9, you know?

**Comment by amomchilov** [comment]
I did not! I just found it in [the changeling](https://github.com/TASVideos/desmume/blob/master/desmume/ChangeLog#L145). Great stuff!
