### ISSUE TITLE
game james cameron's avatar crashes the 0.9.11 version of the emulator

### ISSUE THREAD

**Issue by kotenok2000** [TASVideos/desmume#286]
The 0.9.11 version of the emulator crashes at the beginning of the game.
[crash event.txt](https://github.com/TASVideos/desmume/files/3388682/crash.event.txt)
here is the config file of the emulator.
[desmume.ini.txt](https://github.com/TASVideos/desmume/files/3388683/desmume.ini.txt)
The 0.9.10 version of the emulator does not crash.

**Comment by zeromus** [comment]
Try again in a version that isn't years old by going to desmume.org and finding buildbot links
