### ISSUE TITLE
desmume-glade incompatible libglade 

### ISSUE THREAD

**Issue by sodomon2** [TASVideos/desmume#290]
Apparently when I run the demume-glade gives me a compatibility error with libglade Here's the error

diego [~/Descargas/games/desmume-master/desmume/src/frontend/posix/gtk-glade]$ ./desmume-glade 
Failed to set format: Invalid argument
Microphone init failed.
DeSmuME 0.9.12 git#0 x64-JIT SSE2

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.518: Unable to locate theme engine in module_path: "adwaita",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.520: Unable to locate theme engine in module_path: "adwaita",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.527: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.527: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.527: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.530: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.530: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.530: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.530: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.532: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.532: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.532: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): Gtk-WARNING **: 02:55:58.533: Unable to locate theme engine in module_path: "murrine",

(desmume-glade:12847): libglade-CRITICAL **: 02:55:58.535: glade_xml_construct: assertion 'fname != NULL' failed

(desmume-glade:12847): libglade-CRITICAL **: 02:55:58.535: glade_xml_construct: assertion 'fname != NULL' failed

(desmume-glade:12847): libglade-CRITICAL **: 02:55:58.535: glade_xml_get_widget: assertion 'self != NULL' failed

(desmume-glade:12847): libglade-CRITICAL **: 02:55:58.535: glade_xml_get_widget: assertion 'self != NULL' failed

(desmume-glade:12847): libglade-CRITICAL **: 02:55:58.535: glade_xml_get_widget: assertion 'self != NULL' failed

(desmume-glade:12847): libglade-CRITICAL **: 02:55:58.535: glade_xml_get_widget: assertion 'self != NULL' failed

(desmume-glade:12847): Gtk-CRITICAL **: 02:55:58.535: IA__gtk_check_menu_item_set_active: assertion 'GTK_IS_CHECK_MENU_ITEM (check_menu_item)' failed

** (desmume-glade:12847): CRITICAL **: 02:55:58.535: void glade_xml_signal_autoconnect_StringObject(GladeXML*): assertion 'self != NULL' failed

** (desmume-glade:12847): CRITICAL **: 02:55:58.535: void glade_xml_signal_autoconnect_StringObject(GladeXML*): assertion 'self != NULL' failed

(desmume-glade:12847): GtkGLExt-CRITICAL **: 02:55:58.573: gtk_widget_set_gl_capability: assertion 'GTK_IS_WIDGET (widget)' failed
gtk_widget_set_gl_capability

**Comment by zeromus** [comment]
inspect get_ui_file() in main.cpp which is what's failing and returning null. you apparently have a system configuration problem or user error in building which makes the glade GLADEUI_UNINSTALLED_DIR and DATADIR unset or nonexistent.
