### ISSUE TITLE
Request: New Hotkeys2

### ISSUE THREAD

**Issue by yuya495** [TASVideos/desmume#292]
zeromus's Hello I am using so because Japanese English is not good Google translation

I want you to be able to assign a hot key to Close ROM too, for example Ctrl + Back space

**Comment by zeromus** [comment]
Why? Closing a rom is not very useful. Some emulators do not even have this option.

**Comment by yuya495** [comment]
It is very convenient for me

**Comment by zeromus** [comment]
Why is it very convenient for you?

**Comment by yuya495** [comment]
It ’s very cumbersome to open the file menu and select Close ROM.
![amarec(20190821-132715)](https://user-images.githubusercontent.com/8580180/63402876-e2ceb400-c417-11e9-95ed-a09fc57dd26b.PNG)

**Comment by zeromus** [comment]
1. why do you have to Close ROM?
2. alt+f, C

**Comment by yuya495** [comment]
If it seems impossible, close this issue.
