### ISSUE TITLE
Future of Desmume

### ISSUE THREAD

**Issue by Amul2004** [TASVideos/desmume#293]
What are you guys working on which feature these days ?
Will 0.9.12 will ever be released??
And please update your website, because it took me quite a time to even find the official repo of desmume!

**Comment by zeromus** [comment]
If it took you quite a time, that's your fault. The desmume website has ample links to github.

**Comment by Amul2004** [comment]
Ok it might be my own fault(sorry for that)...

But at least tell the features on which you are working on these days?
And also please tell if 0.9.12 will ever be released??

**Comment by zeromus** [comment]
1. check the commit history
2. why does it matter?
