### ISSUE TITLE
Save file from DS isn't recognized

### ISSUE THREAD

**Issue by PureTryOut** [TASVideos/desmume#297]
I have a save of Pokémon Platinum on a R4 card for my DS, which works fine when played on the DS itself. However, the same save copied to my PC doesn't work with DeSmuME. The console reports that it does find the `.sav` file and converts it to the new format, but when booting the game it starts a new save anyway.

```
BackupDevice: DeSmuME .dsv save file not found. Trying to load a .sav file.
BackupDevice: Converting old raw .sav file.
```

I copied the game originally to my DS to enable a cheat that I couldn't get to work otherwise, but I disabled it again after using it and made sure to save the game again before transferring the save back to my PC. I'm guessing that cheat is still messing things up somehow?

The save: [Pokemon Platinum.txt](https://github.com/TASVideos/desmume/files/3652364/Pokemon.Platinum.txt). Just rename it to `.sav` or `.dsv`.

**Comment by zeromus** [comment]
r4 .sav is not the same as the raw .sav desmume imports automatically. Use the "import backup memory" menu option in desmume to correctly identify the format and import it

**Comment by PureTryOut** [comment]
My DeSmuMe doesn't have that option. I'm on Linux, so using the GTK UI, which is probably different from the one used on Windows and the likes.

Can't support for this format be added? I'm guessing I'm not the only one with an R4 card out there which also likes to emulate his game on PC.

**Comment by zeromus** [comment]
use wine

**Comment by PureTryOut** [comment]
I'm sorry, but are you serious? I'm using this emulator on a supported platform, but have to run it on a different platform just to get a function which probably works fine on my platform too but just lacks a menu option to use it?

Why is this function not available on Linux in the first place? Why do the different platforms even use different GUI's? GTK and other GUI toolkits should work fine on multiple platforms like Linux _and_ Windows.
