### ISSUE TITLE
Transformers Autobot (I) - Black screen after intro

### ISSUE THREAD

**Issue by DarkSwan86** [TASVideos/desmume#30]
The italian version of this game shows black screen after you start a new game. The (U) version works perfectly.

--- ROM INFO ---
ROM game code: AFZI
ROM serial: NTR-AFZI-ITA
ROM chipID: 00003FC2
ROM internal name: TRANSFORMERS
ROM developer: Activision

--- PC INFO ---
CPU: Intel i5-4670K
GPU: AMD Radeon 7950
Driver version: Crimson ReLive Edition 16.12.2 (December 2016)
OS: Windows 7 x64

**Comment by zeromus** [comment]
http://melonds.kuribo64.net/board/thread.php?id=25
they think it's a bad dump

**Comment by zeromus** [comment]
so let's call it a bad dump
