### ISSUE TITLE
Desmume doesn't compile on Arch linux

### ISSUE THREAD

**Issue by CaioVdmm** [TASVideos/desmume#302]
I can't compile desmume on my archlinux.
it give me this error:
`/usr/include/glib-2.0/glib/gmacros.h:988:33: error: missing binary operator before token "_Pragma"
  988 | #define _GLIB_GNUC_DO_PRAGMA(x) _Pragma(G_STRINGIFY (x))`
please help

**Comment by zeromus** [comment]
not desmume problem. archlinux problem. change glib version or compiler version.
