### ISSUE TITLE
Fullscreen bars on linux

### ISSUE THREAD

**Issue by Csokis** [TASVideos/desmume#309]
Why not black bars in fullscreen? Why white/grey?

[https://i.imgur.com/s2FReMj.png](https://i.imgur.com/s2FReMj.png)

_Xubuntu 18.04.3 LTS + github code compiled._

**Comment by sietschie** [comment]
It seems this happens because they just use the default gtk background color in full screen.
I also found this choice unexpected. I changed it and added a pull request.
If this solution is suitable maybe it can be merged into the master.

**Comment by Csokis** [comment]
Thank You! It's perfect for me. :)

[https://i.imgur.com/ewMWJk5.jpg](https://i.imgur.com/ewMWJk5.jpg)
