### ISSUE TITLE
Request:Nintendo DS loader Ghidra

### ISSUE THREAD

**Issue by ElatedEatrs** [TASVideos/desmume#310]
In the same style as this https://github.com/aldelaro5/ghidra-gekko-broadway-lang preferably the arm9 processor first and arm7 second. Please close this issue.

**Comment by zeromus** [comment]
closing, as requested (???)

**Comment by ElatedEatrs** [comment]
I asked this to be closed as this isn't an issue with the emulator. I want a ghidra D's language as the existing language of armv5t (the Ds's approximate language)is missing instructions. Ghidra is a decompiler
