### ISSUE TITLE
Advance wars dual strike, problem with cursor and highlighted tiles in version 0.9.11

### ISSUE THREAD

**Issue by PinkCheese** [TASVideos/desmume#313]
While playing advance wars dual strike, i noticed that the cursor doesn't properly show up, i fixed this by setting the renderer to softrasterizer and setting the depth comparison treshold to 100, but i don't have the same image quality as in OpenGL. Another issue i encountered is that tiles that are supposed to be highlighted in red when checked for a unit's attack range are highlighted in white instead.

**Comment by zeromus** [comment]
this is a 4.5 year old version of desmume
