### ISSUE TITLE
Failed to compile on arm64, undefined reference to filestream

### ISSUE THREAD

**Issue by nhobson99** [TASVideos/desmume#318]
I've added file_stream.c to Makefile.am as suggested in a previous issue, but it didn't solve my compilation problem.

> ../libdesmume.a(features_cpu.o): In function `check_arm_cpu_feature':
/home/swootch/desmume/desmume/src/frontend/posix/../../libretro-common/features/features_cpu.c:318: undefined reference to `filestream_open'
/home/swootch/desmume/desmume/src/frontend/posix/../../libretro-common/features/features_cpu.c:323: undefined reference to `filestream_gets'
/home/swootch/desmume/desmume/src/frontend/posix/../../libretro-common/features/features_cpu.c:334: undefined reference to `filestream_close'
collect2: error: ld returned 1 exit status
Makefile:559: recipe for target 'desmume' failed
make[2]: *** [desmume] Error 1

I'm attempting this build on a modded Nintendo Switch, so the drivers might not all be there, but that shouldn't prevent a simple include from throwing off the build. I've also rerun autoconf, automake, configure and make several times with different settings, as well as changing the order of include statements just in case something weird was happening there. I've tried `make clean; make` to no avail. Where should I be looking?

Edit to add: the environment is the latest version of L4T Ubuntu v3.0, based on Ubuntu 18 (I think) and I installed all the suggested dependencies listed on the build instructions.

**Comment by zeromus** [comment]
you will have to modify frontend/posix/Makefile.am to check for an ARM cpu (or hardcode it just for yourself) and add file_stream.c to the sources list

**Comment by nhobson99** [comment]
Something about that finally decided to work. I added all .c and .h files from libretro-common/stream to Makefile.am, then ran autoconf, automake, configure and make all.

I also just found out that desmume is in the mainline Ubuntu repo. I tested both and the performance is near identical, both the cli and gtk versions. Glad I got it working from source though, thank you.
