### ISSUE TITLE
 white screen 

### ISSUE THREAD

**Issue by maclaa** [TASVideos/desmume#319]
i was trying to play pokemon renegade platinum (a hackrom) and it ended up being really complicated. i read great comments about desmume and i downloaded the original site's version but i didn't worked, so i tried by the desmume on winds pro, and there is 3 options of desmune emulators: the 32 bit, 64 bit and another one that just says "2020.01.21" and i think it's the newest version. mine wasn't working neither on 64 or the 2020.01.21, just on the 32 bit, but after like, two days, the game started to show a white screen when i tried to play. i tried everything wrote on the faq (and even downloaded a bunch pokemon renegade's versions and the problem stayed), but nothing show results. please send me suggestions on what to do! ;^)
the photos are just to show that even though i tried changing, nothing changed

![2](https://user-images.githubusercontent.com/63129507/78411286-940c0e00-75e5-11ea-9f9e-d951cab52da1.jpg)
![3](https://user-images.githubusercontent.com/63129507/78411288-953d3b00-75e5-11ea-8716-b66946be8c30.jpg)
![4](https://user-images.githubusercontent.com/63129507/78411293-966e6800-75e5-11ea-9446-c02964ddb6fe.jpg)
![5](https://user-images.githubusercontent.com/63129507/78411294-979f9500-75e5-11ea-934c-2d443767ebff.jpg)

ps; sorry if my english isn't the best ;p

**Comment by zeromus** [comment]
Hacked roms arent supported, winds pro is not supported. Desmume 0.9.11 is very old. Use a newer version. White screen: change config > display method.

**Comment by maclaa** [comment]
> Hacked roms arent supported, winds pro is not supported. Desmume 0.9.11 is very old. Use a newer version. White screen: change config > display method.

thank you!!
