### ISSUE TITLE
Bug you will encounter when playing "Castlevania - Dawn of Sorrow"(any version) and are using dynamic recompiler.

### ISSUE THREAD

**Issue by d65090482** [TASVideos/desmume#320]
Bug you will encounter when playing "Castlevania - Dawn of Sorrow"(any version) and are using dynamic recompiler.
If you check "use dynamic recompiler" before or while playing "Castlevania - day of sorrow" and set the "block size" to be greater than 15, you will encounter the following errors in the game: 1. When the scenario dialogue window pops up, there is no yellow border on its edge; 2 When controlled by the player, HP and MP in the upper right corner are abnormal. In addition, when soma is injured and(or) causes damage to the enemy, no number will be displayed.
I'm using version 0.9.11. I don't know if there are any similar errors in the newer version than 0.9.11.
PS: I use Baidu translation, so maybe there will be something different from the meaning expressed in the original, please forgive me.

**Comment by zeromus** [comment]
The whole reason for the block size option is because the "dynamic recompiler" breaks games and the block size controls how badly it breaks. This is not a bug.

**Comment by d65090482** [comment]
> The whole reason for the block size option is because the "dynamic recompiler" breaks games and the block size controls how badly it breaks. This is not a bug.

In this way, please improve or perfect the dynamic recompiler.

**Comment by zeromus** [comment]
The nature of the dynamic recompiler is that it cannot be perfect. It trades accuracy for performance.
