### ISSUE TITLE
File VCRUNTIME140_1.dll is not found. Reinstall the programm.

### ISSUE THREAD

**Issue by renyaia** [TASVideos/desmume#324]
Hello, 
I tried running desmume-vs2019-x64-release.exe and for some reason I get this error. 
"It's not possible to run the code, because the system couldn't find the file VCRUNTIME140_1.dll. To fix this problem, try reinstalling the programm" (<- translation from russian). What could I possibly do?

**Comment by zeromus** [comment]
You can read the bold **Note for Windows users** immediately beneath the desmume.org download link
