### ISSUE TITLE
Is the new git version unable to support double-byte ROM names and folders?

### ISSUE THREAD

**Issue by simperen** [TASVideos/desmume#326]
I am a Chinese player. As the title says, the new Git version, when opening the ROM named Chinese, the following warning message will pop up directly, and the actual save operation cannot be performed in the game.
Returning to the official 0.9.11 version does not have this problem.

![无标题](https://user-images.githubusercontent.com/26716558/80912411-5b3f9000-8d6f-11ea-83dd-1fb70bf03cb3.png)

**Comment by zeromus** [comment]
Works fine for me. Don't choose a directory for battery saves that contains chinese characters in it.

**Comment by simperen** [comment]
No, I ca n’t agree, my Roms directory is in English, only the Rom name is Chinese, it will still report an error, the attachment is my desmume.ini file
[desmume.zip](https://github.com/TASVideos/desmume/files/4573381/desmume.zip)

**Comment by zeromus** [comment]
which example rom file name makes it not work? every one I try works.

**Comment by simperen** [comment]
Just tested again one by one, the results are as follows:
Recent Rom 0=F:\Emu\CH-desmume-win64\Roms\高级战争 毁灭日 汉化完善版.nds  not work.
Recent Rom 1=F:\Emu\CH-desmume-win64\Roms\勇者斗恶龙5-天空的新娘.nds    not work.
Recent Rom 2=F:\Emu\CH-desmume-win64\Roms\火焰纹章-光与暗的英雄.nds    It's work
Recent Rom 3=F:\Emu\CH-desmume-win64\Roms\DQMJ2.nds                It's work
Recent Rom 4=F:\Emu\CH-desmume-win64\Roms\火焰纹章-新暗黑龙与光之剑.nds  It's work
Recent Rom 5=F:\Emu\CH-desmume-win64\Roms\黄金太阳-黎明前的黑暗.nds   It's work
Recent Rom 6=F:\Emu\CH-desmume-win64\Roms\银河战士-初猎.nds  It's work
Recent Rom 7=F:\Emu\CH-desmume-win64\Roms\三国志DS2.nds  It's work
Recent Rom 8=F:\Emu\CH-desmume-win64\Roms\风来的西林2 .nds   not work
Recent Rom 9=F:\Emu\CH-desmume-win64\Roms\风来的西林2沙漠之魔城.nds  not work

It ’s a bit weird, it ’s true that not every Rom with Chinese name will report an error.
An interesting test result is:
When I rename DQMJ2.nds to 勇者斗恶龙怪兽篇2.nds, it will not be saved;
When I renamed 最终幻想3.nds (cannot be saved) to 最终幻想III.nds, it became saveable.

I don’t know if these test results can help to solve the problem, thank you very much!

**Comment by zeromus** [comment]
try latest commits

**Comment by simperen** [comment]
> try latest commits

Thank you very much! That's OK.
