### ISSUE TITLE
Pokemon Ranger cropping/warping sprites

### ISSUE THREAD

**Issue by warpKaiba** [TASVideos/desmume#333]
I tried searching around and didn't see anyone mentioning this issue anywhere. Happens on both on 9.11 and the build from here: https://ci.appveyor.com/project/zeromus/desmume/build/artifacts
The top row of pixels on most sprites are cut off. They are rendered with the 3d rendering engine. I've tried openGL and softrasterizer and it happens on both. I've owned this game so I know it's incorrect, I can't take photos but I found an LP on youtube that shows how it's supposed to look (forgive the blurriness this was the only clip I could find that didn't have this issue. looks like no$gba has the same problem). You can also find video of people having the same error on some playthroughs on youtube.

![image](https://user-images.githubusercontent.com/27407917/81996770-8483da00-9613-11ea-9b64-7f9e14b16af3.png)

Compare lapras's horn and the guy's hair.

![image](https://user-images.githubusercontent.com/27407917/81996722-5b634980-9613-11ea-8b69-7d49fa31af6f.png)

For what it's worth I tried the japanese version and it has the same problem.

**Comment by zeromus** [comment]
enable TXT hack. If that doesn't work, there's nothing more you can do.
