### ISSUE TITLE
Unverified Backup memory command

### ISSUE THREAD

**Issue by Liger0** [TASVideos/desmume#334]
When clicking on the "Continue" button with  a working save file and a checksum-verified Rom of Pokemon Heart Gold (It), the console reports

MC9: Unverified Backup Memory command: 08 FROM 020DDDAC
MC9: Unverified Backup Memory command: 08 FROM 020DDE54
MC9: Unverified Backup Memory command: 08 FROM 020DDDAC
MC9: Unverified Backup Memory command: 08 FROM 020DDE54

It doesn't happen with other games so I guess I'd jump to try with this report.

**Comment by zeromus** [comment]
just chatter.
