### ISSUE TITLE
Rendering issue in Pokemon Mystery Dungeon: Explorers of Sky

### ISSUE THREAD

**Issue by JustinWayland** [TASVideos/desmume#336]
On the latest commit of DeSmuMe, a rather noticable artifact occurs in the main menu in that the back of the text box does not cover everything up to the right border, creating a gap where the background peeks through.  This occurs on an unpatched ROM.

![20200601_02-15-29 608 POKEDUN SORA](https://user-images.githubusercontent.com/20479646/83381183-fa2acc80-a3ad-11ea-8648-8e36e292a963.png)

By contrast, this artifact does not occur on the libretro fork of DeSmuMe, as seen below.(apologies for the size)

![4273 - Pokemon Mystery Dungeon - Explorers of Sky (USA)-200601-024518](https://user-images.githubusercontent.com/20479646/83383081-64457080-a3b2-11ea-8c09-e5bdb0b3d460.png)

Since the libretro fork split more than a year ago, I believe that this should be categorized as a regression.

It has existed since before [this commit](https://github.com/TASVideos/desmume/commit/be2735b3c502c79522e554c9461c478f229f9ccf) but probably did not exist at the time of [this commit.](https://github.com/TASVideos/desmume/commit/e06d11f6df8c2e35d570412c45f5a63e5e7c031d)

**Comment by zeromus** [comment]
![image](https://user-images.githubusercontent.com/102701/83437230-02622680-a405-11ea-9902-7ec09444e354.png)

**Comment by JustinWayland** [comment]
<img width="494" alt="Screenshot 2020-06-01 14 44 43" src="https://user-images.githubusercontent.com/20479646/83442648-8375e980-a416-11ea-9513-1e6c95e35e67.png">

This is starting to look like a Mac specific issue.

**Comment by zeromus** [comment]
use softrasterizer, that will probably fix it

**Comment by JustinWayland** [comment]
<img width="246" alt="Screenshot 2020-06-01 15 19 30" src="https://user-images.githubusercontent.com/20479646/83445660-5e37aa00-a41b-11ea-9d4a-f2b2b2c2200d.png">

I am.

**Comment by JustinWayland** [comment]
Just checked the old 2015 Mac release.  This artifact does not appear there.

**Comment by JustinWayland** [comment]
Messed around a bit on the emulator, and switching to OpenGL from SoftRasterizer actually fixes the rendering error.
I'll put the two modes below for comparison.
SoftRasterizer
![20200601_19-21-35 439 POKEDUN SORA](https://user-images.githubusercontent.com/20479646/83463908-5688fd00-a43d-11ea-837c-418f5ec7b051.png)
OpenGL
![20200601_19-21-43 670 POKEDUN SORA](https://user-images.githubusercontent.com/20479646/83463930-6274bf00-a43d-11ea-91d7-b7c800916c4b.png)

**Comment by JustinWayland** [comment]
The rendering error disappears completely if the Fragment Sampling Hack is enabled.

**Comment by zeromus** [comment]
That's rogerman's name for "TXT Hack". The whole purpose of TXT hack is to nudge things left or right by one pixel. It's doing its job and being inappropriately applied in this case.
