### ISSUE TITLE
Virus found

### ISSUE THREAD

**Issue by Supernova3339** [TASVideos/desmume#337]
When downloading the emulator, I scanned it and what do I find? Malware. So somebody has access to the site and is putting malicious ransomware in the code itself.     '

the malicous code file is Malicious.moderate.ml.score

**Comment by zeromus** [comment]
how do I know you didn't download it from a malware site? Provide some useful information. And then use virustotal to confirm that your own virus scanner is creating a false positive.

**Comment by Supernova3339** [comment]
I found it through your site.

**Comment by zeromus** [comment]
How do I know you even know what "our site" is?

**Comment by Supernova3339** [comment]
It’s desmume.org of course I know what it is. A DS emulator, the best of its kind

**Comment by zeromus** [comment]
I don't believe you. Prove it with a URL.

**Comment by Supernova3339** [comment]
I got it from the site: desmume.com which “download link” highlighted in blue redirects to: https://ci.appveyor.com/project/zeromus/desmume/build/artifacts then I get it to prove a point. Guess what I found? Proof that I’m not an idiot.

**Comment by zeromus** [comment]
Guess what I found? Proof that there's no viruses.
https://www.virustotal.com/gui/url/aa97e4693f838a0401824aeca12ed2481a495a4836f6d05530e7dbb2dbd9b96b/detection

**Comment by Supernova3339** [comment]
Here’s proof that there is viruses.
