### ISSUE TITLE
Lua Scripts are crashing the emulator

### ISSUE THREAD

**Issue by Papermanzero** [TASVideos/desmume#34]
If the users tries to add a lua script (windows 10 - desmume x64 with lua51.dll for x64 version) the emulator freezes. I tried the Metroid Prime Hunters script: http://forums.desmume.org/viewtopic.php?pid=26016
Tested the same scripts and dll files with DeSmuME_0.9.11_x64, which was working without issues.

**Comment by zeromus** [comment]
works fine for me with the lua dlls in our repository. Maybe you should get yours from there.

**Comment by Papermanzero** [comment]
As stated 0.9.11 works without issues. However the latest build a5b4df20 seems to have issues with the same setup. A windows pop-up appears, which states that the program does not work anymore.

**Comment by zeromus** [comment]
That's not freezing, that's crashing. And that's not what the error message says. Which dlls did you use?

**Comment by Papermanzero** [comment]
Then it is crashing. Sorry, for the wrong term :-/
From you repository...

**Comment by zeromus** [comment]
Try it with a clean ini file

**Comment by Papermanzero** [comment]
Did that it it was working now.

**Comment by zeromus** [comment]
It's almost certainly related to opengl rendering (I think more likely the latter). I know, it sounds completely unrelated. But there is a strange random memory corruption bug right now which is really really hard to smoke out. If it happens again try switching to softrasterizer.

**Comment by Papermanzero** [comment]
Got again a message (at least no crash). This time: attempt to concatenate a nil value
Good to know how to workaround the issue.

**Comment by zeromus** [comment]
The crash may be different every time. Something's flaking out the opengl drivers. Maybe nvidia only, maybe all of them. I'm not sure yet. Can you say what GPU youve got, for the record?

**Comment by Papermanzero** [comment]
Your guess is right. Nvidia 760 GTX.
A reboot of the emulator solves also the issue.

**Comment by Papermanzero** [comment]
Got now also messages and crash with softrasterizer.

**Comment by zeromus** [comment]
huh, neat, i got it to happen on windows 10

**Comment by Papermanzero** [comment]
I can also share a script which can easily reproduce the bug in Metroid Prime Hunters.

```
positionx =128
if key.right then
		positionx = positionx + 1
		if positionx>255 then
			positionx=0
		end
		stylus.set {x=positionx, y=positiony, touch=true}
		print (positionx)
	end
```

Just hold right and after a while the crash occurs. :-)

**Comment by zeromus** [comment]
are you using --num-cores 1 or running on a 1- or 2-core cpu?

**Comment by Papermanzero** [comment]
My CPU has in total 4 cores. I am not using any arguments.

**Comment by zeromus** [comment]
This may sound crazy too but can you try disabling the toolbar and see if that helps?

**Comment by Papermanzero** [comment]
It is already disabled

**Comment by zeromus** [comment]
I'm out of time debugging this today, but I found one bug already (1-core related) and there is ANOTHER bug -- try closing the main window while lua's running: the main window wont close (but delete MainWindowToolbar has run, and when you try to close the main window again it will crash)

there may be 10000 more bugs

**Comment by Papermanzero** [comment]
Yes, I reproduced this bug also. I closed the window and I saw immediately the crash.
But it is great that you already found a bug. :-)

**Comment by Papermanzero** [comment]
Tried the newest build, which seems to be more stable already. :-)
However the crash still occurs after a certain time (but as said not so easy as previously).

**Comment by zeromus** [comment]
Those commits cant affect this problem except in the --num-cores 1 case

**Comment by LordZane** [comment]
Is this issue fixed in the latest master? Would building from source fix this?

**Comment by zeromus** [comment]
Not intentionally or knowingly. But since I insist it's about 3d and not lua, you may not encounter this anyway.

**Comment by LordZane** [comment]
Actually I messed up, sorry. Turns out my problem was I had to run the lua script AFTER you start the game, and not before

**Comment by harshmp** [comment]
I'm using the latest build (32 bit) and lua scripts are causing crashes. Lua dlls from this repo.

![lua crash](https://user-images.githubusercontent.com/22417006/30518921-2a4eac80-9ba8-11e7-9622-6fd45707feb6.png)

```
local function fn()
	gui.text(2,2,"Hello world")
end
gui.register(fn)
emu.reset()
```

The same script runs on the 0.9.11-win32-dev version without any crashes.

**Comment by zeromus** [comment]
works fine for me. what's "the latest build"? confirm you dont have any special settings that are affecting it (delete your ini file and check it)

**Comment by harshmp** [comment]
Latest auto-build from here: https://ci.appveyor.com/project/zeromus/desmume/build/artifacts

I deleted the ini file and tried loading the script but it still crashes.
It takes some time to crash. Usually it crashes at the screen showed in the screenshot.
Yes, the rom works perfectly fine without lua scripts.
