### ISSUE TITLE
Game won't recognize save file

### ISSUE THREAD

**Issue by itsCopycat** [TASVideos/desmume#341]
just changed emulator to desmume and importing saves files. the **.sav** file changed to **.dsv** already but there's no continue or load game button in-game

**Comment by zeromus** [comment]
.sav isn't a format, it's a catch-all for any format. Properly speaking they should be formatless raw data, but there's no guarantee of that. Some programmers will put anything in a .sav. Therefore correct operation of importing .sav can't be guaranteed. I suggest you get support from the vendor of your prior emulator.
