### ISSUE TITLE
DeSmuME crashes when using iQue BIOS.

### ISSUE THREAD

**Issue by Mario0051** [TASVideos/desmume#346]
Loading any game using the iQue BIOS causes the emulator to crash. The last line that appears in the console is `ARM9 BIOS load: OK.`

**Comment by zeromus** [comment]
Desmume is not an ique emulator. If you found something saying it is on a page we control, please let me know where you found it so I can erase it.

**Comment by eeuq7mi** [comment]
Use v0.9.11 may solve this problem.
https://github.com/TASVideos/desmume/issues/417
