### ISSUE TITLE
DeSmuME closes automatically after trying to open a rom

### ISSUE THREAD

**Issue by olivegoncalves** [TASVideos/desmume#349]
So, I was trying to play DeSmuMe again because it is the one I have the most comfort with, I changed of Windows, I had Windows XP and I got Windows 7 (because the computer is not that advanced) so I started normally with the "Compatibility" button in "Windows XP Service Pack 3" and when I try to open a ROM, the emulator closes automatically and I really want to know what happens.
![DeSmuME Error](https://user-images.githubusercontent.com/68575617/88009534-c4b67b80-cae0-11ea-827a-dd70e9c406a4.jpg)

**Comment by zeromus** [comment]
So don't use compatibility mode

**Comment by olivegoncalves** [comment]
> So don't use compatibility mode

I used to do that but then my computer will lag so hard and I needed to reboot the computer, I started putting it on compatibility mode because in DeSmuME page says that some people have errors while using the emulator, so they would need to put it on compatibility mode.

**Comment by zeromus** [comment]
I can't find "compatibility mode" on "DeSmuME page".
Compatibility mode doesn't fix "lag so hard and I needed to reboot"
Blowing the dust out of your fans, upgrading/downgrading your GPU drivers, uninstalling security software and malware and desktop "enhancement" software, and changing desmume's config > display method <---- things which fix "lag so hard"
