### ISSUE TITLE
Desmume won't run again Mac

### ISSUE THREAD

**Issue by corover1** [TASVideos/desmume#353]
I'm a Mac user. Downloaded latest stable release, patched it with the 3/18 version on the website. I've used it for over a couple weeks now perfectly fine. However today I was messing with the video setting in display seeing how it would change the graphics. As soon as I touched the pixel scaler it crashed and I got a "crashed" error message from Mac. I've tried deleting then reinstalling both the 9.11 version and the 3/18 version; I can only manage to get the original 9.11 to actually run the other just crashes. I sporadically get it to not crash sometimes but all it says is Desmume closed unexpectedly blah blah do you want to reopen your windows, neither option of yes or no changes what happens again right back to the crash message on log. I have not touched the settings since. All my save data was on the 3/18 version through the save state from emulator not in-game. I'd really appreciate some help, I have at least 50 hours play time and don't want to restart. 

Also if it helps the log displays this message:

Application Specific Information:
abort() called
DeSmuME(1174,0x119a06dc0) malloc: *** error for object 0x10f8ba000: pointer being freed was not allocated

**Comment by zeromus** [comment]
next time save in-game and make backups. stop what you're doing right now and make backups of everything; there's no reason to lose data. find someone who knows how to use macs to find where the preferences are stored and erase them so you can undo whatever you did to the pixel scaler settings that glitched your mac. Nobody here is supporting mac right now so youll have to phone a friend over to help.
