### ISSUE TITLE
oamView bug

### ISSUE THREAD

**Issue by w-qhai** [TASVideos/desmume#358]
Version:  0_9_12
Game:  Super Robot Taisen K

I tried to extract images from oam.
But when I checked oam, I found that the image was different from the one in the game.

- this is in game
![raw](https://user-images.githubusercontent.com/21096210/90332096-aca51f80-dfec-11ea-9939-5a566345228d.png)

- this is in 0_9_12
![9_12](https://user-images.githubusercontent.com/21096210/90332152-36ed8380-dfed-11ea-8891-6363432225a1.png)
They are different on the chest and hands

- this is in 0_9_11 (Sorry I cannot compile this version. This is the binary file I downloaded.)
![9_11](https://user-images.githubusercontent.com/21096210/90332154-3f45be80-dfed-11ea-81f0-fb98d6ed76bd.png)

This is the same as in the game.

**Comment by w-qhai** [comment]
Windows

**Comment by zeromus** [comment]
I'm not going to investigate blurry snapshots.
There is no desmume 0.9.12 so I don't know what version you're using.
Post savestates in this scene.

**Comment by w-qhai** [comment]
Sorry, the 0.9.12 version I mentioned is compiled from the latest github code

**Comment by w-qhai** [comment]
Compile desmume with the latest code
Then open Super Robot Taisen K
Click "new game" in the game
tools->view OAM
The robot image displayed is different from the one in the game
