### ISSUE TITLE
Cannot build under Arch Linux - "display.h" is missing

### ISSUE THREAD

**Issue by Gnatzelle** [TASVideos/desmume#360]
Hi Guys and Gals...
I'm unable to build desmume under Arch Linux after the latest commit > https://github.com/TASVideos/desmume/commit/79c6ab430af82d111edcdb210d27f4eea74082ba
cause the file "display.h" is missing. There is one in the /src/frontend/windows folder, but i don't think that would work under *nix i guess? ^^"

**Comment by mark21gt** [comment]
Yes, some files seems to be missing indeed. I don't think using the Windows files will work either.
