### ISSUE TITLE
Pokemon Diamond Slot-2 Feature issues

### ISSUE THREAD

**Issue by ccfman2004** [TASVideos/desmume#361]
I can get Pokemon Diamond to see my Pokemon Emerald Rom but when I try to do the migration I get an in-game error saying the Pal Park is already stocked with 6 Pokemon but it's not as I never added Pokemon in the first place.

<img width="507" alt="Screen Shot 2020-08-24 at 2 59 41 PM" src="https://user-images.githubusercontent.com/79392/91084760-7eda5f00-e61a-11ea-898f-c871b900ff1c.png">

**Comment by zeromus** [comment]
You need to have a gba save file too, else you just have a rom with no save memory which is an unrealistic scenario and the NDS rom gets confused by it

**Comment by ccfman2004** [comment]
The save file is loaded into the emulator

**Comment by ccfman2004** [comment]
<img width="660" alt="Screen Shot 2020-08-24 at 4 11 16 PM" src="https://user-images.githubusercontent.com/79392/91091362-771fb800-e624-11ea-91fb-9500214eaef4.png">

**Comment by zeromus** [comment]
how big is the .sav file

**Comment by ccfman2004** [comment]
128KB.  I have used no tools to hack it.

**Comment by ccfman2004** [comment]
[Pokemon Emerald (U)(TrashMan).sav.zip](https://github.com/TASVideos/desmume/files/5120061/Pokemon.Emerald.U.TrashMan.sav.zip)
[Pokemon Diamond.sav.zip](https://github.com/TASVideos/desmume/files/5120064/Pokemon.Diamond.sav.zip)

**Comment by zeromus** [comment]
It seems like this happens because the _NDS_ game already has six pokemon transferred to it. Simplest explanation is that you do, and you're mistaken. I can't verify it because this NDS sav isn't near the pal park.

**Comment by ccfman2004** [comment]
It doesn't as I have not added any yet.  I am saved at the Pal Park.
[Pokemon Diamond.sav.zip](https://github.com/TASVideos/desmume/files/5120144/Pokemon.Diamond.sav.zip)
.

**Comment by ccfman2004** [comment]
I found an editor that can edit Pal Park info and it shows that there is nothing in the Pal Park bank.

**Comment by ccfman2004** [comment]
I just tried a save I downloaded off the internet and had no issues so I don't know what makes my save different.  I used TwiLightMenu++ and NDS-Bootloader on my N2DS system to start the game from the beginning.

**Comment by zeromus** [comment]
I googled this problem a bit and it seems like bugs in the game. Generally about half the people you find discussing pokemon bugs are emulating without telling you, but I get the feeling this is real. It fits, anyway, since I don't see any way this could be a bug in desmume.

**Comment by zeromus** [comment]
Oh, you used hacking tools to play the game. Brilliant. You voided your warranty. There's no guarantee hacking tools can properly create NDS save data.

**Comment by ccfman2004** [comment]
Everything is running in DS mode.

**Comment by zeromus** [comment]
For your information, save files on the NDS are quite frustrating. It is not clear how large they should be or what the initial contents of memory should be. It is probably not this simple, but changing between default values 0xFF and 0x00 may make a difference.

**Comment by ccfman2004** [comment]
My save from my retail cart uses 0xFF for blanks space and the one from the NDS-Bootloader uses 0x00 for blank space.

**Comment by ccfman2004** [comment]
I found and used a save editor that let's you edit Pal Park Pokemon and the data between the retail save and the nds-bootstrap save was different. So I used the editor to load my save with 6 Pokemon and then I caught them.  Now I can use the emulator to stock Pokemon.
