### ISSUE TITLE
Compiling Mac version error OERingBuffer.h not found and framework not found OpenEmuBase

### ISSUE THREAD

**Issue by ccfman2004** [TASVideos/desmume#362]
When I try to compile the Xcode project for Mac OS 10.14.6 I says that OERingBuffer.h is not found when I use the files I found in the OpenEmu SDK I eventually get "framework not found: OpenEmuBase"

**Comment by ccfman2004** [comment]
I finally found the wiki for compiling and it seems I had the Build setting for OpenEmu checked.  The compiling wiki is very confusing and I cannot compile the app.

**Comment by zeromus** [comment]
ok, open an issue when you have a specific complaint. then don't expect it to get answered, because the mac guy is awol

**Comment by ccfman2004** [comment]
I get Command PhaseScriptExecution failed with a nonzero exit code
