### ISSUE TITLE
Can't have 2 different games running at the same time Mac OS

### ISSUE THREAD

**Issue by ccfman2004** [TASVideos/desmume#365]
When I have 2 windows open and load a ROM it loads it into both windows.

macOS 10.14.6
Version: f6064006d2d4be3d953f5937c32b081970a76184
Xcode 10.1

**Comment by zeromus** [comment]
This can't be an accident. If this happens it's by design, so that you can have two windows for one game. Try launching two application instances instead of one application instance with two windows.

**Comment by ccfman2004** [comment]
With Mac you can only have one instance of an app unless you make a copy and launch that.

**Comment by zeromus** [comment]
Then you can't run 2 different games at one time unless you make a copy and launch that.
