### ISSUE TITLE
Download Play doesn't work.

### ISSUE THREAD

**Issue by ccfman2004** [TASVideos/desmume#366]
When you load the DS menu and click on Download Play you get a screen that doesn't give you the usual searching for downloadable apps.

<img width="517" alt="Screen Shot 2020-08-29 at 7 35 31 PM" src="https://user-images.githubusercontent.com/79392/91649365-3cad8500-ea41-11ea-80ab-295e74a45580.png">

**Comment by zeromus** [comment]
Wifi isn't supported. I assume that's what's blocking this.

**Comment by ccfman2004** [comment]
Then why is there a Wifi settings in the menu then?

**Comment by zeromus** [comment]
For the unsupported wifi features

**Comment by ccfman2004** [comment]
You explicitly told me that migrating from gen 4 to gen 5 was available for like 10 years when I asked about it in the Wishlist thread.

**Comment by zeromus** [comment]
No, I explicitly told you that it's had the ability to load a Slot-1 ROM and launch the DS Bios. If it doesn't allow you to import gen 4 pokemons, that's a bug. If the reason it won't let you import gen 4 pokemons is a wifi bug, then it's a bug in an unsupported feature

**Comment by ccfman2004** [comment]
In order to import gen 4 for gen 5 you need download play which is why I made that post asking if you can do it.

**Comment by zeromus** [comment]
No, you asked if desmume supported booting from the firmware and then made remarks about why that's valuable to you.
