### ISSUE TITLE
Can't compile on Xubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by Csokis** [TASVideos/desmume#371]
I can't compile on Xubuntu 18.04.5 LTS. Here is the error:

> Making all in .
make[1]: Entering directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix'
Making all in gtk
make[1]: Entering directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix/gtk'
Making all in doc
make[2]: Entering directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix/gtk/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix/gtk/doc'
make[2]: Entering directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix/gtk'
depbase=`echo tools/ioregsView.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"desmume\" -DPACKAGE_TARNAME=\"desmume\" -DPACKAGE_VERSION=\"svn\" -DPACKAGE_STRING=\"desmume\ svn\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"desmume\" -DVERSION=\"svn\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSVN_REV=0 -DSVN_REV_STR=\"0\" -DHAVE_LIBZ=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_LIBDL=1 -DHAVE_LIBGL=1 -DHAVE_GL_GLX_H=1 -DHAVE_GL_GLX=1 -DHAVE_LIBSOUNDTOUCH=1 -DHAVE_JIT=1 -DHOST_LINUX=1 -DHOST_64=1 -I.  -I../../../../src/ -I../../../../src/libretro-common/include -I../../../../src/frontend -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -pthread -I/usr/local/include -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/alsa -I/usr/include/agg2 -I/usr/include/soundtouch   -g -O2 -MT tools/ioregsView.o -MD -MP -MF $depbase.Tpo -c -o tools/ioregsView.o tools/ioregsView.cpp &&\
mv -f $depbase.Tpo $depbase.Po
tools/ioregsView.cpp: In function ‘void crea_REG_SPICNT(int)’:
tools/ioregsView.cpp:74:12: error: ‘gtk_box_new’ was not declared in this scope
  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
            ^
tools/ioregsView.cpp:293:21: note: in expansion of macro ‘BIT_COMBO’
   else if(i == 0) { BIT_COMBO(i, "0-1", spicnt_strings[0]);
                     ^~~~~~~~~
tools/ioregsView.cpp:74:12: note: suggested alternative: ‘gtk_hbox_new’
  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
            ^
tools/ioregsView.cpp:293:21: note: in expansion of macro ‘BIT_COMBO’
   else if(i == 0) { BIT_COMBO(i, "0-1", spicnt_strings[0]);
                     ^~~~~~~~~
tools/ioregsView.cpp:74:12: error: ‘gtk_box_new’ was not declared in this scope
  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
            ^
tools/ioregsView.cpp:299:21: note: in expansion of macro ‘BIT_COMBO’
   else if(i == 8) { BIT_COMBO(i, "8-9", spicnt_strings[8]);
                     ^~~~~~~~~
tools/ioregsView.cpp:74:12: note: suggested alternative: ‘gtk_hbox_new’
  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
            ^
tools/ioregsView.cpp:299:21: note: in expansion of macro ‘BIT_COMBO’
   else if(i == 8) { BIT_COMBO(i, "8-9", spicnt_strings[8]);
                     ^~~~~~~~~
tools/ioregsView.cpp:74:12: error: ‘gtk_box_new’ was not declared in this scope
  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
            ^
tools/ioregsView.cpp:305:22: note: in expansion of macro ‘BIT_COMBO’
   else if(i == 10) { BIT_COMBO(i, "10", spicnt_strings[10]);
                      ^~~~~~~~~
tools/ioregsView.cpp:74:12: note: suggested alternative: ‘gtk_hbox_new’
  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
            ^
tools/ioregsView.cpp:305:22: note: in expansion of macro ‘BIT_COMBO’
   else if(i == 10) { BIT_COMBO(i, "10", spicnt_strings[10]);
                      ^~~~~~~~~
tools/ioregsView.cpp: In function ‘void open(int)’:
tools/ioregsView.cpp:457:14: error: ‘gtk_box_new’ was not declared in this scope
   mBox0[c] = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
              ^~~~~~~~~~~
tools/ioregsView.cpp:457:14: note: suggested alternative: ‘gtk_hbox_new’
   mBox0[c] = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
              ^~~~~~~~~~~
              gtk_hbox_new
Makefile:585: recipe for target 'tools/ioregsView.o' failed
make[2]: *** [tools/ioregsView.o] Error 1
make[2]: Leaving directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix/gtk'
Makefile:649: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mnt/minden/Sources/desmume/desmume/src/frontend/posix/gtk'
Makefile:1670: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by zeromus** [comment]
Your output doesn't show you reconfiguring, only making. That's not how building software works.
