### ISSUE TITLE
[Request] Disassembler on Linux GTK / Glade

### ISSUE THREAD

**Issue by Klairm** [TASVideos/desmume#372]
I seen that there's a disassembler tool on the Windows port (https://wiki.desmume.org/index.php?title=DeSmuME_Manual_for_the_Windows_port#Tools_.7C_Disassembler) , but not on Linux, any plans to add it to Linux?

Thanks!

**Comment by zeromus** [comment]
No. if you want to be a console game hacker, use windows or wine.
