### ISSUE TITLE
GTK version does not build

### ISSUE THREAD

**Issue by thesourcehim** [TASVideos/desmume#375]
Entering «/mnt/d/projects/git/desmume/desmume/src/frontend/posix/gtk»
depbase=`echo tools/ioregsView.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"desmume\" -DPACKAGE_TARNAME=\"desmume\" -DPACKAGE_VERSION=\"svn\" -DPACKAGE_STRING=\"desmume\ svn\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"desmume\" -DVERSION=\"svn\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSVN_REV=0 -DSVN_REV_STR=\"0\" -DHAVE_LIBZ=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_LIBDL=1 -DHAVE_LIBGL=1 -DHAVE_GL_GLX_H=1 -DHAVE_GL_GLX=1 -DHAVE_LIBSOUNDTOUCH=1 -DHAVE_JIT=1 -DHOST_LINUX=1 -DHOST_64=1 -I.  -I../../../../src/ -I../../../../src/libretro-common/include -I../../../../src/frontend -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/atk-1.0 -pthread  -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include    -I/usr/include/soundtouch    -g -O2 -MT tools/ioregsView.o -MD -MP -MF $depbase.Tpo -c -o tools/ioregsView.o tools/ioregsView.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/include/gtk-2.0/gtk/gtkobject.h:37,
                 from /usr/include/gtk-2.0/gtk/gtkwidget.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkcontainer.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkbin.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkwindow.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:33,
                 from tools/ioregsView.cpp:22:
/usr/include/gtk-2.0/gtk/gtktypeutils.h:236:64: warning: «GTypeDebugFlags» is deprecated [-Wdeprecated-declarations]
  236 | void            gtk_type_init   (GTypeDebugFlags    debug_flags);
      |                                                                ^
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from tools/ioregsView.cpp:22:
/usr/include/glib-2.0/gobject/gtype.h:685:3: note: declared here
  685 | } GTypeDebugFlags GLIB_DEPRECATED_TYPE_IN_2_36;
      |   ^~~~~~~~~~~~~~~
In file included from /usr/include/gtk-2.0/gtk/gtktoolitem.h:31,
                 from /usr/include/gtk-2.0/gtk/gtktoolbutton.h:30,
                 from /usr/include/gtk-2.0/gtk/gtkmenutoolbutton.h:30,
                 from /usr/include/gtk-2.0/gtk/gtk.h:126,
                 from tools/ioregsView.cpp:22:
/usr/include/gtk-2.0/gtk/gtktooltips.h:73:12: warning: «GTimeVal» is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   73 |   GTimeVal last_popdown;
      |            ^~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from tools/ioregsView.cpp:22:
/usr/include/glib-2.0/glib/gtypes.h:545:26: note: declared here
  545 | typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
      |                          ^~~~~~~~
tools/ioregsView.cpp: In function «void crea_REG_SPICNT(int)»:
tools/ioregsView.cpp:74:12: error: «gtk_box_new» was not declared in this scope; did you mean «gtk_hbox_new»?
   74 |  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
      |            ^~~~~~~~~~~
tools/ioregsView.cpp:293:21: note: in macro expansion «BIT_COMBO»
  293 |   else if(i == 0) { BIT_COMBO(i, "0-1", spicnt_strings[0]);
      |                     ^~~~~~~~~
tools/ioregsView.cpp:74:12: error: «gtk_box_new» was not declared in this scope; did you mean «gtk_hbox_new»?
   74 |  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
      |            ^~~~~~~~~~~
tools/ioregsView.cpp:299:21: note: in macro expansion «BIT_COMBO»
  299 |   else if(i == 8) { BIT_COMBO(i, "8-9", spicnt_strings[8]);
      |                     ^~~~~~~~~
tools/ioregsView.cpp:74:12: error: «gtk_box_new» was not declared in this scope; did you mean «gtk_hbox_new»?
   74 |  _wl_[w] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0); \
      |            ^~~~~~~~~~~
tools/ioregsView.cpp:305:22: note: in macro expansion «BIT_COMBO»
  305 |   else if(i == 10) { BIT_COMBO(i, "10", spicnt_strings[10]);
      |                      ^~~~~~~~~
tools/ioregsView.cpp: In function «void open(int)»:
tools/ioregsView.cpp:457:14: error: «gtk_box_new» was not declared in this scope; did you mean «gtk_hbox_new»?
  457 |   mBox0[c] = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
      |              ^~~~~~~~~~~
      |              gtk_hbox_new
make[2]: *** [Makefile:597: tools/ioregsView.o] Error 1

It seems that configure script still uses GTK2 instead of 3.

**Comment by zeromus** [comment]
@linkmauve

**Comment by davg-qqq** [comment]
#368 ported the fronted to GTK3 and added meson as a buildtool, but the old autotools config files were not updated so they don't work anymore.
Building with meson does work, but I first needed to add pthreads as a dependency for the posix build using `dep_pthread = dependency('threads')`, otherwise the link step would fail because of missing pthread symbols. 
FYI there's also a build error if you try use libagg because the HUD menu code wasn't converted completely.

**Comment by thesourcehim** [comment]
> Building with meson does work, but I first needed to add pthreads as a dependency for the posix build using `dep_pthread = dependency('threads')`

I can confirm that it does build with meson, I did not modify any files.

**Comment by linkmauve** [comment]
Thanks, I just fixed that in 46c7e344393647da83f9b27ac11657cef15bbd55.  I kept the autotools build for the gtk-glade interface, but for the gtk and cli interface you’re better off with meson.  I plan on looking at what to salvage from gtk-glade and merge it into gtk, and eventually remove it, at which point we’ll probably remove autotools altogether.

I didn’t have agg installed when I did the gtk3 port, I’ll have a look, thanks for noticing. :)

**Comment by davg-qqq** [comment]
Sorry, I should have mentioned I'm on xubuntu 20.04, I figured it was something env specific or you would have noticed already.

Fixing the autotools build seems straightforward, just need to change the gtk version and everything works, see https://github.com/davg-qqq/desmume/commit/e2b3e9ffbc253e5999d2aa46940af77ca07ef19b. I'm just not sure what the proper minimum version should be there.

If you're switching to meson only then I think you should update `desmume/README.LIN` to describe the new steps to build the project.

**Comment by linkmauve** [comment]
Thanks, I’ve pushed your commit (with version 3.24 requested, also in meson, because that’s the only one I have available here).
