### ISSUE TITLE
Regression: performance became worse

### ISSUE THREAD

**Issue by thesourcehim** [TASVideos/desmume#376]
I compared two commits: current (2ac787a) and f606400 (before all GTK commits).
In the current commit performance dropped signifficantly with the same settings. Before I ran Order of Ecclesia with 5xBRZ filter at 60 fps fullscreen without problems, but now I barely get 25-28 fps.

[config.cfg.txt](https://github.com/TASVideos/desmume/files/5252365/config.cfg.txt)

**Comment by zeromus** [comment]
it looks like it will be easy to bisect through those commits to find the exact one
@linkmauve

**Comment by thesourcehim** [comment]
First bad commit is 89f5e500393145b07a7d186ce974b0663c38ddf8
GTK: Use accessor to retrieve GtkAdjustment value

**Comment by thesourcehim** [comment]
I don't know if it is important or not, but while bisecting I used different build methods during different steps (as meson did not always work). Also at that specific commit I was relying on fps counter in main window's caption since there was no video at all, window's client area was blank, sound worked though.

**Comment by thesourcehim** [comment]
Turned out build method does matter. Meson creates debug build without optimizations by default, thus performance drop. Meson option --buidtype=release should be added to the build instructions, tested it, got 60fps back.

**Comment by linkmauve** [comment]
Thanks for your investigation, I use `makepkg` to create a package for my distribution, and it builds in release mode by default so I hadn’t seen that.
