### ISSUE TITLE
Distorted graphics

### ISSUE THREAD

**Issue by fatfree69** [TASVideos/desmume#383]
See old version vs new version
![Screen Shot 2020-10-02 at 4 33 21 AM](https://user-images.githubusercontent.com/72250838/94904122-d1ecd080-0468-11eb-8055-1f2e63e6680a.png)

**Comment by zeromus** [comment]
Works fine for me with all settings deleted. You haven't used the error reporting form on the macos version or even told me what game you're playing so I can't see what settings you may have changed. Usually this is fixed by changing the TXT hack option or the 3d renderer optoin
