### ISSUE TITLE
detect USB controller when plugged in wile desmume is running

### ISSUE THREAD

**Issue by fintogive** [TASVideos/desmume#386]
I cant tell you how many time ive forgotten to plug in my controller after opening up desmume and have to close and reopen the emulator in order for desmume to detect the usb controller.  i know this is a minor issue but ive seen it done with other emulators.  Is this possible to do?

**Comment by zeromus** [comment]
not without rewriting 100% of the input code which is already a complete mess. 
Sorry, wishlist is all we can do
