### ISSUE TITLE
game doesn't save after some uses

### ISSUE THREAD

**Issue by ABReaper** [TASVideos/desmume#387]
when i open a rom (for my case Bowser's Inside story), it says that it couldn't read/access to the battery save file, and I am no tech guy to do this.

**Comment by zeromus** [comment]
make backups of your .dsv file and pay closer attention to what you're doing to figure out what you did to break it.

**Comment by ABReaper** [comment]
i dont know what that means

**Comment by zeromus** [comment]
then find a tech guy to do this
