### ISSUE TITLE
Desmume crashes when opening .nds games

### ISSUE THREAD

**Issue by Storm-ctrl** [TASVideos/desmume#388]
Basically just the title. Whenever I try opening a .nds game with Desmume, it crashes. Whenever I open Desmume normally, it works just fine, but if I even dare to try opening a .nds game, it crashes. I'm on MacOS Catalina (10.15.6).

**Comment by zeromus** [comment]
https://github.com/TASVideos/desmume/issues/335

**Comment by Storm-ctrl** [comment]
Thank you, very cool
