### ISSUE TITLE
Does anyone know how the sound system for the DS works?

### ISSUE THREAD

**Issue by Retkid** [TASVideos/desmume#392]
Literally anyone? All the audi o code was commited by Roger and he seems inactive. I doubt im smart enough to understand all of it on my own? Does the DS use midi and soundfonts? If so how can i get the midi tracks from the games out of the code? if not there has to be a way to convert the instruction set to midi, how does it work? why not use midi? 

so many questions

**Comment by zeromus** [comment]
The audio code was not committed by roger.
The DS uses midi and soundfonts sometimes, mp3s some other times. Depends on the game.
To get the midi tracks out of the games, you gain enough experience reverse engineering that you aren't asking questions like this. Search for vgmtrans and use that and read documents associated with it.
