### ISSUE TITLE
Executable not launching anymore

### ISSUE THREAD

**Issue by NatKeely** [TASVideos/desmume#401]
There is juste the console opening but then the emulator won't start. Is there anything to do ? I have the actual latest release and the latest windows version with everything updated (before, the emulator worked on my computer). Thanks you for your help.

**Comment by zeromus** [comment]
delete your ini file, the window configuration has become broken

**Comment by eeuq7mi** [comment]
similar to: https://github.com/TASVideos/desmume/issues/138
The emulator crash with exception when I load a rom.
`Unhandled exception at 0x0000000140613c30 in DeSmuME-VS2019-x64-Release.exe:   0xC0000005: Access violation reading location 0x0000000000144000`

**This error is Common when upgrade from old version `0.9.11`, preserving the `ini` config file created by the old version.**

Delete ini solve this problem. **Thanks for the solution!**

**Comment by zeromus** [comment]
I wasn't able to reproduce by copying an ini from an old version to a new one.

**Comment by eeuq7mi** [comment]
Sorry that I didn't fully test it, I have recorded it in #417 .
