### ISSUE TITLE
Black background for DS window?

### ISSUE THREAD

**Issue by anlsh** [TASVideos/desmume#402]
The empty space around the DS screens in the emulator window is white. This looks ugly in full-screen mode, and so I would like the window's fill color to be black.

Current behavior:
https://preview.redd.it/1koga9tj5b751.png?width=1600&format=png&auto=webp&s=ad4a4b9e4141555bef1099e8c8dfc8a2a7b7a0b4

At least [two](https://forums.launchbox-app.com/topic/52978-desmume-fullscreen-white-edges-to-black/) [threads](https://www.reddit.com/r/PokemonROMhacks/comments/hgehc1/desmume_is_all_white_and_ugly_how_do_i_turn_the/fw9xs7k/) say that the solution is to set the "Display Method" under Config to OpenGL I can see the place where I assume they mean to select this (Config > Graphics Settings > the "3d core" field, where Softrasterizer is selected by default), but changing it to OpenGL does nothing. I have seen at least [one thread](https://sourceforge.net/p/desmume/bugs/1675/#4c21) suggesting that there should specifically be a "display method" option under "Config"

I've also seen [one](https://www.reddit.com/r/PokemonROMhacks/comments/hgehc1/desmume_is_all_white_and_ugly_how_do_i_turn_the/fw44uiz/) reference to a "theme" option which I can't find (does it even exist?). 

Yet another thread advises [actually modifying the desmume source](https://forums.desmume.org/viewtopic.php?id=10415) and recompiling it. Well, that's pretty overkill but I tried it out anyways, adding the following block of code

    GdkRGBA color;
    color.red = 0.0;
    color.green = 0.0;
    color.blue = 0.0;
    color.alpha = 1.0;

    gtk_widget_override_color(pDrawingArea, GTK_STATE_FLAG_NORMAL, &color);

after this line     https://github.com/TASVideos/desmume/blob/91f6e4a9ef7368237bc650ceaeead437e29cd93e/desmume/src/frontend/posix/gtk/main.cpp#L4376

... that does nothing either

---------------------------------------

What do i need to do to change the background color? I've done all my testing on the latest master (91f6e4a9ef7368237bc650ceaeead437e29cd93e)

**Comment by zeromus** [comment]
You're using the windows desmume, in windows, while discussing building hacks to linux source code. I don't even know what to do with this nonsense. If you have no display method option under config, then your solution is to run the windows desmume instead of ???? version. Changing the display method fixes it 100% of the time.

**Comment by anlsh** [comment]
Oh um, that's an easily-cleared up misunderstanding. I came across the screenshot on one of the threads I came across and just linked it here instead of actually taking my own screenshot- I figured it was quicker and just as illustrative. Sorry!

Anyways it is my deep sorrow to inform you that I do, run Ubuntu 20.04 and that unless I'm doing something wrong^1 then changing the display method works somewhat less than 100% of the time

1. Which I mean I totally still could be, that's why I'm asking. Here's a screenshot of my Config > Graphics settings window^2
2. A real one this time, not just something I dug up

**Comment by zeromus** [comment]
There is no display method option in the linux version.
Don't post bugs anywhere without writing LINUX in them. Otherwise you waste people's time.
Open a new ticket with a feature request to change the fill color to something more sensible and write LINUX in the topic.
