### ISSUE TITLE
Trojan:Win32/Spursint.F!cl

### ISSUE THREAD

**Issue by Superzypter** [TASVideos/desmume#404]
When downloading the file it gets deleted by windows. I dont want to use this file.. Is it safe?
Its the link from appveyor from the official desmume page..

**Comment by zeromus** [comment]
https://www.virustotal.com/gui/url/6f290a99b15e31344bbb904fa9133b9c60c6874f54f74795080a55ee4f9cb893/detection

**Comment by poesdelal** [comment]
Probably false positive in Chrome, try to download with another browser.
