### ISSUE TITLE
MAC - Fullscreen mode fills up background with red bars

### ISSUE THREAD

**Issue by schaarmax** [TASVideos/desmume#406]
Hi I have a question, maybe someone here can help me. A few hours ago I started seeing red bars next to my game in full screen mode. I'm using a mac and recently updated to Mac OS Big Sur. I'm running the newest desmume version. This is unrelated to the game I play, but happens everytime I press fullscreen and play for a few seconds. Also happened when using OpenEMU. Has anyone else who's using a mac run in to this issue?  

![image](https://user-images.githubusercontent.com/75286524/100686355-72367700-337e-11eb-9f9f-7b5953c3a2bb.png)

![image](https://user-images.githubusercontent.com/75286524/100686329-6480f180-337e-11eb-9613-94b8cc196df6.png)

![image](https://user-images.githubusercontent.com/75286524/100686367-782c5800-337e-11eb-9b46-3224b7baee04.png)

**Comment by zeromus** [comment]
You're lucky it works at all. Don't mess with anything. For most people, big sur broke desmume entirely.
I have been telling people to use openemu. I assume it's updated more frequently, but I could be wrong.
This will get fixed when the other 1000 tickets about this get fixed. Certainly next time a build is posted on desmume.org (but it could be years)

**Comment by schaarmax** [comment]
Alright, thanks man!
