### ISSUE TITLE
Opengl transparency issue

### ISSUE THREAD

**Issue by StephenLynx** [TASVideos/desmume#408]
Playing pokemon heartgold, in the Ecruteak gym everything is black when using opengl, except for characters. That seems to be because of the fog not being rendered at all. The for renders fine with software renderer.

https://i.imgur.com/jw5WBFf.png

ps: playing on linux opengl version 3.0 if I'm not mistaken.

**Comment by zeromus** [comment]
then youre either using a very very old linux version, or you need to change to softrasterizer renderer.
