### ISSUE TITLE
Small graphical glitch in "Professor Layton and the Spectre's Call"

### ISSUE THREAD

**Issue by renecatharsis** [TASVideos/desmume#410]
There's a small glitched orange line next to the main NPC in the early stages of the game "Professor Layton and the Spectre's Call". (EU version)

The line is only visible in OpenGL renderer, SoftRasterizer works fine.

Builds used: https://github.com/TASVideos/desmume/commit/ac507ebdc0d370073186bfa52b43e1fcbb877eaa
OS: Win10 Pro, 64-bit
System specs: Core i7-8750H, GeForce GTX 1060

![5953_layton_glitched](https://user-images.githubusercontent.com/1114906/103320843-436ff700-4a37-11eb-8dcb-9c56b4069f6a.png)
![5953_layton_rominfo](https://user-images.githubusercontent.com/1114906/103320845-44088d80-4a37-11eb-8703-603bb90cc95a.png)
[5953_layton_savegame.zip](https://github.com/TASVideos/desmume/files/5752550/5953_layton_savegame.zip)

See attached savegame. No savestates were used.
To reproduce, just load the only available save game, click through the cutscenes and tap on the first playable screen until the characters start a dialog.

**Comment by zeromus** [comment]
these are addressed usually by TXT HACK and are not likely to ever be fixed in the opengl renderers unless someone goes into a whole new level of detail and then all these will be fixed at once without addressing them individually
