### ISSUE TITLE
WIN - Interaction with desmume via windows messages

### ISSUE THREAD

**Issue by erwanvivien** [TASVideos/desmume#411]
I'm very noob to github, tell me if it's the place or not to send a message ?

### Problem:
Using c# to send `PostMessage` `WM_KEYUP`/`WM_KEYDOWN` I want to be able to make a bot to play on my game from far away.

I'm using the following code to try send the message. However I believe that the `current` I have is not the actual one
```
PostMessage(current, WM_KEYDOWN, keycode, 0);
PostMessage(current, WM_KEYUP, keycode, 0);
```

I decided to loop through all subprocesses (I have only 1 and I believe is the WindowToolBar32  - One containing the rotate CWW button) and it still does not work.

Is there a process which I should send my keys to ?

### Expected:
Being able to send keys to the main window and play the game.

### Actual:
Only able to send to the WindowToolBar32 and not the actual game (trying on Pokemon, but should not alter if other game)

Thanks for any help given !

**Comment by zeromus** [comment]
1. desmume doesn't handle keyboard input through WM_KEYUP and WM_KEYDOWN but rather directinput
2. use autohotkey or xpadder or similar to synthesize directinput
3. use lua, or use bizhawk+melonds
