### ISSUE TITLE
DeSmuME goes mad when loading a rom with diacritic characters in its file name.

### ISSUE THREAD

**Issue by ElektroStudios** [TASVideos/desmume#412]
### Issue description:

**DeSmuME** can't create a proper battery file name if the input rom file name has special characters (diacritics) from Windows-1252 text encoding.

From my point of view as a end user, the emulator seem to have some encoding bug for writing both in the debug console and the battery file name (it could be a lack of Unicode support?).

### Steps to reproduce:

Just insert any diacritic char in a rom file name (eg. "Máäàrio Kart DS.nds") and load the rom in **DeSmuME**.

( possible other characters that maybe **DeSmuME** does not properly support: áéíóú àèìòù äëïöü ñç )

### Demonstration:

This is the crazy **DeSmuME** behavior when loading a zipped rom with file name: "**Pokémon - Edición Blanca 2.zip**" (having the .nds rom the same file name as the zip file)

![alt text](https://i.imgur.com/lWXo3k6.png)

( clearly the emulator is not decoding right the rom file name. )

**Comment by zeromus** [comment]
stop using a 5 years old version of desmume

**Comment by ElektroStudios** [comment]
> 
> 
> stop using a 5 years old version of desmume

Stop assuming and accusing without asking which version I'm using:

![alt text](https://i.imgur.com/2Kbd1L1.png)

As you can see, I'm using the LATEST release.

What a way of yours to deal with users and their problems, just closing threads.

**Comment by zeromus** [comment]
Zip files are fundamentally flawed and lack encoding or codepage information on the 8 bit character strings, so there is no way to guess how to interpret the garbage sent to us by zip libraries. Zip libraries created in 2021 are still creating zips without using the informal extension that says to use UTF-8 encoding in cases where the local codepage could be used to encode latin characters.

Right now I assume I'm getting UTF-8 from the zipfile which is probably wrong. Just now I considered using the local codepage but instead decided to go deep into the crapped up layers of libraries we put in this emulator for opening archives and make wild guesses in a way which will work out more reliably.

**Comment by ElektroStudios** [comment]
THANKS for finally taking the time to review this issue and for explaining us how it internally works everything. (really, thanks)

Although I can't fully understand it because I ignore the relationship between the compression library and the file name (is the encoding of the name supposed to depend on a library flag?), anyway and in case of it helps: I use WinRAR 5.x to create the zip files.

The problem is still strange to me since other emulators from other console platforms that accepts zipped roms works fine when loading a zipped file with the same characteristics / diacritic characters, in fact this is the first emulator that gives me a problem of this kind with file name encoding.

I wish you all luck to fix this issue.
Cheers.

**Comment by zeromus** [comment]
Other emulators will have problems in other acses.

**Comment by ElektroStudios** [comment]
Last thing: I apologize with you, I have taken assumption on the second thread closing as a personal and childish attack, which is why I was enraged writing the thread quoting you on the title, but I was wrong because with the response you gave us here its clear that your intentions were not bad neither childish. Excuse me.

Cheers.

**Comment by ElektroStudios** [comment]
Las thing: I apologize with you, I have taken assumption on the second thread closing as a personal and childish attack, which is why I was enraged writing the thread quoting you on the title, but I was wrong because with the response you gave us here its clear that your intentions were not bad neither childish. Excuse me.

Cheers.
