### ISSUE TITLE
[Small Bug] 512 KB firmware + BIOS image, lead to crash when loading rom

### ISSUE THREAD

**Issue by eeuq7mi** [TASVideos/desmume#417]
**Firstly, thank the authors for providing this excellent project!**

Here I want to report a small problem. This small bug isn't so important (because little people use the firmware). I just post it for others to refer.

---

**OS:** Win 8.1 x64
**Emu Version:** v0.9.12 x64 compiled on Jan 7 2021
(v0.9.11 x64 compiled on Apr 13 2015, **doesn't** have this bug.)

**External Firmware:** 512KB iQue (256KB firmware **won't** cause this bug.)

Use external BIOS image only, or use the external 512KB firmware only **won't** cause the error. But when using external BIOS and 512KB firmware **at the same time**, the emulator will crash when opening a nds rom form the menu.

**Console Output:**
```
CPU mode: Interpreter
ARM7 BIOS load: OK.
ARM9 BIOS load: OK.

(And then the exception occurred.)
```

**Exception info:**
```
Unhandled exception at 0x00007ffee01812de in DeSmuME-VS2019-x64-Release.exe: 0xC0000005: Access violation reading location 0x0000000004de0000
```
(The address may change for different rom.)

**Comment by eeuq7mi** [comment]
After written this issue, i found a similar issue: #346

**Comment by zeromus** [comment]
As far as desmume is concerned, this is an invalid firmware file. If you want to submit a patch to check the size and reject the size somehow you're welcome to. It's gross though and will just junk up desmume. Consider that there may be no clean way to open the file at the point where it's needed to determine whether it's destiny to try loading it.

**Comment by eeuq7mi** [comment]
Thanks for reply! Hope the above info can help others when debuging the new version.
