### ISSUE TITLE
MacOS: touch input incorrectly mapped

### ISSUE THREAD

**Issue by ArchKevin22** [TASVideos/desmume#42]
When using the mouse to send input to the touch screen on the Mac, it is mapped incorrectly. See the video for details. The touch input looks like it's mapped to the upper right corner?

[touchprob.zip](https://github.com/TASVideos/desmume/files/812793/touchprob.zip)

Running on MacBook Pro 2016 15 inch.
GPU: AMD Radeon Pro 460 (probably irrelevant here)

**Comment by zeromus** [comment]
Are you using external firmware file

**Comment by ArchKevin22** [comment]
Tried with external firmware and without.

**Comment by ArchKevin22** [comment]
Upon further inspection, it seems that the touch input is mapped to both screens as if the touch screen is expanded to take the room of both screens.

**Comment by rogerman** [comment]
@ArchKevin22, your analysis doesn't make any sense.

Try playing a game like The Legend of Zelda: Spirit Tracks, which uses the touch screen to move Link around, and see if the problem persists. That game uses little sparkly stars to track the touch location in real time, so that should reveal the problem without any ambiguity.

**Comment by ArchKevin22** [comment]
Here is a video of me attempting to start a new game in Zelda.
[zvid.zip](https://github.com/TASVideos/desmume/files/812848/zvid.zip)

**Comment by rogerman** [comment]
@ArchKevin22, it seems like there may be a legitimate problem here.

Please choose Help > Submit a Bug Report and follow the onscreen instructions. When you get to the end, copy-paste the information here, thanks!

**Comment by ArchKevin22** [comment]
Should I post here or source forge? Which is more preferred?

**Comment by ArchKevin22** [comment]
I'll start with here.

App Version:  0.9.12 git#5e06fbc x64-JIT SSSE3 (LLVM-Clang v8.0.0)
Operating System: Mac OS X v10.12.3 (16D32)
Model Identifier: MacBookPro13,3
ROM Name: ZELDA_DS:PH
ROM Serial: NTR-AZEE-USA
-----------------------------------
Emulation Speed: 1.00x
Auto Frame Skip: YES
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: Auto
Advanced Bus-Level Timing: YES
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Dynamic Recompiler (BlockSize=100)
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
3D Renderer - Engine: SoftRasterizer (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Textures: YES
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Audio - Output Engine: OS X Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method
-----------------------------------
Cheats: YES (ActiveCheatCount=0)
-----------------------------------
Observed Behavior: When I click the touchscreen, it should click where the cursor is.

Expected Behavior: The mapping of the touchscreen seems to be extended to both screens covering only the left half of the touchscreen so the mapping is off.

**Comment by rogerman** [comment]
No need to post it on SourceForge. Just posting it here is fine.

**Comment by ArchKevin22** [comment]
Is there a way I can contribute? (as in help with the code) If I had some knowledge about how the touchscreen mapping works (and where the code in the touchscreen mapping is located in the project), I can attempt to mess around with stuff.

**Comment by rogerman** [comment]
You're using one of the new Touch Bar 2016 MacBook Pros, which has a Retina display, correct? Unfortunately, I haven't done a lot of testing on Retina displays, and I'm pretty sure that this issue has everything to do with that. I did a bunch of changes to that part of the code, and I may have broken something with Retina displays.

The best way to contribute for now is to test previous builds and find out where the regression started. Here's some good places to start:

2016/12/30 - [git#cf8f021](https://drive.google.com/uc?export=download&id=0B6Qy5vjjaIa6ajlhS05FWk1TdTQ)
2016/12/31 - [git#207a3b2](https://drive.google.com/uc?export=download&id=0B6Qy5vjjaIa6OV9GYk1aRFZQcjA)
2017/01/15 - [git#25c0232](https://drive.google.com/uc?export=download&id=0B6Qy5vjjaIa6dVAwWUx1MWdsSVE)

**Comment by ArchKevin22** [comment]
Broken on git#25c0232, the other two builds work fine.

**Comment by rogerman** [comment]
Yup, it's an issue with Retina displays. Most likely, I broke touch mapping on Retina displays in commit 858d14b, where I changed display views to use a CAOpenGLLayer instead of an NSOpenGLContext. This is definitely a fixable bug.

**Comment by ArchKevin22** [comment]
Nice.
