### ISSUE TITLE
Lua input regression

### ISSUE THREAD

**Issue by why-2004** [TASVideos/desmume#423]
in build 0.0.0.668, Lua scripts can read keyboard input with `input.get()`. In build 0.0.0.772, the same Lua script does not register any input.

Steps to reproduce: Open a lua file with `print(input.get())` in Lua scripting. On 0.0.0.668, it has been tested to produce the expected output, that is, keyboard keys being pressed and mouse positions. On 0.0.0.772, the output is empty,

**Comment by windwakr** [comment]
Can confirm. PR #350 completely breaks input in Lua.

**Comment by zeromus** [comment]
probably fixed

**Comment by windwakr** [comment]
That does seem to fix input.get, but controller.get remains broken.

**Comment by zeromus** [comment]
fixed again
