### ISSUE TITLE
Toggle sound option? 

### ISSUE THREAD

**Issue by lanceer** [TASVideos/desmume#424]
Hey zeromus,
First of all, incredible job on the emulator, much appreciated. Also, just wondering, what ever happened to that toggle sound option in the hotkeys configuration? I remember seeing it being there in earlier versions of desmume, but now I can't seem to locate it? 

Thanks.

**Comment by zeromus** [comment]
I don't remember it ever being there. Perhaps it was deleted when the hotkey system was rewritten. Perhaps whoever added multiple audio drivers considered it redundant after the option to set the sound core to "none" was added

**Comment by lanceer** [comment]
Appreciate the fast response. One last question, when running desmume, I have been receiving the Windows SmartScreen popup, and this has been happening ever since commit e5a7fbe6348b05f1082750cae791c46b2af1a888. When I ran builds before that, I did not receive the popup, any idea why this is?

**Comment by zeromus** [comment]
No. False positives are a fact of life for security software. There's nothing we can do about this, and further discussion on the topic won't be entertained.
