### ISSUE TITLE
Windows - Forced shutdown when selecting dynamic recompiler

### ISSUE THREAD

**Issue by nkfarwell** [TASVideos/desmume#425]
If you go to to Tools > Emulation Settings > CPU Emulation Mode and check the "Use dynamic recompiler" option and press "OK", you will be given a prompt telling you that DeSmuME needs to be restarted for it to go into effect and gives you an option of Yes or No. Regardless of which option is pressed, the emulator will shut down. I lost many hours of progress to this - please fix or add a warning before that a restart will happen as there is no warning before the prompt, at which point you no longer have an option and it will shut down. Thank you.

DeSmuME 0.9.12 git#6ef876b2

**Comment by zeromus** [comment]
The emulator does not shut down in either case. It may crash, though, I suppose. If you can give me reproducible steps to make it crash, I will look into it.
