### ISSUE TITLE
Firmware dims emulation in latest version (not the latest stable version)

### ISSUE THREAD

**Issue by jadasse** [TASVideos/desmume#427]
In the current latest version, 0.9.12git#6ef876b2 x64-JIT SSE2, whenever DESMUME boots into firmware.bin, the emulation dims horrifically for the rest of the emulation. However, in the outdated latest stable version, 0.9.11, booting into the firmware causes no problems. What's going on?

**Comment by zeromus** [comment]
Works fine for me. You must have set a low illumination setting in the firmware.

**Comment by jadasse** [comment]
It worked! Thanks dude!
