### ISSUE TITLE
About the RTC

### ISSUE THREAD

**Issue by Corpyo** [TASVideos/desmume#429]
I still don’t have the beta which i adsume has a functioning RTC mechanism. Was wondering how I can maybe acces it to get it working without the beta if it’s possible.

**Comment by zeromus** [comment]
Desmume has always had a functioning RTC mechanism.
The github desmume web site you are on right now has a link on the homepage that takes you to the downloads.

**Comment by Corpyo** [comment]
Sorry if I didn’t specify at first, I’m having trouble with the RTC on am IOS phone.

**Comment by zeromus** [comment]
desmume doesn't support ios. you're using software made by someone else
