### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by phineasandferbfangirl** [TASVideos/desmume#434]
App Version:  0.9.12 git#be2735b3 x64-JIT SSSE3 (LLVM-Clang v9.1.0)
Operating System: Mac OS X v10.15.7 (19H524)
Model Identifier: MacBookPro16,2
ROM Name: POKEMON D
ROM Serial: NTR-ADAE-USA
-----------------------------------
Emulation Speed: 2.00x
Auto Frame Skip: YES
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: None
Advanced Bus-Level Timing: YES
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
GPU - Color Depth: 18-bit
3D Renderer - Engine: SoftRasterizer (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Audio - Output Engine: OS X Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method
-----------------------------------
Cheats: NO
-----------------------------------
Observed Behavior: I went to use explorer kit, the game asked me to save, then the entire screen turned black and unresponsive. No music or anything. Tried reloading the save state but nothing is working.

Expected Behavior: To be underground.

**Comment by zeromus** [comment]
stop using savestates. save in-game frequently and close the emulator. open it again and load the in-game save.
