### ISSUE TITLE
Compiling with 'Dev+' option in Visual Studio 2019 doesn't produce a build with the GDB Stub enabled.

### ISSUE THREAD

**Issue by PlatinumMaster** [TASVideos/desmume#438]
Hello, I've been trying to enable GDB stub support for DeSmuMe, however when I compile it using the Dev+ option in VS2019 Community (which, per the configuration, has this GDB stub support enabled by default), it doesn't produce a build where I can use the `--arm9gdb=<port>` option.

**Comment by zeromus** [comment]
who told you to use `--arm9gdb=<port>` ? the command line help currently says `--arm9gdb port`.

**Comment by PlatinumMaster** [comment]
My bad. It seems like I had been looking at the wrong version of the README (since the older DeSmuME versions used the former syntax). It's working now.

**Comment by PlatinumMaster** [comment]
https://github.com/TASVideos/desmume/blob/master/desmume/README.WIN#L21
I had referred to this. But, I will make a PR to change it.

**Comment by zeromus** [comment]
those docs are woefully out of date in many more respects than just this

**Comment by PlatinumMaster** [comment]
Is there a more up-to-date document I can refer to?

**Comment by zeromus** [comment]
no.
