### ISSUE TITLE
Latest Build?

### ISSUE THREAD

**Issue by Zakkie32** [TASVideos/desmume#445]
Sorry if I'm asking this in the complete wrong place, but how can I download the latest build? On the AppVeyor page, under the Artifacts tab it just says "The build job does not contain any artifacts"

I've looked around but I'm not sure where exactly I'm meant to download the latest build, since the official DeSmuME website seems to be making it very obvious not to use the old stable releases

Thanks

**Comment by zeromus** [comment]
I said wait for a build, so if you can't see it, you haven't waited long enough.

**Comment by Jules-A** [comment]
Hmm... Didn't the expiry use to be 6 months?
