### ISSUE TITLE
Different graphics settings for both screens

### ISSUE THREAD

**Issue by qEagleStrikerp** [TASVideos/desmume#446]
I wondered if it was possible to set different graphics settings for both screens. I'm thinking of games that use 3D graphics on one screen and 2D graphics on the other. To produce the best results, you'd have to set 3D rendering settings for the first screen, and no rendering settings, but instead a magnification filter for the second one. Is there a way to do this currently?

Thanks in advance.

**Comment by zeromus** [comment]
no
