### ISSUE TITLE
Imposible to connect to WFC

### ISSUE THREAD

**Issue by JSenKai** [TASVideos/desmume#447]
Hi! I'm a newbie in Desmume emulator
So, I'm trying the WI-FI emulation with the instruccions in the wiki section, and almost work, but, for some reason, in the second try (the 5r step/instruction/point) did not connect. And the screen that advice "The information between console and card don't mach" appears in the second try.
What am I doing wrong?

**Comment by zeromus** [comment]
desmume does not support wifi.
