### ISSUE TITLE
When will 0.9.12 be released as "stable"?

### ISSUE THREAD

**Issue by phoenixeliot** [TASVideos/desmume#449]
OpenEmu, my preferred emulator app, only ports official "stable" releases of the cores it uses, and is thus very far behind on DeSmuME, because the latest stable release of DeSmuME was released in 2015.

When will 0.9.12 be released as "stable"? Is there any way to get something called a "stable" release some day soon so that the OpenEmu folks will be willing to use it?

See these two related bugs on their tracker, closed due to no "stable" release here, going back to 2016.
https://github.com/OpenEmu/OpenEmu/issues/2528
https://github.com/OpenEmu/OpenEmu/issues/4424

**Comment by zeromus** [comment]
Openemu's policies aren't our problem.

**Comment by phoenixeliot** [comment]
Sure. But do you know if there is any kind of plan for when 0.9.12 will be released as stable? Are there plans to make more stable releases? 

If not, then perhaps I can at least use that to convince them not to stick only to stable releases.

**Comment by zeromus** [comment]
There are no plans. We have no staff. Nobody is interested in desmume anymore. Desmume's had a bunch of garbage jammed into it over the past 6 years and nobody is working on cleaning it up. If we made a stable release it would be a stable release in name only and not actually stable.

**Comment by phoenixeliot** [comment]
Fair enough. Thank you for responding :)
