### ISSUE TITLE
When I increase the speed and then I instantly discrease it, Desmume crashes during few seconds... Also when I increase the speed the game sounds broken.

### ISSUE THREAD

**Issue by terminalAngellus** [TASVideos/desmume#450]

**Comment by zeromus** [comment]
Stop using an ancient version of desmume. Stop using cheats, hacks, and desktop enhancements.
As for the sound broken at increased speed, that's just how some games are. You may try changing the sound "synchronization mode"

**Comment by terminalAngellus** [comment]
I used the latest version, the one from the autobuild thing, also I've
never used cheats or hacks.
Anyway thanks for the response but I solved my problem !

**Comment by zeromus** [comment]
How did you solve it?
