### ISSUE TITLE
Screenshot only works properly in vertical layout

### ISSUE THREAD

**Issue by DeflatedPickle** [TASVideos/desmume#451]
When I take a screenshot with `Ctrl` + `S` (or via the menu item) with some different view settings (LCDs layout and rotation), I get the following results;

**Vertical**;
![desmume-screenshot-0](https://user-images.githubusercontent.com/24986480/122635459-fadaf180-d0db-11eb-8f69-047bcab165f4.png)
This is normal, this is what we want

**Horizontal**;
![desmume-screenshot-1](https://user-images.githubusercontent.com/24986480/122635475-0cbc9480-d0dc-11eb-98a3-c301a8cea083.png)
This is using the top screen for both halves and it's squished them for us

**Single Screen**;
![desmume-screenshot-2](https://user-images.githubusercontent.com/24986480/122635492-2d84ea00-d0dc-11eb-8bf1-28cfe9a89cff.png)
This shows the top screen, which is what we want

**Single Screen - Swap Screens**;
![desmume-screenshot-3](https://user-images.githubusercontent.com/24986480/122635507-41c8e700-d0dc-11eb-9857-83aca6a26f9c.png)
This is the top screen again, even though we want the bottom screen

**Single Screen - Swap Screens - Rotate 90°**;
![desmume-screenshot-4](https://user-images.githubusercontent.com/24986480/122635630-00850700-d0dd-11eb-8d33-206affab8657.png)
I don't know what this is

**Single Screen - Swap Screens - Rotate 180°**;
![desmume-screenshot-6](https://user-images.githubusercontent.com/24986480/122635672-3924e080-d0dd-11eb-984f-c9a8eba3f685.png)
Not only is this the wrong screen, the screenshot isn't rotated

**Comment by zeromus** [comment]
Can't repro. Are you using a 10years old desmume? Besides this. the specifications are for screenshot to have the exact formatting as the original game, not what you see on your screen. You use your OS screenshot to screenshot what you have on your screen. Due to desmume's extremely frail code for managing these window layouts dropped in by hackers who then scoot to never support it again, we can't even support an option to replicate that arrangement in screenshot.

**Comment by DeflatedPickle** [comment]
That's a very interesting history for the code, but no I was using the latest release. I don't know anything about how the rendering is done on the DS, nor Desmume, but I was hoping it was as simple as some kind of OpenGL canvas, for each screen, that could have its content hucked into a file (or even if it was one, have the screen size guessed and split the image). Because of that, I felt it wasn't something dependant on the operating system. I definitely can't reproduce the same output as it was giving, with my OS

**Comment by zeromus** [comment]
If you're not using windows then youre even more screwed, because the mac and linux ports don't have maintainers at all right now and are not likely ever to be fixed to any degree.
