### ISSUE TITLE
Question: which desmume version should I use?

### ISSUE THREAD

**Issue by rmmariano** [TASVideos/desmume#452]
The [download page](http://desmume.org/download/) says I shouldn't use the latest stable release, because there are problems with it.

Well, if I can not use the latest stable release, which version should I use? 

Which problems are there in the latest stable release? Will future versions support the battery files from the current stable release? Currently I'm using v0.9.11 on Ubuntu 18 and I'm worried about the compatibility with future versions.

Would there be any forecast of a new stable release? 

Thank you in advance.

**Comment by zeromus** [comment]
The top of that page tells you which version to use.
Problems in the latest stable release consist of the set of all problems fixed since the latest stable release.
Battery files will stay compatible forever.
There are no forecasts.
