### ISSUE TITLE
Where is the "Emulation -> GBA slot" option on Linux version?

### ISSUE THREAD

**Issue by rmmariano** [TASVideos/desmume#453]
I've noticed that on Windows version, there is an "Emulation -> GBA slot" option, but I do not find it inside my Ubuntu.

Where is this option? 

I'm migrating my games from Windows to Ubuntu and I am used to use this option.

Thank you in advance.

**Windows 7:**

![windows](https://user-images.githubusercontent.com/10242509/123886606-37052200-d926-11eb-9c3b-3008ee376581.png)

**Ubuntu 18:**

![ubuntu](https://user-images.githubusercontent.com/10242509/123886611-3bc9d600-d926-11eb-9be6-3fa13f7c3435.png)

**Comment by zeromus** [comment]
the linux version lacks this feature, among many others. try using the command line options.

**Comment by rmmariano** [comment]
@zeromus thank you for your warning.
I'm migrating the games, because I don't use Windows anymore, only Linux nowadays.
If you could add these features in the Linux version in the future, it would help us a lot.
What would be the command line to add a *.sav file to the GBA slot?
I've tried "--gbaslot-rom=/path/to/file.sav", but it didn't work.
I'm trying to send my pokémon from Gen III to Gen IV on platinum.
Thank you.

**Comment by zeromus** [comment]
You just passed a RAM file to the ROM argument. Pass the ROM file to the ROM argument. 
Since you're migrating from windows, you've used the windows UI before which says "Please make save file matching name with extension. sav"

**Comment by rmmariano** [comment]
Would the ROM file be the *.gba file?
I've tried to add this file as the argument or to point to the folder, but neither option worked, I do not know the reason.
I send below the commands outputs.
Thank you.

```
$ desmume pokemon_platinum.nds --gbaslot-rom=/path/Roms/pokemon_emerald.gba

Gtk-Message: 22:51:21.114: Failed to load module "canberra-gtk-module"
Slot 2: GBA Cartridge
Failed to set format: Invalid argument
Microphone init failed.
DeSmuME 0.9.11 svn0 dev+ x64-JIT
Using 4 threads for video filter.

(desmume:12312): Gtk-CRITICAL **: 22:51:21.218: IA__gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
SoftRast Initialized with cores=4

ROM game code: CPUE
ROM serial: NTR-CPUE-USA
ROM chipID: 00007FC2
ROM internal name: POKEMON PL
ROM developer: Nintendo

Slot1 auto-selected device type: Retail MC+ROM
GBASlot opening ROM: /path/Roms/pokemon_emerald.gba
 - Success (16777216 bytes)
GBASlot did not load associated SRAM.
BackupDevice: size = 4 Mbit
CPU mode: Interpreter
Already decrypted.
MMU9 write32 to undefined register 04000058h = 00000000h (PC:01FF857C)
...
Changing master brightness outside of vblank


$ desmume pokemon_platinum.nds --gbaslot-rom=/path/Roms
Gtk-Message: 22:51:48.075: Failed to load module "canberra-gtk-module"
Slot 2: GBA Cartridge
Failed to set format: Invalid argument
Microphone init failed.
DeSmuME 0.9.11 svn0 dev+ x64-JIT
Using 4 threads for video filter.

(desmume:12391): Gtk-CRITICAL **: 22:51:48.181: IA__gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
SoftRast Initialized with cores=4

ROM game code: CPUE
ROM serial: NTR-CPUE-USA
ROM chipID: 00007FC2
ROM internal name: POKEMON PL
ROM developer: Nintendo

Slot1 auto-selected device type: Retail MC+ROM
GBASlot opening ROM: /path/Roms
 - Success (4294967295 bytes)
GBASlot did not load associated SRAM.
BackupDevice: size = 4 Mbit
CPU mode: Interpreter
Already decrypted.
MMU9 write32 to undefined register 04000058h = 00000000h (PC:01FF857C)
...
Changing master brightness outside of vblank
...
```

**Comment by zeromus** [comment]
"GBASlot did not load associated SRAM."
/path/Roms/pokemon_emerald.sav does not exist

**Comment by rmmariano** [comment]
I've tested here again and both pokemon_emerald.gba and pokemon_emerald.sav files are inside the same folder, but the "GBASlot did not load associated SRAM" message appears, I do not know the reason.

Desmume on Windows loads the battery on the GBA slot normally, just on Ubuntu this message appears.
