### ISSUE TITLE
windows wont download properly

### ISSUE THREAD

**Issue by necusick** [TASVideos/desmume#455]
I go to the most recent version (currently the only version) and it downloads fine. though when I try to open the application I get the response "The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem." I've recently reinstalled windows if that may be what's causing the issue but this is not the first time I've run into this even before reinstalling windows. I'm not the best with computers, and I tried reinstalling desmume but that didn't help.

**Comment by zeromus** [comment]
https://www.google.com/search?q=desmume+VCRUNTIME140_1.dll

**Comment by necusick** [comment]
thank you
