### ISSUE TITLE
Lua51.dll missing on latest build

### ISSUE THREAD

**Issue by GhostFire90** [TASVideos/desmume#456]
Whenever i try to run a lua script i get the "lua51.dll was not found" error even though its 
1. In my path vars
2. In the same folder as the exe

**Comment by zeromus** [comment]
You found the 32bit lua51.dll

**Comment by GhostFire90** [comment]
No i did not, i specifically downloaded lua5.1.dll 64x

**Comment by zeromus** [comment]
https://www.google.com/search?q=desmume+lua51.dll
->
https://forums.desmume.org/viewtopic.php?id=11266
->
https://sourceforge.net/p/desmume/bugs/1628/

**Comment by GhostFire90** [comment]
I got that link FROM the sourceforge bug you linked
Please actually read what im saying, it doesnt work for me and the bug still exists

**Comment by zeromus** [comment]
OK, that sourceforge bug is old. do the 64bit equivalent of that
https://iweb.dl.sourceforge.net/project/luabinaries/5.1.4/Windows%20Libraries/lua-5.1.4_Win64_dll12_lib.zip

**Comment by Maverick7508** [comment]
Is there a working link? That source forge link doesn't load.

**Comment by zeromus** [comment]
https://sourceforge.net/projects/luabinaries/files/5.1.5/Tools%20Executables/lua-5.1.5_Win64_bin.zip/download

**Comment by Delcoii** [comment]
I found this method working

1. make directory "lua_dll" in C
2. add this dir to PATH env var ex) c:\lua_dll
3. add all components of lua-5.1.5_Win64_dll11_lib in this folder (lua5.1.dll, lua5.1.lib, lua51.dll, lua51.lib, include)
4. It works fine in deSmuME_0.9.13_x64.exe

**Comment by mintranik** [comment]
> I found this method working
> 
> 1. make directory "lua_dll" in C
> 2. add this dir to PATH env var ex) c:\lua_dll
> 3. add all components of lua-5.1.5_Win64_dll11_lib in this folder (lua5.1.dll, lua5.1.lib, lua51.dll, lua51.lib, include)
> 4. It works fine in deSmuME_0.9.13_x64.exe


Can you show visually how to do that? I tried to solve the error by putting the lua51.ddl in the same folder as the unmute, but it still doesn't work. I don't know what to do yet.

**Comment by zeromus** [comment]
I don't know is "unmute" but it sounds like an unsupported hack.
delcoii's method is poor.
here is the proper method.
1. download desmume, dearchive it
2. download the last lua library I linked, dearchive it into the same directory such that lua5.1.exe is in the same directory as DeSmuME_0.9.13_x64.exe

yes, there are only 2 steps. no picture is needed for such a simple operation.

if it doesn't work, clean your computer: you have broken junky luas in your PATH.

note, if you follow delcoii's method, you will now have luas in your path which will be broken junky from some other application's point of view. other applications doing this would be what breaks desmume in the first place.

But this is unlikely to be your problem.
