### ISSUE TITLE
Windows 10 PKMN White - Freezing mid/beginning of battle

### ISSUE THREAD

**Issue by lowotus** [TASVideos/desmume#461]
Hello, sorry if this possibly duplicates another issue but I've searched all over the internet and have found no solutions.
**I have an issue where whenever I enter a trainer battle, the game just freezes. It's shown in the File tab that the emulator is paused, but whenever I unpause it, it's still frozen but the music is still playing.**

I have tried:
- Reinstalling DeSmuME
- Installing an older version (0.9.11)
- Downloading the ROM from different websites
- Enabling and disabling "Advanced Bus-Level Timing"
- Enabling and disabling "Dynamic recompiler"
- Disabling and deleting cheats
- Saving in-game and creating new save states

If it's worth mentioning, I've been running randomized seeds.
Don't know what to do... :/

**Comment by zeromus** [comment]
You've cheated wrong by using a hacked or incorrect rom. Stop using cheats entirely. Save in-game. Delete everything (but save your .dsv) and download everything clean from scratch. Transplant the .dsv and load your game. You'll see that it works. Then you'll have proof you cheated/hacked wrongly.

**Comment by lowotus** [comment]
> You've cheated wrong by using a hacked or incorrect rom. Stop using cheats entirely. Save in-game. Delete everything (but save your .dsv) and download everything clean from scratch. Transplant the .dsv and load your game. You'll see that it works. Then you'll have proof you cheated/hacked wrongly.

Thank you sm for the help, I'll try that now.
