### ISSUE TITLE
What is with Game Hacks in DeSmuME?

### ISSUE THREAD

**Issue by P0W3** [TASVideos/desmume#462]
What is with Game Hacks? What is the whole point of using Game Hacks? To me, hacking is breaking the game.

![image](https://user-images.githubusercontent.com/18279115/130517340-f79676e7-3e9d-4f94-84b6-5f91999b011c.png)

I use DeSmuME (v0.9.12) (git#e8f619c4 x64-JIT SSE2) (Windows).

![image](https://user-images.githubusercontent.com/18279115/130517259-b132e109-df37-40c8-af28-9055e82d6d77.png)

**Comment by zeromus** [comment]
Game Hacks enables game-specific workarounds for buggy games. Including pokemon hg/ss.
