### ISSUE TITLE
Autobuild

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [TASVideos/desmume#463]
latest version doesnt autobuild for 32bit windows? can that be added?

**Comment by Jules-A** [comment]
> Oops, I forgot. In march 2020 support for x86 was removed by commit [347a3aa](https://github.com/TASVideos/desmume/commit/347a3aa833ab1b521b1f5b0597120dd23ef1cd2f)
> This won't be reconsidered or revisited. Sorry for the bad news.

Appveyor still seems to try to build x86 though which is causing the commits to show an X which makes it look like there's legit build failures when it's just the x86 build failing.

**Comment by zeromus** [comment]
That's only because I forgot to hit save after I removed it after I added it before I forgot that x86 support was removed

**Comment by MyTDT-Mysoft** [comment]
yeah check the latest build artifact where 32bit was still supported... and get that compiled... and release that last version as the last 32bit working version... dont kill the 32bit version with the outdated current "stable" version... thats kinda mean :P

**Comment by zeromus** [comment]
This build is the last one before x86 support was removed
[DeSmuME x86 (git#46980d77).zip](https://github.com/TASVideos/desmume/files/7095218/DeSmuME.x86.git.46980d77.zip)

This build predates the wifi work which caused the x86 support to be removed (many unrelated commits over the same time span are lost as well)
[DeSmuME x86 (git#e2d60f62).zip](https://github.com/TASVideos/desmume/files/7095219/DeSmuME.x86.git.e2d60f62.zip)

**Comment by cjquibael** [comment]
noce
