### ISSUE TITLE
Windows: Crash in memory viewer when selecting "Full" region.

### ISSUE THREAD

**Issue by windwakr** [TASVideos/desmume#47]
This crash happens when ROM loading is set to streaming. This is caused by the code interpreting the "Full" region option as the "CartROM" option, and vice versa.

Another issue with the memory viewer is that the region options don't update if you close the ROM and change the ROM loading option, which can lead to crashes.

**Comment by zeromus** [comment]
what IS the full region, anyway? it looks like nonsense to me. I want to delete it.

**Comment by zeromus** [comment]
This will automatically get fixed when I fix the rom loading system, which will be within a couple of months
