### ISSUE TITLE
Last commit display bug problem

### ISSUE THREAD

**Issue by Real96** [TASVideos/desmume#471]
I think that the screen is the only better way i have to explain this. I just downloaded last commit and didn't touch settings:

![image](https://user-images.githubusercontent.com/20956021/134048379-203c708a-cc70-42f0-adf1-c305ade7f7d8.png)

**Comment by rogerman** [comment]
Try commit e1cadfe and see if that works out for you.

**Comment by Real96** [comment]
> Try commit [e1cadfe](https://github.com/TASVideos/desmume/commit/e1cadfe11277d017abeb12932382361749952ebc) and see if that works out for you.

Just compiled d6e80e7, still same problem :/ i'm on windows tho

**Comment by zeromus** [comment]
broken for me too.
bisected it to 457872812005fa62e1bdee8e16cc84643e928703
