### ISSUE TITLE
Pokemon soulsilver bug

### ISSUE THREAD

**Issue by Genesisio22** [TASVideos/desmume#473]
App Version: v0.9.12
Operating System: macOS v11.6 (20G165)
Model Identifier: iMac21,1
ROM Name: POkemon soulsilver
ROM Serial: Unspecified
-----------------------------------
Emulation Speed: 2.00x
Auto Frame Skip: YES
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: None
Advanced Bus-Level Timing: YES
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
GPU - Color Depth: 18-bit
3D Renderer - Engine: SoftRasterizer (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Audio - Output Engine: OS X Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method
-----------------------------------
Cheats: YES (ActiveCheatCount=0)
-----------------------------------
Observed Behavior: When I talk to the guy in front of the ship that brings me in kanto the game is blocked and my character is blocked in front of the entrance of the ship 

Expected Behavior: Is simple I should enter in the ship but I can’t because it blocks before I  try to enter

**Comment by zeromus** [comment]
I searched for how to get on the ship and got about 30 different answers, so clearly it's complicated and most likely you just don't understand it.
