### ISSUE TITLE
Latest DeSmume SoftRaster texture scale bug for "Castlevania - Dawn of Sorrow (U)"

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#5]
Tested "Castlevania - Dawn of Sorrow (U)" with DeSmuME 0.9.12 git#3b92f41 downloaded from official web site on Windows 8.1 x64. 

My settings:
![settings](https://cloud.githubusercontent.com/assets/8726272/21003064/425b5558-bd64-11e6-94b6-15f2b85f0954.jpg)

TexScale 1x no bug.

![tex1x](https://cloud.githubusercontent.com/assets/8726272/21002985/bd8d45fc-bd63-11e6-96d1-8694c4598881.jpg)

TexScale 2x Title screen is corrupted.

![tex2x](https://cloud.githubusercontent.com/assets/8726272/21003007/e47247bc-bd63-11e6-8d52-5349937e5c54.jpg)

**Comment by rogerman** [comment]
Fixed in commit 36b192a.
