### ISSUE TITLE
Homebrew 'Bad Apple' by Gericom freezes after one minute, but only if detected as homebrew

### ISSUE THREAD

**Issue by windwakr** [TASVideos/desmume#52]
https://gbatemp.net/threads/bad-apple-for-the-nintendo-ds.466504/

As the title states, the homebrew soft freezes after one minute in DeSmuME, but only if DeSmuME detects it as homebrew. If you alter the four bytes in the header at 0xC0(logo) to '24 FF AE 51' so it's not detected as homebrew, it will play through with no problems.

**Comment by windwakr** [comment]
The crash is caused by GBA slot being set to 'auto'(the default setting). The slot apparently gets set to PassME for homebrew. But I'm not exactly sure why that causes a crash.

**Comment by zeromus** [comment]
I believe it causes typical libnds bootup stuff to select passme, which can't work (I'm pretty sure) beyond 32MB (the slot 2 bus simply can't address more than that). So this homebrew should fail on a hardware passme in some way, hopefully the same way as desmume. I'll let you close this if you can confirm or are otherwise convinced.

**Comment by windwakr** [comment]
Yeah, it checks for a valid data on the GBA slot :
https://github.com/devkitPro/filesystem/blob/4e894ee69a66b6a8e7e0c2144c35bf404f1733fa/source/nitrofs.c#L129

I'm guessing there's no easy way to test what version of libnds a homebrew was built with? It seems that any [homebrew built since 2010 shouldn't need the PassME option](https://github.com/devkitPro/filesystem/commit/cba5cb5d60ffe5d147926e9fa32f559d530ce944).

**Comment by zeromus** [comment]
Hmm. Thanks for that analysis. Maybe we shouldnt choose passme after all, if it's been so long. There will still be some homebrews that ONLY work with passme. But after almost a decade maybe it's time to change it.
