### ISSUE TITLE
SPU.cpp {Read,Write}{Byte,Word} code is wrong

### ISSUE THREAD

**Issue by BigBigos** [TASVideos/desmume#53]
Hello,

The ReadByte, ReadWord and their Write counterpart methods in SPU.cpp are filled with the following wrong code:

*(u8*)(thischan.timer + 1)

The intention was probably to take the second byte of a 2-byte u16 field. Endianess issues aside, this is wrong - it adds 1 to thischan.timer field value (not address) and converts it to u8 pointer before dereferencing. You probably meant:

*((u8*)&thischan.timer + 1)

This first takes thischan.timer pointer, converts the pointer to u8*, increments the address and deferences it.

I have created a patch for gentoo 0.9.11 version. It contains many things (most of them already fixed here) but it also has chunks for this file.

[desmume.zip](https://github.com/TASVideos/desmume/files/906951/desmume.zip)

**Comment by zeromus** [comment]
Phew, how did we not notice this stink in our attic for so long.  thanks
