### ISSUE TITLE
Mario Kart DS stuck in black screen.

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#54]
Mario Kart DS stuck in black screen if press "start" or "A" to skip intro after start a match.  

Tested with win32 latest test build downloaded from [https://ci.appveyor.com/project/zeromus/desmume/build/artifacts](url) .

OS: Windows 8.1 x64  
display card: nVidia GTX 760M

Steps to reproduce this bug:
(1) download desmume test build from  https://ci.appveyor.com/project/zeromus/desmume/build/artifacts
(2) load Mario Kart DS (US)
(3) start a racing:
      GRAND PRIX --> 150 CC --> select Yoshi --> MUSHROOM CUP
(4) press start button quickly to skip the intro
(5) if not stuck in black screen, just quit the match and repeat step (3) to step (5)

I always get stuck in black screen by repeat step (3) to step (5) less than 3 times.

my desmume.ini can download from here: http://www.mediafire.com/file/gaj3ka3farze3r8/desmume_ini.zip

![screen](https://cloud.githubusercontent.com/assets/8726272/24831833/8c8e41a6-1cd4-11e7-9575-fe8ba9d20323.jpg)

**Comment by zeromus** [comment]
try on a few old builds. i can't believe something like this has been broke for long.

**Comment by intact** [comment]
Git bisect points to this commit https://github.com/TASVideos/desmume/commit/adf682eb23fbbcdb93f2f4045cd4aeb0d9a40e6c
