### ISSUE TITLE
Target FPS doing nothing

### ISSUE THREAD

**Issue by Phoenax** [TASVideos/desmume#540]
So, I just noticed a new release (0.9.13, windows, x64) and installed it today. With previous version (0.9.11), I had no problem with increasing and decreasing Target FPS, but, after instaling the new one, it seems to have no effect. Ended up installing 0.9.11 again, but the problem now persists, even though it never happened before. Changed magnification scale, and it would work with some, but now it doesn't work with any.

Idk if anyone has had this problem before, it's just kinda annoying

**Comment by zeromus** [comment]
define "problem" and "effect". What effect do you expect? does anything display on-screen when you press - or =?

**Comment by Phoenax** [comment]
Sry, my first time.

Display appears "Target FPS went up to <number>" or "Target FPS went down to <number>" when i press - and + (hotkey appears as = for some reason", but no speedup/down happen (like I said, it did before).

**Comment by zeromus** [comment]
your keyboard doesn't have a + key, it has an = key that prints + when you press it while holding shift.
I don't believe no slowdown happens. What's your proof that no slowdown happens?

**Comment by Phoenax** [comment]
Well, no, it's not an English layout. + and = are 2 different keys here. In case you don't know, google "Portuguese Keyboard Layout" to see the differences.

Either way, like I said, no apparent speed up / down when I use it. Emulation plays at the same speed whether the Target FPS value is at 1.0, 0.0625 or 4.0, which didn't happen before, it allowed me to play at 2x speed (I find pokemon games really slow with lot's of animations and the early walking without bicycle).

As to proof, I can record my screen, if needed.

**Comment by Phoenax** [comment]
It's a bit small, but had to stick to 25MB, but I think it's good enough to see

**Comment by Phoenax** [comment]
Just some seconds, as I had to stick to 25MB, but I think good enough to see what's happening 
[Target FPS.zip](https://github.com/TASEmulators/desmume/files/8823093/Target.FPS.zip)
