### ISSUE TITLE
 Defcon Zero by scarab problems

### ISSUE THREAD

**Issue by benderscruffy** [TASVideos/desmume#56]
http://www.pouet.net/prod.php?which=53004
the first screen is missing the text and planets (top screen)
then after that the top screen goes black during the demo

**Comment by zeromus** [comment]
fixed also by 
https://github.com/TASVideos/desmume/commit/e332e3df262d368518293aaff73b09bc9511088b

Main issue seemed to be an intersection of some sloppy register initialization combined with newer emulation (not implemented in previous revisions of desmume) of the geometry engine power-down clearing registers. The sloppy initialization was fixed, so now these games rendering survive geometry engine power-down
