### ISSUE TITLE
Full screen one LCD layout bug for OpenGL display backend. 

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#6]
My settings:
![setting1](https://cloud.githubusercontent.com/assets/8726272/21006089/4a7640fa-bd72-11e6-81f6-01da5dbe43ab.jpg)

![setting2](https://cloud.githubusercontent.com/assets/8726272/21006095/53748fb8-bd72-11e6-98f9-2597c08d2e7b.jpg)

Fullscreen mode:
![lcd layout](https://cloud.githubusercontent.com/assets/8726272/21006125/6848f2c6-bd72-11e6-9f48-659bfdf0ddc4.jpg)

Window mode:
![lcd layout2](https://cloud.githubusercontent.com/assets/8726272/21006159/8e8ca3e2-bd72-11e6-82a1-c85cfdd0a5fb.jpg)

**Comment by zeromus** [comment]
You've changed smoething you haven't shown me, or you have some desktop enhancement/streaming software (whatever that pink HUD is?) breaking the software. 
In the One Screen LCD scenario Desmume DOES draw the sub screen at a nonsensical position (albeit transformed to 0x0) but you've got something inflating it back up.

**Comment by ppsspp-gamer** [comment]
(1) the pink HUD is RivaTuner Static server for display GPU loading and FPS (part of MSI after burner).
(2) you can reproduce this bug by following the steps: 
     (a) change your desktop resolution to 1280x720 and 
     (b) set Desmume internal resolution to 3x
     (c) switch LCD layout from two panels left/right to one panel at full screen mode when game is running.
