### ISSUE TITLE
Save State Corruption

### ISSUE THREAD

**Issue by Felipefpl** [TASVideos/desmume#629]
I made a save state on Dragon Quest 4 and i got the message below when i tried to load it, i'm using the nightly i got on January 30:

![Save State](https://user-images.githubusercontent.com/5569804/216047915-324b6d17-0619-45db-a3c8-5f2780d0b470.gif)

**Comment by zeromus** [comment]
about where in the game were you when you made that state?

**Comment by Felipefpl** [comment]
This happened in the opening of the game, i like to use the save state there, it'a a habit of mine, can be useful when testing settings to make the game faster. But this also happens in-game.

**Comment by zeromus** [comment]
during the title screen? or during the actual script opening during the monster attack in the town?

**Comment by Felipefpl** [comment]
It happens everywhere. there is not a specific place where it happens.

**Comment by zeromus** [comment]
@rogerman this doesnt happen on be287de623ccd24988182f094bce63bb2e7ede84
to test just load dragon quest 4, wait for publisher splash (square and artepiazza), savestate, and loadstate. there is some mismatch between the structure of the save and load operations

**Comment by rogerman** [comment]
Well drat, I really took great pains to respect the original save state format when I did commit 5426509e. I'll take a look at it.

**Comment by Felipefpl** [comment]
Tested on intro/in-game and it works now, thanks zeromus and rogerman.
