### ISSUE TITLE
Slot 1 set to "Retail Debug" crashes DeSmuME since c365617f

### ISSUE THREAD

**Issue by windwakr** [TASVideos/desmume#63]
Open DeSmuME, set Slot 1 to "Retail Debug", and it will immediately crash. This happens since commit c365617f.

**Comment by windwakr** [comment]
Well, now that it doesn't crash I can't actually use the feature. I just get a black screen on the game.



Also, don't feel like opening another issue but the nitroFS viewer now has problems extracting certain files. It just makes 0 byte files in some cases, and in others it fills the file with garbage until DeSmuME crashes.

**Comment by zeromus** [comment]
Give me an exact example. I checked to make sure the filesystem looked ok in the tree view but not extracting any files

**Comment by windwakr** [comment]
With a fresh copy of DeSmuME, open up Suikoden Tierkreis and open up the nitroFS viewer then extract all.
