### ISSUE TITLE
NitroFS viewer doesn't properly extract files unless emulation is paused

### ISSUE THREAD

**Issue by windwakr** [TASVideos/desmume#65]
Example: Load up Suikoden - Tierkreis, open up the NitroFS viewer and extract 'data/rom/ds_data_vow.sdat' while the audio to the opening cinematic is playing. Then pause emulation and extract it again. If you compare the files you should see differences. It seems like the extraction fails on files being read by the game, or something.

**Comment by zeromus** [comment]
greaaaat. the tools all run in ANOTHER THREAD.

**Comment by windwakr** [comment]
Yeah, that seems to fix it.
