### ISSUE TITLE
posix-main.cpp ‘OGLLoadEntryPoints missing includes

### ISSUE THREAD

**Issue by noabody** [TASVideos/desmume#76]
In file - desmume/desmume/src/frontend/posix/main.cpp
Missing include around line 41 which should read:
#include "OGLRender.h"
#include "OGLRender_3_2.h"

Build fails if not present and generates error:
main.cpp: In function ‘int common_gtk_main(configured_features*)’:
main.cpp:3395:35: error: ‘OGLLoadEntryPoints_3_2’ was not declared in this scope
     OGLLoadEntryPoints_3_2_Func = OGLLoadEntryPoints_3_2;
                                   ^~~~~~~~~~~~~~~~~~~~~~
main.cpp:3396:34: error: ‘OGLCreateRenderer_3_2’ was not declared in this scope
     OGLCreateRenderer_3_2_Func = OGLCreateRenderer_3_2;
                                  ^~~~~~~~~~~~~~~~~~~~~

#if defined(HAVE_LIBOSMESA) || defined(HAVE_GL_GLX)
#include <GL/gl.h>
#include <GL/glu.h>
#include "OGLRender.h"
#include "OGLRender_3_2.h"
#include "osmesa_3Demu.h"
#include "glx_3Demu.h"
#endif

libosmesa6:
  Installed: 1:17.2~git170722002800.30d6bc4~z~padoka0

Maybe missing that I have libosmesa installed and so skips the include at line 72.

**Comment by zeromus** [comment]
#if defined(HAVE_LIBOSMESA) || defined(HAVE_GL_GLX)
    OGLLoadEntryPoints_3_2_Func = OGLLoadEntryPoints_3_2;
    OGLCreateRenderer_3_2_Func = OGLCreateRenderer_3_2;
    #endif

try this instead

**Comment by noabody** [comment]
Sorry about that.  It's something in my system.
/usr/bin/ld: cannot find -llibosmesa
collect2: error: ld returned 1 exit status
