### ISSUE TITLE
[OpenGL] Incorrect colors in the last builds.

### ISSUE THREAD

**Issue by CesarAxe** [TASVideos/desmume#77]
I tried with OpenGL 3.2 and OpenGL Old.
Tested games: Super Mario 64, Mario Kart DS and Dementium The Ward.
Hardware: AMD Radeon R7 250.
![1](https://user-images.githubusercontent.com/17837481/28585963-bab174e2-7137-11e7-8d31-49d088bee311.png)
![214](https://user-images.githubusercontent.com/17837481/28585969-c3334910-7137-11e7-8d44-cc708c49d2c3.png)

**Comment by zeromus** [comment]
Please turn off the 3d renderer entirely before assuming a bug has anything to do with 3d
