### ISSUE TITLE
Pokémon Black (IRBO01): "Auto Run 1.1" code crashes the emulator

### ISSUE THREAD

**Issue by autofire372** [TASVideos/desmume#78]
62003D00 4A176120
E2003D00 00000070
4A176120 4B176810
D11C4298 4A16A310
48166812 28005C10
22F0D116 D1134211
42112202 8C18D111
D10A2801 7A104A0C
D0032824 70982002
E0012024 709820FF
20007210 47708418
321E2203 54982001
D1024770 4C0220FF
20027220 47704208
021A4DDC 6871D028
02000024 0003448D
D2000000 00000000
52035FC8 E5840010
02035FC8 FAFF374C
D2000000 00000000
521A4DE0 42082002
021A4DE0 FFB7F65E
D2000000 00000000

The preceding AR code currently causes the emulator to crash to desktop regardless of whether the JIT is enabled or not.

**Comment by zeromus** [comment]
that version of destine has bugs with AR codes

**Comment by zeromus** [comment]
*desmume. i can't edit posts on my friggin phone, it's perpetual amateur hour at github hq

**Comment by autofire372** [comment]
What version of desmume do you think I'm running? I'm going off of current master...

**Comment by zeromus** [comment]
i thought you were running a version that had a bug that was the bug that you had, naturally, since you didn't specify. i'll investigate.

**Comment by zeromus** [comment]
This cheat is nonsense. It says to copy 709820FF bytes from the cheat code.
If it actually works on real hardware (I doubt it) we can't support it without someone improving the state of the art in understanding how nonsense codes work on the AR firmware.

**Comment by autofire372** [comment]
Unfortunately, I can confirm that this code works as intended on real hardware.

**Comment by zeromus** [comment]
This code doesn't have nonsense in it.
There's nothing we can do without someone reverse engineering the illegal code behaviour better.

**Comment by autofire372** [comment]
So, somehow the cheat I reported as broken is now working in desmume without a hitch. This is odd, as the "fix" zeromus merged merely stopped the code from working altogether, and I can't find anything else in the commit history between then and now that touched cheat handling...

**Comment by autofire372** [comment]
You have successfully reduced my interest in your emulator to zero as well, jerk.
