### ISSUE TITLE
wifi.cpp line 317, line 319

### ISSUE THREAD

**Issue by edbird** [TASVideos/desmume#83]
Lines:

#define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) LOGC(8, "WIFI: "__VA_ARG);

#define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);

Errors:

               wifi.cpp: In function ‘void WIFI_triggerIRQ(u8)’:
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:648:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(3, "IRQ 12 triggered.\n");
   ^~~~~~~~
wifi.cpp: In function ‘void WIFI_TXStart(u32)’:
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:889:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(4, "TX slot %i trying to send a packet: TXCnt = %04X, TXBufLoc = %04X\n",
  ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:898:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(1, "TX slot %i trying to send a packet overflowing from the TX buffer (address %04X). Attempt ignored.\n",
    ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:906:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(1, "TX slot %i trying to send a packet with length field set to zero. Attempt ignored.\n",
    ^~~~~~~~
wifi.cpp: In function ‘void WIFI_write16(u32, u16)’:
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:974:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(5, "Write at address %08X, %04X\n", address, val);
  ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:1131:5: note: in expansion of macro ‘WIFI_LOG’
     WIFI_LOG(2, "TXBUF_REPLY=%04X\n", WIFI_IOREG(REG_WIFI_TXBUF_REPLY1));
     ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:1182:5: note: in expansion of macro ‘WIFI_LOG’
     WIFI_LOG(3, "Beacon transmission enabled to send the packet at %08X every %i milliseconds.\n",
     ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:1201:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(4, "Write to TXRESET: %04X\n", val);
    ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:1213:22: note: in expansion of macro ‘WIFI_LOG’
    if (val & 0xFFF0) WIFI_LOG(2, "Unknown TXREQ bits set: %04X\n", val);
                      ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:1286:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(3, "EXTRACOUNT=%i (%i �s)\n", val, val*WIFI_CMDCOUNT_SLICE);
    ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:1343:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(2, "Write to RXSTAT register: %03X = %04X\n", address, val);
    ^~~~~~~~
wifi.cpp: In function ‘u16 WIFI_read16(u32)’:
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:1368:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(5, "Read at address %08X\n", address);
  ^~~~~~~~
wifi.cpp:319:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
wifi.cpp:1560:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(2, "Read to TXBUF_TIM @ %08X %08X\n", NDS_ARM7.instruct_adr, NDS_ARM7.R[14]);
    ^~~~~~~~

**Comment by zeromus** [comment]
your source code is corrupted. 
that
https://github.com/TASVideos/desmume/blob/master/desmume/src/wifi.cpp#L323
isnt
https://github.com/TASVideos/desmume/blob/master/desmume/src/wifi.cpp#L325
the source

**Comment by edbird** [comment]
I'm not sure what you mean here - I've checked my source and it appears to be the same as the lines linked above. What is different?

**Comment by zeromus** [comment]
The parts you bolded somehow in your error logs you posted
