### ISSUE TITLE
ctrlssdl.cpp

### ISSUE THREAD

**Issue by edbird** [TASVideos/desmume#84]
I think this might be an SDL issue rather than a desume one, but I am not sure?

I have no idea how to "sidestep" around this one - so I can't carry on attempting to compile this.

Is is possible I am linking against the wrong SDL version libs? I have both 1.2 and 2.0 installed. Which version does desume expect?

../ctrlssdl.cpp: In function ‘u16 get_joy_key(int)’:
../ctrlssdl.cpp:203:39: error: invalid operands of types ‘__gnu_cxx::__enable_if<true, double>::__type {aka double}’ and ‘int’ to binary ‘operator>>’
           if( (abs(event.jaxis.value) >> 14) != 0 )
                ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../ctrlssdl.cpp: In function ‘int do_process_joystick_events(u16*, SDL_Event*)’:
../ctrlssdl.cpp:373:36: error: invalid operands of types ‘__gnu_cxx::__enable_if<true, double>::__type {aka double}’ and ‘int’ to binary ‘operator>>’
       if( (abs(event->jaxis.value) >> 14) != 0 )
            ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
Makefile:555: recipe for target '../ctrlssdl.o' failed

**Comment by zeromus** [comment]
this isn't a SDL problem. it's using 1.2 correctly or else you'd get way more errors than that.
you're using alien source code again.
1. those lines do not correspond to the current code
2. your compiler thinks jaxis.value is a double, apparently. lord knows where that came from. not from the desmume sources, I can tell you that. probably your SDL sources are as scrambled as your desmume sources

**Comment by edbird** [comment]
I got the desume sources from here (github) so I don't understand what's going on here.
