### ISSUE TITLE
[OpenGL] Problem in the darkness of Dementium The Ward

### ISSUE THREAD

**Issue by CesarAxe** [TASVideos/desmume#88]
I tried in the last build.
Incorrect:
![1](https://user-images.githubusercontent.com/17837481/28942710-faef5782-7861-11e7-8da8-405876357828.PNG)
In a build of 9 days ago:
Correct:
![2](https://user-images.githubusercontent.com/17837481/28942732-09c72fd2-7862-11e7-93ec-09d008cf3e07.PNG)
![34](https://user-images.githubusercontent.com/17837481/28942759-29f3d3aa-7862-11e7-9f5b-b39497939e58.PNG)

**Comment by rogerman** [comment]
The darkness in that game requires fog emulation, which does seem to work just fine... except for when MSAA is being used. Commit f8ab45f fixes fog emulation for MSAA. I can't find any other cases where fog emulation would fail.

Please try commit f8ab45f and see if this resolves your issue.

**Comment by CesarAxe** [comment]
Works fine, the problem was resolved, thanks..
