### ISSUE TITLE
The Legend of Zelda Spirit Tracks (Extreme slow down)

### ISSUE THREAD

**Issue by tabnk** [TASVideos/desmume#9]
Build = 2016/12/10 – git#1787081
Setting: 
Both JIT or No JIT. 
Both native OpenGL 3.2 and Software mode

It was fine on older build (2015/2014) but slow down when using latest of build (2016)

![image](https://cloud.githubusercontent.com/assets/10874582/21121756/1f6cfb02-c109-11e6-9119-5dd4c9bf113f.png)

**Comment by zeromus** [comment]
Looks like about how fast it should be run if you made a debug build
