### ISSUE TITLE
shared/mic_alsa.cpp:167:27: error: 'write32le' was not declared in this scope

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [TASVideos/desmume#95]
Hi,
I'm using gcc 6.4.1 on Fedora 25.  The error occur when compiling desmume.
If I write

void wirte32le(u32, void*);

in shared/mic_alsa.cpp this error disappears.  So, maybe we have to include
some header file?

The error detail:

depbase=`echo shared/mic_alsa.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"desmume\" -DPACKAGE_TARNAME=\"desmume\" -DPACKAGE_VERSION=\"svn\" -DPACKAGE_STRING=\"desmume\ svn\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"desmume\" -DVERSION=\"svn\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSVN_REV=0 -DSVN_REV_STR=\"0\" -DHAVE_LIBZ=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_LIBDL=1 -DHAVE_LIBGL=1 -DHAVE_GL_GLX_H=1 -DHAVE_GL_GLX=1 -DHAVE_JIT=1 -DHOST_LINUX=1 -DHOST_64=1 -I.  -I./../../../src/ -I./../../../src/libretro-common/include -I./../../../src/frontend -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/alsa      -g -O2 -MT shared/mic_alsa.o -MD -MP -MF $depbase.Tpo -c -o shared/mic_alsa.o shared/mic_alsa.cpp &&\
mv -f $depbase.Tpo $depbase.Po
shared/mic_alsa.cpp: In function 'void mic_savestate(EMUFILE*)':
shared/mic_alsa.cpp:167:27: error: 'write32le' was not declared in this scope
     write32le((u32)(-1),os);
                           ^
Makefile:1646: recipe for target 'shared/mic_alsa.o' failed
make[1]: *** [shared/mic_alsa.o] Error 1

**Comment by tokumeiwokiboushimasu** [comment]
Oh, but if I write 

void wirte32le(u32, void*);

in shared/mic_alsa.cpp, ld returns the error below.

undefined reference to `write32le(unsigned int, void*)'
collect2: error: ld returned 1 exit status
Makefile:557: recipe for target 'desmume' failed
make[2]: *** [desmume] Error 1

Hmm, alsa version issue?

**Comment by zeromus** [comment]
fix taking clues from this commit, where it was surely broken
11cf901336d77574e0f2c3482e130e05fa5f03e4
