### ISSUE TITLE
Visual Studio 2017 Compiling error

### ISSUE THREAD

**Issue by ravenscope** [TASVideos/desmume#96]
I loaded a project (DeSmuME.sln) into Visual Studio 2017 Community.　I tried to make a release build.
However, I could not build with the following error.　Please tell me how to fix it.

> 1>------ ビルド開始: プロジェクト: DeSmuME, 構成: Release Win32 ------
> 1>指定されたパスが見つかりません。
> 1>C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: コマンド ""%windir%\Sysnative\cscript" /nologo /E:JScript "defaultconfig\make_scmrev.h.js"
> 1>C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" はコード 3 で終了しました。
> 1>プロジェクト "DeSmuME.vcxproj" のビルドが終了しました -- 失敗。
> ========== ビルド: 0 正常終了、1 失敗、0 更新不要、0 スキップ ==========

**Comment by zeromus** [comment]
sounds like cscript.exe is missing on your system. confirm it exists at c:\windows\syswow64\cscript.exe and c:\windows\system32\cscript.exe

**Comment by ravenscope** [comment]
My environment is Windows 7 Pro SP1 (x86), so I confirmed c:\windows\system32\cscript.exe and it existed.

**Comment by zeromus** [comment]
change line 87 of desmume.props to say system32 instead of sysnative

**Comment by ravenscope** [comment]
I changed the code and I got a different error.
> 1>------ ビルド開始: プロジェクト: DeSmuME, 構成: Release Win32 ------
> 1>Cannot find git or git.cmd, check your PATH:
> 1>C:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86;C:\Program Files\Microsoft SDKs\Windows\v7.1A\\bin;;C:\Program Files\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools;C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\tools;C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\ide;C:\Program Files\HTML Help Workshop;;C:\Program Files\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\windows\Microsoft.NET\Framework\v4.0.30319\;C:\windows\SysWow64;;C:\Program Files\ALSI\InterSafe Client\SecurePDF;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Common Files\Roxio Shared\10.0\DLLShared\;C:\Program Files\Common Files\Roxio Shared\DLLShared\;C:\Program Files\Windows Live\Shared;C:\Program Files\QuickTime\QTSystem\;
> 1>C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: コマンド ""%windir%\system32\cscript" /nologo /E:JScript "defaultconfig\make_scmrev.h.js"
> 1>C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" はコード 1 で終了しました。
> 1>プロジェクト "DeSmuME.vcxproj" のビルドが終了しました -- 失敗。
> ========== ビルド: 0 正常終了、1 失敗、0 更新不要、0 スキップ ==========

**Comment by zeromus** [comment]
That error message explains itself. You have no git instealled on your system.

**Comment by ravenscope** [comment]
Does that mean I need "git" to build desmume?

**Comment by ravenscope** [comment]
After installing git, I succeeded in building desmume.
zeromus, thanks for helping me.
