### ISSUE TITLE
358/2 kh beast castle transparency issue

### ISSUE THREAD

**Issue by Sudoloo** [TASVideos/desmume#98]
![transperency image](https://user-images.githubusercontent.com/4110158/30778019-2ea66fde-a08f-11e7-92b1-d1034103535f.png)

as seen in the image, open gl 3.2 rendering, and old gl, causes many transparency issues in this area, softrasterizer doesn't have the issue. none of the optional options (save for changing the rendering engine to softr) fixed the area after toggling on/off, entire room's textures are transparent for most part, excluding some walls and floors.

apologies if this is not the location to post this, but this seemed in line with other posted issues.

addendum, it is completely playable

**Comment by rogerman** [comment]
Most likely related to #74 and #24.

**Comment by mgitkun** [comment]
What version/build was this?
I can't reproduce this issue..........not sure if @rogerman checked it or not but I assume that screenshot is from a really old build. I know that the last stable build (0.9.11) had these issues for sure.

Here's a video of Beast's Castle in 0.9.11 and the latest autobuild (1742114)
https://vimeo.com/235193902 
And here's another video of it working normally with literally every graphics 'hack' (MSAA, Smooth Textures, 6x GPU Scaling, 24 bit color, deposterization, 4x Texture Scaling, and normal filter) 
https://vimeo.com/235192728

**Comment by rogerman** [comment]
mgitkun, thanks for the videos. Now I can see exactly what is going on.

This is not an issue with polygon transparency -- this is actually an issue with missing polygons.

In builds prior to r5372, OpenGL's stencil buffer was used to emulate transparent polygon IDs, but the implementation had serious bugs. Missing polygons was one of this implementation's greatest shortcomings.

Starting with r5372, the stencil buffer is now used to emulate shadow polygons, while at the same time fixing the issue with the missing polygons. This rework was finalized in commit 68958a7.

Therefore, this issue has already been fixed. Please one of our nightly builds at http://desmume.org/download if you want this scene to render correctly in OpenGL. Alternatively, if you want to continue using v0.9.11, then switch your 3D renderer to SoftRasterizer.
