### ISSUE TITLE
0.9.11 can't start win 10

### ISSUE THREAD

**Issue by PoKeCrAfT2001** [TASVideos/desmume#99]
I recently downloaded 0.9.11 on windows 10 and followed this tutorial https://www.youtube.com/watch?v=ItaWDQBLztg but when I double click the app it shows "The code execution could not proceed because MSVCP100.dll was not found. Reinstalling the program may fix this problem." followed by "The code execution could not proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem." Reinstalling the program did not fix this problem. PLZ tell me what to do.

**Comment by zeromus** [comment]
http://www.lmgtfy.com/?q=MSVCP100.dll+was+not+found
